[workspace]
resolver = "2"
members = [
    "crates/melee-core",
    "crates/melee-sim",
    "crates/melee-neat",
    "crates/melee-worker",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = "line-tables-only"

[profile.dev]
debug = "line-tables-only"
