module Evergreen.Migrate.V2 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V1.Auth.Common
import Evergreen.V1.Logger
import Evergreen.V1.Melee.Battle
import Evergreen.V1.Melee.Element
import Evergreen.V1.Melee.Graphics
import Evergreen.V1.Melee.Id
import Evergreen.V1.Melee.Input
import Evergreen.V1.Melee.Local
import Evergreen.V1.Melee.Projectile
import Evergreen.V1.Melee.Ranking
import Evergreen.V1.Melee.Rng
import Evergreen.V1.Melee.Room
import Evergreen.V1.Melee.Ship
import Evergreen.V1.Melee.ShipState
import Evergreen.V1.Melee.Units
import Evergreen.V1.OAuth
import Evergreen.V1.OAuth.AuthorizationCode
import Evergreen.V1.Types
import Evergreen.V2.Auth.Common
import Evergreen.V2.Logger
import Evergreen.V2.Melee.Battle
import Evergreen.V2.Melee.Element
import Evergreen.V2.Melee.Graphics
import Evergreen.V2.Melee.Id
import Evergreen.V2.Melee.Input
import Evergreen.V2.Melee.Local
import Evergreen.V2.Melee.Projectile
import Evergreen.V2.Melee.Ranking
import Evergreen.V2.Melee.Rng
import Evergreen.V2.Melee.Room
import Evergreen.V2.Melee.Ship
import Evergreen.V2.Melee.ShipState
import Evergreen.V2.Melee.Units
import Evergreen.V2.OAuth
import Evergreen.V2.OAuth.AuthorizationCode
import Evergreen.V2.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V2.Types.FrontendModel Evergreen.V2.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V2.Types.BackendModel Evergreen.V2.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V2.Types.FrontendMsg Evergreen.V2.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V2.Types.ToBackend Evergreen.V2.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V2.Types.BackendMsg Evergreen.V2.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V2.Types.ToFrontend Evergreen.V2.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V2.Types.BackendModel
migrate_Types_BackendModel old =
    { logState = old.logState |> migrate_Logger_LogState
    , pendingAuths = old.pendingAuths
    , sessions = old.sessions
    , users = old.users
    , emailPasswordCredentials = old.emailPasswordCredentials
    , pollingJobs = old.pollingJobs |> Dict.map (\k -> migrate_Types_PollingStatus identity)
    , melee = old.melee |> migrate_Melee_Room_Host
    }


migrate_Auth_Common_AuthChallengeReason : Evergreen.V1.Auth.Common.AuthChallengeReason -> Evergreen.V2.Auth.Common.AuthChallengeReason
migrate_Auth_Common_AuthChallengeReason old =
    case old of
        Evergreen.V1.Auth.Common.AuthSessionMissing ->
            Evergreen.V2.Auth.Common.AuthSessionMissing

        Evergreen.V1.Auth.Common.AuthSessionInvalid ->
            Evergreen.V2.Auth.Common.AuthSessionInvalid

        Evergreen.V1.Auth.Common.AuthSessionExpired ->
            Evergreen.V2.Auth.Common.AuthSessionExpired

        Evergreen.V1.Auth.Common.AuthSessionLoggedOut ->
            Evergreen.V2.Auth.Common.AuthSessionLoggedOut


migrate_Auth_Common_BackendMsg : Evergreen.V1.Auth.Common.BackendMsg -> Evergreen.V2.Auth.Common.BackendMsg
migrate_Auth_Common_BackendMsg old =
    case old of
        Evergreen.V1.Auth.Common.AuthSigninInitiated_ p0 ->
            Evergreen.V2.Auth.Common.AuthSigninInitiated_ p0

        Evergreen.V1.Auth.Common.AuthSigninInitiatedDelayed_ p0 p1 ->
            Evergreen.V2.Auth.Common.AuthSigninInitiatedDelayed_ p0 (p1 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V1.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V2.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6

        Evergreen.V1.Auth.Common.AuthSuccess p0 p1 p2 p3 p4 ->
            Evergreen.V2.Auth.Common.AuthSuccess p0
                p1
                p2
                p3
                (p4 |> Result.mapError migrate_Auth_Common_Error >> Result.map (Tuple.mapBoth migrate_Auth_Common_UserInfo (Maybe.map migrate_Auth_Common_Token)))

        Evergreen.V1.Auth.Common.AuthRenewSession p0 p1 ->
            Evergreen.V2.Auth.Common.AuthRenewSession p0 p1

        Evergreen.V1.Auth.Common.AuthLogout p0 p1 ->
            Evergreen.V2.Auth.Common.AuthLogout p0 p1


migrate_Auth_Common_Error : Evergreen.V1.Auth.Common.Error -> Evergreen.V2.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V1.Auth.Common.ErrStateMismatch ->
            Evergreen.V2.Auth.Common.ErrStateMismatch

        Evergreen.V1.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V2.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V1.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V2.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V1.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V2.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V1.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V2.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V1.Auth.Common.ErrAuthString p0 ->
            Evergreen.V2.Auth.Common.ErrAuthString p0


migrate_Auth_Common_ToFrontend : Evergreen.V1.Auth.Common.ToFrontend -> Evergreen.V2.Auth.Common.ToFrontend
migrate_Auth_Common_ToFrontend old =
    case old of
        Evergreen.V1.Auth.Common.AuthInitiateSignin p0 ->
            Evergreen.V2.Auth.Common.AuthInitiateSignin p0

        Evergreen.V1.Auth.Common.AuthError p0 ->
            Evergreen.V2.Auth.Common.AuthError (p0 |> migrate_Auth_Common_Error)

        Evergreen.V1.Auth.Common.AuthSessionChallenge p0 ->
            Evergreen.V2.Auth.Common.AuthSessionChallenge (p0 |> migrate_Auth_Common_AuthChallengeReason)


migrate_Auth_Common_Token : Evergreen.V1.Auth.Common.Token -> Evergreen.V2.Auth.Common.Token
migrate_Auth_Common_Token old =
    { methodId = old.methodId
    , token = old.token |> migrate_OAuth_Token
    , created = old.created
    , expires = old.expires
    }


migrate_Auth_Common_UserInfo : Evergreen.V1.Auth.Common.UserInfo -> Evergreen.V2.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Logger_LogEntry : Evergreen.V1.Logger.LogEntry -> Evergreen.V2.Logger.LogEntry
migrate_Logger_LogEntry old =
    { index = old.index
    , timestamp = old.timestamp
    , level = old.level |> migrate_Logger_LogLevel
    , message = old.message
    }


migrate_Logger_LogLevel : Evergreen.V1.Logger.LogLevel -> Evergreen.V2.Logger.LogLevel
migrate_Logger_LogLevel old =
    case old of
        Evergreen.V1.Logger.Debug ->
            Evergreen.V2.Logger.Debug

        Evergreen.V1.Logger.Info ->
            Evergreen.V2.Logger.Info

        Evergreen.V1.Logger.Warn ->
            Evergreen.V2.Logger.Warn

        Evergreen.V1.Logger.Error ->
            Evergreen.V2.Logger.Error


migrate_Logger_LogState : Evergreen.V1.Logger.LogState -> Evergreen.V2.Logger.LogState
migrate_Logger_LogState old =
    { entries = old.entries |> List.map migrate_Logger_LogEntry
    , nextIndex = old.nextIndex
    , maxEntries = old.maxEntries
    }


migrate_Logger_Msg : Evergreen.V1.Logger.Msg -> Evergreen.V2.Logger.Msg
migrate_Logger_Msg old =
    case old of
        Evergreen.V1.Logger.GotTimestamp p0 p1 ->
            Evergreen.V2.Logger.GotTimestamp p0 p1


migrate_Melee_Battle_Arena : Evergreen.V1.Melee.Battle.Arena -> Evergreen.V2.Melee.Battle.Arena
migrate_Melee_Battle_Arena old =
    { frame = old.frame |> migrate_Melee_Units_FrameCount
    , previousLocations = old.previousLocations
    , pumpAcc = old.pumpAcc
    , seed = old.seed |> migrate_Melee_Rng_Seed
    , space = old.space |> migrate_Melee_Units_WorldExtent
    , combatants = old.combatants |> migrate_Melee_Units_Sided migrate_Melee_ShipState_Combatant
    , elements = old.elements |> Dict.map (\k -> migrate_Melee_Element_Element)
    , queue = old.queue |> List.map migrate_Melee_Id_ElementId
    , nextElementId = old.nextElementId
    }


migrate_Melee_Element_Body : Evergreen.V1.Melee.Element.Body -> Evergreen.V2.Melee.Element.Body
migrate_Melee_Element_Body old =
    case old of
        Evergreen.V1.Melee.Element.ShipBody p0 ->
            Evergreen.V2.Melee.Element.ShipBody (p0 |> migrate_Melee_Units_Side)

        Evergreen.V1.Melee.Element.WreckBody p0 ->
            Evergreen.V2.Melee.Element.WreckBody (p0 |> migrate_Melee_Units_Side)

        Evergreen.V1.Melee.Element.PlanetBody ->
            Evergreen.V2.Melee.Element.PlanetBody

        Evergreen.V1.Melee.Element.AsteroidBody ->
            Evergreen.V2.Melee.Element.AsteroidBody

        Evergreen.V1.Melee.Element.CrewBody p0 ->
            Evergreen.V2.Melee.Element.CrewBody
                { origin = p0.origin |> migrate_Melee_Units_Side
                }

        Evergreen.V1.Melee.Element.WeaponImpact p0 ->
            Evergreen.V2.Melee.Element.WeaponImpact (p0 |> migrate_Melee_Projectile_MissileKind)

        Evergreen.V1.Melee.Element.BlastBody ->
            Evergreen.V2.Melee.Element.BlastBody

        Evergreen.V1.Melee.Element.ExplosionBody ->
            Evergreen.V2.Melee.Element.ExplosionBody

        Evergreen.V1.Melee.Element.WarpInBody ->
            Evergreen.V2.Melee.Element.WarpInBody

        Evergreen.V1.Melee.Element.IonTrailBody ->
            Evergreen.V2.Melee.Element.IonTrailBody

        Evergreen.V1.Melee.Element.AndrosynthBubble ->
            Evergreen.V2.Melee.Element.AndrosynthBubble

        Evergreen.V1.Melee.Element.ArilouLaser ->
            Evergreen.V2.Melee.Element.ArilouLaser

        Evergreen.V1.Melee.Element.ChenjesuPhoton ->
            Evergreen.V2.Melee.Element.ChenjesuPhoton

        Evergreen.V1.Melee.Element.ChenjesuFragment ->
            Evergreen.V2.Melee.Element.ChenjesuFragment

        Evergreen.V1.Melee.Element.ChenjesuDogi ->
            Evergreen.V2.Melee.Element.ChenjesuDogi

        Evergreen.V1.Melee.Element.ChmmrLaser ->
            Evergreen.V2.Melee.Element.ChmmrLaser

        Evergreen.V1.Melee.Element.ChmmrSatellite p0 ->
            Evergreen.V2.Melee.Element.ChmmrSatellite
                { orbitFacing = p0.orbitFacing |> migrate_Melee_Units_Facing
                }

        Evergreen.V1.Melee.Element.ChmmrZap ->
            Evergreen.V2.Melee.Element.ChmmrZap

        Evergreen.V1.Melee.Element.DruugeHotShot ->
            Evergreen.V2.Melee.Element.DruugeHotShot

        Evergreen.V1.Melee.Element.EarthlingNuke ->
            Evergreen.V2.Melee.Element.EarthlingNuke

        Evergreen.V1.Melee.Element.EarthlingPointDefense ->
            Evergreen.V2.Melee.Element.EarthlingPointDefense

        Evergreen.V1.Melee.Element.IlwrathFlame ->
            Evergreen.V2.Melee.Element.IlwrathFlame

        Evergreen.V1.Melee.Element.KohrAhSaw ->
            Evergreen.V2.Melee.Element.KohrAhSaw

        Evergreen.V1.Melee.Element.KohrAhFried ->
            Evergreen.V2.Melee.Element.KohrAhFried

        Evergreen.V1.Melee.Element.MelnormeCharge ->
            Evergreen.V2.Melee.Element.MelnormeCharge

        Evergreen.V1.Melee.Element.MelnormeConfusion ->
            Evergreen.V2.Melee.Element.MelnormeConfusion

        Evergreen.V1.Melee.Element.MmrnmhrmLaser ->
            Evergreen.V2.Melee.Element.MmrnmhrmLaser

        Evergreen.V1.Melee.Element.MmrnmhrmMissile ->
            Evergreen.V2.Melee.Element.MmrnmhrmMissile

        Evergreen.V1.Melee.Element.MyconPlasma ->
            Evergreen.V2.Melee.Element.MyconPlasma

        Evergreen.V1.Melee.Element.OrzHowitzer ->
            Evergreen.V2.Melee.Element.OrzHowitzer

        Evergreen.V1.Melee.Element.OrzMarine ->
            Evergreen.V2.Melee.Element.OrzMarine

        Evergreen.V1.Melee.Element.PkunkSpread ->
            Evergreen.V2.Melee.Element.PkunkSpread

        Evergreen.V1.Melee.Element.ShofixtiDart ->
            Evergreen.V2.Melee.Element.ShofixtiDart

        Evergreen.V1.Melee.Element.ShofixtiGlory ->
            Evergreen.V2.Melee.Element.ShofixtiGlory

        Evergreen.V1.Melee.Element.SlylandroLightning ->
            Evergreen.V2.Melee.Element.SlylandroLightning

        Evergreen.V1.Melee.Element.SpathiForward ->
            Evergreen.V2.Melee.Element.SpathiForward

        Evergreen.V1.Melee.Element.SpathiButt ->
            Evergreen.V2.Melee.Element.SpathiButt

        Evergreen.V1.Melee.Element.SupoxPellet ->
            Evergreen.V2.Melee.Element.SupoxPellet

        Evergreen.V1.Melee.Element.SyreenMissile ->
            Evergreen.V2.Melee.Element.SyreenMissile

        Evergreen.V1.Melee.Element.ThraddashBlaster ->
            Evergreen.V2.Melee.Element.ThraddashBlaster

        Evergreen.V1.Melee.Element.ThraddashAfterburn ->
            Evergreen.V2.Melee.Element.ThraddashAfterburn

        Evergreen.V1.Melee.Element.UmgahCone ->
            Evergreen.V2.Melee.Element.UmgahCone

        Evergreen.V1.Melee.Element.UrQuanFusion ->
            Evergreen.V2.Melee.Element.UrQuanFusion

        Evergreen.V1.Melee.Element.UrQuanFighter ->
            Evergreen.V2.Melee.Element.UrQuanFighter

        Evergreen.V1.Melee.Element.UrQuanFighterLaser ->
            Evergreen.V2.Melee.Element.UrQuanFighterLaser

        Evergreen.V1.Melee.Element.UtwigGizmo ->
            Evergreen.V2.Melee.Element.UtwigGizmo

        Evergreen.V1.Melee.Element.VuxLaser ->
            Evergreen.V2.Melee.Element.VuxLaser

        Evergreen.V1.Melee.Element.VuxLimpet ->
            Evergreen.V2.Melee.Element.VuxLimpet

        Evergreen.V1.Melee.Element.YehatMissile ->
            Evergreen.V2.Melee.Element.YehatMissile

        Evergreen.V1.Melee.Element.ZoqSpit ->
            Evergreen.V2.Melee.Element.ZoqSpit

        Evergreen.V1.Melee.Element.ZoqTongue ->
            Evergreen.V2.Melee.Element.ZoqTongue


migrate_Melee_Element_Element : Evergreen.V1.Melee.Element.Element -> Evergreen.V2.Melee.Element.Element
migrate_Melee_Element_Element old =
    { id = old.id |> migrate_Melee_Id_ElementId
    , owner = old.owner |> migrate_Melee_Element_Owner
    , parent = old.parent |> Maybe.map migrate_Melee_Units_Side
    , target = old.target |> Maybe.map migrate_Melee_Id_ElementId
    , flags = old.flags |> migrate_Melee_Element_ElementFlags
    , life = old.life |> migrate_Melee_Element_Life
    , points = old.points
    , mass = old.mass
    , turnWait = old.turnWait |> migrate_Melee_Units_Wait
    , thrustWait = old.thrustWait |> migrate_Melee_Units_Wait
    , colorCycleIndex = old.colorCycleIndex
    , velocity = old.velocity |> migrate_Melee_Units_VelocityDesc
    , intersect = old.intersect |> migrate_Melee_Element_IntersectControl
    , current = old.current |> migrate_Melee_Element_Image
    , next = old.next |> migrate_Melee_Element_Image
    , prim = old.prim |> migrate_Melee_Element_Prim
    , projectile = old.projectile |> Maybe.map migrate_Melee_Projectile_State
    , body = old.body |> migrate_Melee_Element_Body
    }


migrate_Melee_Element_ElementFlags : Evergreen.V1.Melee.Element.ElementFlags -> Evergreen.V2.Melee.Element.ElementFlags
migrate_Melee_Element_ElementFlags old =
    old


migrate_Melee_Element_Image : Evergreen.V1.Melee.Element.Image -> Evergreen.V2.Melee.Element.Image
migrate_Melee_Element_Image old =
    { location = old.location |> migrate_Melee_Units_WorldPoint
    , frameIndex = old.frameIndex
    }


migrate_Melee_Element_IntersectControl : Evergreen.V1.Melee.Element.IntersectControl -> Evergreen.V2.Melee.Element.IntersectControl
migrate_Melee_Element_IntersectControl old =
    { lastTimeVal = old.lastTimeVal
    , endPoint = old.endPoint |> migrate_Melee_Units_WorldPoint
    , stampOrigin = old.stampOrigin |> migrate_Melee_Units_WorldPoint
    }


migrate_Melee_Element_Life : Evergreen.V1.Melee.Element.Life -> Evergreen.V2.Melee.Element.Life
migrate_Melee_Element_Life old =
    case old of
        Evergreen.V1.Melee.Element.Persistent p0 ->
            Evergreen.V2.Melee.Element.Persistent p0

        Evergreen.V1.Melee.Element.Finite p0 ->
            Evergreen.V2.Melee.Element.Finite p0


migrate_Melee_Element_Owner : Evergreen.V1.Melee.Element.Owner -> Evergreen.V2.Melee.Element.Owner
migrate_Melee_Element_Owner old =
    case old of
        Evergreen.V1.Melee.Element.Neutral ->
            Evergreen.V2.Melee.Element.Neutral

        Evergreen.V1.Melee.Element.Owned p0 ->
            Evergreen.V2.Melee.Element.Owned (p0 |> migrate_Melee_Units_Side)


migrate_Melee_Element_Prim : Evergreen.V1.Melee.Element.Prim -> Evergreen.V2.Melee.Element.Prim
migrate_Melee_Element_Prim old =
    case old of
        Evergreen.V1.Melee.Element.NoPrim ->
            Evergreen.V2.Melee.Element.NoPrim

        Evergreen.V1.Melee.Element.Stamp ->
            Evergreen.V2.Melee.Element.Stamp

        Evergreen.V1.Melee.Element.StampFill p0 ->
            Evergreen.V2.Melee.Element.StampFill p0

        Evergreen.V1.Melee.Element.Line ->
            Evergreen.V2.Melee.Element.Line


migrate_Melee_Graphics_Quality : Evergreen.V1.Melee.Graphics.Quality -> Evergreen.V2.Melee.Graphics.Quality
migrate_Melee_Graphics_Quality old =
    case old of
        Evergreen.V1.Melee.Graphics.Classic ->
            Evergreen.V2.Melee.Graphics.Classic

        Evergreen.V1.Melee.Graphics.HighDefinition ->
            Evergreen.V2.Melee.Graphics.HighDefinition


migrate_Melee_Id_ElementId : Evergreen.V1.Melee.Id.ElementId -> Evergreen.V2.Melee.Id.ElementId
migrate_Melee_Id_ElementId old =
    case old of
        Evergreen.V1.Melee.Id.ElementId p0 ->
            Evergreen.V2.Melee.Id.ElementId p0


migrate_Melee_Input_BattleInput : Evergreen.V1.Melee.Input.BattleInput -> Evergreen.V2.Melee.Input.BattleInput
migrate_Melee_Input_BattleInput old =
    { turn = old.turn |> migrate_Melee_Input_Turn
    , thrust = old.thrust
    , weapon = old.weapon
    , special = old.special
    }


migrate_Melee_Input_CyborgRating : Evergreen.V1.Melee.Input.CyborgRating -> Evergreen.V2.Melee.Input.CyborgRating
migrate_Melee_Input_CyborgRating old =
    case old of
        Evergreen.V1.Melee.Input.StandardCyborg ->
            Evergreen.V2.Melee.Input.StandardCyborg

        Evergreen.V1.Melee.Input.GoodCyborg ->
            Evergreen.V2.Melee.Input.GoodCyborg

        Evergreen.V1.Melee.Input.AwesomeCyborg ->
            Evergreen.V2.Melee.Input.AwesomeCyborg


migrate_Melee_Input_Turn : Evergreen.V1.Melee.Input.Turn -> Evergreen.V2.Melee.Input.Turn
migrate_Melee_Input_Turn old =
    case old of
        Evergreen.V1.Melee.Input.NoTurn ->
            Evergreen.V2.Melee.Input.NoTurn

        Evergreen.V1.Melee.Input.TurnLeft ->
            Evergreen.V2.Melee.Input.TurnLeft

        Evergreen.V1.Melee.Input.TurnRight ->
            Evergreen.V2.Melee.Input.TurnRight


migrate_Melee_Local_Mode : Evergreen.V1.Melee.Local.Mode -> Evergreen.V2.Melee.Local.Mode
migrate_Melee_Local_Mode old =
    case old of
        Evergreen.V1.Melee.Local.Solo ->
            Evergreen.V2.Melee.Local.Solo

        Evergreen.V1.Melee.Local.Versus ->
            Evergreen.V2.Melee.Local.Versus

        Evergreen.V1.Melee.Local.Demo ->
            Evergreen.V2.Melee.Local.Demo

        Evergreen.V1.Melee.Local.ReverseSolo ->
            Evergreen.V2.Melee.Local.ReverseSolo


migrate_Melee_Local_Model : Evergreen.V1.Melee.Local.Model -> Evergreen.V2.Melee.Local.Model
migrate_Melee_Local_Model old =
    { names = old.names |> migrate_Melee_Units_Sided identity
    , notice = old.notice
    , difficulty = old.difficulty |> migrate_Melee_Input_CyborgRating
    , fleets = old.fleets |> migrate_Melee_Units_Sided (List.map migrate_Melee_Ship_ShipKind)
    , remaining = old.remaining |> migrate_Melee_Units_Sided (List.map migrate_Melee_Ship_ShipKind)
    , mode = old.mode |> migrate_Melee_Local_Mode
    , phase = old.phase |> migrate_Melee_Local_Phase
    , editing = old.editing |> migrate_Melee_Units_Side
    , seed = old.seed |> migrate_Melee_Rng_Seed
    , graphics = old.graphics |> migrate_Melee_Graphics_Quality
    , sound = old.sound
    , sounds = old.sounds
    , clock = old.clock
    , survivor = old.survivor |> Maybe.map migrate_Melee_Battle_Arena
    , zoomWidth = old.zoomWidth
    , presentationStep = old.presentationStep
    , presentationClock = old.presentationClock
    , round = old.round
    }


migrate_Melee_Local_Phase : Evergreen.V1.Melee.Local.Phase -> Evergreen.V2.Melee.Local.Phase
migrate_Melee_Local_Phase old =
    case old of
        Evergreen.V1.Melee.Local.Hangar ->
            Evergreen.V2.Melee.Local.Hangar

        Evergreen.V1.Melee.Local.Selecting p0 p1 ->
            Evergreen.V2.Melee.Local.Selecting (p0 |> Maybe.map migrate_Melee_Ship_ShipKind)
                (p1 |> Maybe.map migrate_Melee_Ship_ShipKind)

        Evergreen.V1.Melee.Local.Countdown p0 p1 ->
            Evergreen.V2.Melee.Local.Countdown p0 (p1 |> migrate_Melee_Battle_Arena)

        Evergreen.V1.Melee.Local.Combat p0 ->
            Evergreen.V2.Melee.Local.Combat (p0 |> migrate_Melee_Battle_Arena)

        Evergreen.V1.Melee.Local.Paused p0 ->
            Evergreen.V2.Melee.Local.Paused (p0 |> migrate_Melee_Battle_Arena)

        Evergreen.V1.Melee.Local.RoundOver p0 p1 ->
            Evergreen.V2.Melee.Local.RoundOver p0 (p1 |> migrate_Melee_Battle_Arena)

        Evergreen.V1.Melee.Local.Victory p0 ->
            Evergreen.V2.Melee.Local.Victory (p0 |> Maybe.map migrate_Melee_Units_Side)


migrate_Melee_Projectile_BeamKind : Evergreen.V1.Melee.Projectile.BeamKind -> Evergreen.V2.Melee.Projectile.BeamKind
migrate_Melee_Projectile_BeamKind old =
    case old of
        Evergreen.V1.Melee.Projectile.AutoAim ->
            Evergreen.V2.Melee.Projectile.AutoAim

        Evergreen.V1.Melee.Projectile.Megawatt ->
            Evergreen.V2.Melee.Projectile.Megawatt

        Evergreen.V1.Melee.Projectile.Twin ->
            Evergreen.V2.Melee.Projectile.Twin

        Evergreen.V1.Melee.Projectile.Green ->
            Evergreen.V2.Melee.Projectile.Green

        Evergreen.V1.Melee.Projectile.PointDefense ->
            Evergreen.V2.Melee.Projectile.PointDefense

        Evergreen.V1.Melee.Projectile.Zap ->
            Evergreen.V2.Melee.Projectile.Zap

        Evergreen.V1.Melee.Projectile.FighterBeam ->
            Evergreen.V2.Melee.Projectile.FighterBeam


migrate_Melee_Projectile_ContactKind : Evergreen.V1.Melee.Projectile.ContactKind -> Evergreen.V2.Melee.Projectile.ContactKind
migrate_Melee_Projectile_ContactKind old =
    case old of
        Evergreen.V1.Melee.Projectile.Cone ->
            Evergreen.V2.Melee.Projectile.Cone

        Evergreen.V1.Melee.Projectile.Tongue ->
            Evergreen.V2.Melee.Projectile.Tongue


migrate_Melee_Projectile_MissileKind : Evergreen.V1.Melee.Projectile.MissileKind -> Evergreen.V2.Melee.Projectile.MissileKind
migrate_Melee_Projectile_MissileKind old =
    case old of
        Evergreen.V1.Melee.Projectile.Bubble ->
            Evergreen.V2.Melee.Projectile.Bubble

        Evergreen.V1.Melee.Projectile.Crystal ->
            Evergreen.V2.Melee.Projectile.Crystal

        Evergreen.V1.Melee.Projectile.Shard ->
            Evergreen.V2.Melee.Projectile.Shard

        Evergreen.V1.Melee.Projectile.Dogi ->
            Evergreen.V2.Melee.Projectile.Dogi

        Evergreen.V1.Melee.Projectile.Cannon ->
            Evergreen.V2.Melee.Projectile.Cannon

        Evergreen.V1.Melee.Projectile.Nuke ->
            Evergreen.V2.Melee.Projectile.Nuke

        Evergreen.V1.Melee.Projectile.Flame ->
            Evergreen.V2.Melee.Projectile.Flame

        Evergreen.V1.Melee.Projectile.Saw ->
            Evergreen.V2.Melee.Projectile.Saw

        Evergreen.V1.Melee.Projectile.Fried ->
            Evergreen.V2.Melee.Projectile.Fried

        Evergreen.V1.Melee.Projectile.Charge ->
            Evergreen.V2.Melee.Projectile.Charge

        Evergreen.V1.Melee.Projectile.Confusion ->
            Evergreen.V2.Melee.Projectile.Confusion

        Evergreen.V1.Melee.Projectile.Torpedo ->
            Evergreen.V2.Melee.Projectile.Torpedo

        Evergreen.V1.Melee.Projectile.Plasma ->
            Evergreen.V2.Melee.Projectile.Plasma

        Evergreen.V1.Melee.Projectile.Howitzer ->
            Evergreen.V2.Melee.Projectile.Howitzer

        Evergreen.V1.Melee.Projectile.Marine ->
            Evergreen.V2.Melee.Projectile.Marine

        Evergreen.V1.Melee.Projectile.Bug ->
            Evergreen.V2.Melee.Projectile.Bug

        Evergreen.V1.Melee.Projectile.Dart ->
            Evergreen.V2.Melee.Projectile.Dart

        Evergreen.V1.Melee.Projectile.SpathiShot ->
            Evergreen.V2.Melee.Projectile.SpathiShot

        Evergreen.V1.Melee.Projectile.Butt ->
            Evergreen.V2.Melee.Projectile.Butt

        Evergreen.V1.Melee.Projectile.Pellet ->
            Evergreen.V2.Melee.Projectile.Pellet

        Evergreen.V1.Melee.Projectile.Dagger ->
            Evergreen.V2.Melee.Projectile.Dagger

        Evergreen.V1.Melee.Projectile.Blaster ->
            Evergreen.V2.Melee.Projectile.Blaster

        Evergreen.V1.Melee.Projectile.Napalm ->
            Evergreen.V2.Melee.Projectile.Napalm

        Evergreen.V1.Melee.Projectile.Fusion ->
            Evergreen.V2.Melee.Projectile.Fusion

        Evergreen.V1.Melee.Projectile.Fighter ->
            Evergreen.V2.Melee.Projectile.Fighter

        Evergreen.V1.Melee.Projectile.Lance ->
            Evergreen.V2.Melee.Projectile.Lance

        Evergreen.V1.Melee.Projectile.Limpet ->
            Evergreen.V2.Melee.Projectile.Limpet

        Evergreen.V1.Melee.Projectile.YehatShot ->
            Evergreen.V2.Melee.Projectile.YehatShot

        Evergreen.V1.Melee.Projectile.Spit ->
            Evergreen.V2.Melee.Projectile.Spit


migrate_Melee_Projectile_State : Evergreen.V1.Melee.Projectile.State -> Evergreen.V2.Melee.Projectile.State
migrate_Melee_Projectile_State old =
    case old of
        Evergreen.V1.Melee.Projectile.Flying p0 p1 ->
            Evergreen.V2.Melee.Projectile.Flying (p0 |> migrate_Melee_Projectile_MissileKind)
                { age = p1.age
                , facing = p1.facing |> migrate_Melee_Units_Facing
                , trackingWait = p1.trackingWait
                }

        Evergreen.V1.Melee.Projectile.Charging p0 ->
            Evergreen.V2.Melee.Projectile.Charging
                { ticks = p0.ticks
                , facing = p0.facing |> migrate_Melee_Units_Facing
                }

        Evergreen.V1.Melee.Projectile.Ray p0 p1 ->
            Evergreen.V2.Melee.Projectile.Ray (p0 |> migrate_Melee_Projectile_BeamKind)
                { origin = p1.origin |> migrate_Melee_Units_WorldPoint
                , end = p1.end |> migrate_Melee_Units_WorldPoint
                }

        Evergreen.V1.Melee.Projectile.Attached p0 p1 ->
            Evergreen.V2.Melee.Projectile.Attached (p0 |> migrate_Melee_Projectile_ContactKind)
                { age = p1.age
                , facing = p1.facing |> migrate_Melee_Units_Facing
                }

        Evergreen.V1.Melee.Projectile.LightningSegment p0 ->
            Evergreen.V2.Melee.Projectile.LightningSegment
                { origin = p0.origin |> migrate_Melee_Units_WorldPoint
                , end = p0.end |> migrate_Melee_Units_WorldPoint
                }


migrate_Melee_Ranking_Match : Evergreen.V1.Melee.Ranking.Match -> Evergreen.V2.Melee.Ranking.Match
migrate_Melee_Ranking_Match old =
    { players = old.players |> migrate_Melee_Units_Sided identity
    , ratings = old.ratings |> migrate_Melee_Units_Sided identity
    , deadline = old.deadline
    , started = old.started
    , away = old.away |> migrate_Melee_Units_Sided identity
    , outcome = old.outcome |> Maybe.map migrate_Melee_Ranking_Outcome
    }


migrate_Melee_Ranking_Outcome : Evergreen.V1.Melee.Ranking.Outcome -> Evergreen.V2.Melee.Ranking.Outcome
migrate_Melee_Ranking_Outcome old =
    case old of
        Evergreen.V1.Melee.Ranking.Cancelled ->
            Evergreen.V2.Melee.Ranking.Cancelled

        Evergreen.V1.Melee.Ranking.Scored p0 ->
            Evergreen.V2.Melee.Ranking.Scored
                { winner = p0.winner |> Maybe.map migrate_Melee_Units_Side
                , changes = p0.changes |> migrate_Melee_Units_Sided identity
                , ratings = p0.ratings |> migrate_Melee_Units_Sided identity
                }


migrate_Melee_Rng_Seed : Evergreen.V1.Melee.Rng.Seed -> Evergreen.V2.Melee.Rng.Seed
migrate_Melee_Rng_Seed old =
    case old of
        Evergreen.V1.Melee.Rng.Seed p0 ->
            Evergreen.V2.Melee.Rng.Seed p0


migrate_Melee_Room_Host : Evergreen.V1.Melee.Room.Host -> Evergreen.V2.Melee.Room.Host
migrate_Melee_Room_Host old =
    { rooms = old.rooms |> Dict.map (\k -> migrate_Melee_Room_Room)
    , roomSetups =
        old.rooms
            |> Dict.filter (\code room -> code /= "ARENA" && room.ranked == Nothing)
            |> Dict.map (\_ room -> { names = room.game.names, fleets = migrate_Melee_Units_Sided (List.map migrate_Melee_Ship_ShipKind) room.game.fleets, controllers = migrate_Melee_Units_Sided migrate_Melee_Room_SeatControl room.controllers })
    , clientRooms =
        old.rooms
            |> Dict.values
            |> List.concatMap (\room -> [ room.seats.bottom, room.seats.top ] |> List.filterMap (Maybe.andThen .client) |> List.map (\client -> ( client, room.code )))
            |> Dict.fromList
    , nextId = old.nextId
    , now = old.now
    , previewClients = old.previewClients
    , previewAt = old.previewAt
    , players = old.players
    , queue = old.queue
    }


migrate_Melee_Room_Room : Evergreen.V1.Melee.Room.Room -> Evergreen.V2.Melee.Room.Room
migrate_Melee_Room_Room old =
    { code = old.code
    , seats = old.seats |> migrate_Melee_Units_Sided identity
    , game = old.game |> migrate_Melee_Local_Model
    , inputs = old.inputs |> migrate_Melee_Units_Sided migrate_Melee_Input_BattleInput
    , controllers = old.controllers |> migrate_Melee_Units_Sided migrate_Melee_Room_SeatControl
    , ready = old.ready |> migrate_Melee_Units_Sided identity
    , revision = old.revision
    , lastBroadcast = old.lastBroadcast |> Maybe.map migrate_Melee_Local_Model
    , broadcastAt = old.broadcastAt
    , spectators = old.spectators
    , touched = old.touched
    , ranked = old.ranked |> Maybe.map migrate_Melee_Ranking_Match
    }


migrate_Melee_Room_SeatControl : Evergreen.V1.Melee.Room.SeatControl -> Evergreen.V2.Melee.Room.SeatControl
migrate_Melee_Room_SeatControl old =
    case old of
        Evergreen.V1.Melee.Room.Human ->
            Evergreen.V2.Melee.Room.Human

        Evergreen.V1.Melee.Room.Computer ->
            Evergreen.V2.Melee.Room.Computer


migrate_Melee_ShipState_AndrosynthExtra : Evergreen.V1.Melee.ShipState.AndrosynthExtra -> Evergreen.V2.Melee.ShipState.AndrosynthExtra
migrate_Melee_ShipState_AndrosynthExtra old =
    case old of
        Evergreen.V1.Melee.ShipState.Guardian ->
            Evergreen.V2.Melee.ShipState.Guardian

        Evergreen.V1.Melee.ShipState.Blazer p0 ->
            Evergreen.V2.Melee.ShipState.Blazer
                { guardian = p0.guardian |> migrate_Melee_Ship_Characteristics
                }


migrate_Melee_ShipState_ArilouExtra : Evergreen.V1.Melee.ShipState.ArilouExtra -> Evergreen.V2.Melee.ShipState.ArilouExtra
migrate_Melee_ShipState_ArilouExtra old =
    case old of
        Evergreen.V1.Melee.ShipState.Present ->
            Evergreen.V2.Melee.ShipState.Present

        Evergreen.V1.Melee.ShipState.Teleporting p0 ->
            Evergreen.V2.Melee.ShipState.Teleporting (p0 |> migrate_Melee_Units_Wait)


migrate_Melee_ShipState_ChmmrExtra : Evergreen.V1.Melee.ShipState.ChmmrExtra -> Evergreen.V2.Melee.ShipState.ChmmrExtra
migrate_Melee_ShipState_ChmmrExtra old =
    case old of
        Evergreen.V1.Melee.ShipState.TractorIdle ->
            Evergreen.V2.Melee.ShipState.TractorIdle

        Evergreen.V1.Melee.ShipState.TractorOn ->
            Evergreen.V2.Melee.ShipState.TractorOn


migrate_Melee_ShipState_Combatant : Evergreen.V1.Melee.ShipState.Combatant -> Evergreen.V2.Melee.ShipState.Combatant
migrate_Melee_ShipState_Combatant old =
    case old of
        Evergreen.V1.Melee.ShipState.LiveAndrosynth p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveAndrosynth (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_AndrosynthExtra)

        Evergreen.V1.Melee.ShipState.LiveArilou p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveArilou (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ArilouExtra)

        Evergreen.V1.Melee.ShipState.LiveChenjesu p0 ->
            Evergreen.V2.Melee.ShipState.LiveChenjesu (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveChmmr p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveChmmr (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ChmmrExtra)

        Evergreen.V1.Melee.ShipState.LiveDruuge p0 ->
            Evergreen.V2.Melee.ShipState.LiveDruuge (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveEarthling p0 ->
            Evergreen.V2.Melee.ShipState.LiveEarthling (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveIlwrath p0 ->
            Evergreen.V2.Melee.ShipState.LiveIlwrath (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveKohrAh p0 ->
            Evergreen.V2.Melee.ShipState.LiveKohrAh (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveMelnorme p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveMelnorme (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_MelnormeExtra)

        Evergreen.V1.Melee.ShipState.LiveMmrnmhrm p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveMmrnmhrm (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_MmrnmhrmExtra)

        Evergreen.V1.Melee.ShipState.LiveMycon p0 ->
            Evergreen.V2.Melee.ShipState.LiveMycon (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveOrz p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveOrz (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_OrzExtra)

        Evergreen.V1.Melee.ShipState.LivePkunk p0 p1 ->
            Evergreen.V2.Melee.ShipState.LivePkunk (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_PkunkExtra)

        Evergreen.V1.Melee.ShipState.LiveShofixti p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveShofixti (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ShofixtiExtra)

        Evergreen.V1.Melee.ShipState.LiveSlylandro p0 ->
            Evergreen.V2.Melee.ShipState.LiveSlylandro (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveSpathi p0 ->
            Evergreen.V2.Melee.ShipState.LiveSpathi (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveSupox p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveSupox (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_SupoxExtra)

        Evergreen.V1.Melee.ShipState.LiveSyreen p0 ->
            Evergreen.V2.Melee.ShipState.LiveSyreen (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveThraddash p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveThraddash (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ThraddashExtra)

        Evergreen.V1.Melee.ShipState.LiveUmgah p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveUmgah (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_UmgahExtra)

        Evergreen.V1.Melee.ShipState.LiveUrQuan p0 ->
            Evergreen.V2.Melee.ShipState.LiveUrQuan (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveUtwig p0 ->
            Evergreen.V2.Melee.ShipState.LiveUtwig (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveVux p0 p1 ->
            Evergreen.V2.Melee.ShipState.LiveVux (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_VuxExtra)

        Evergreen.V1.Melee.ShipState.LiveYehat p0 ->
            Evergreen.V2.Melee.ShipState.LiveYehat (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V1.Melee.ShipState.LiveZoqFotPik p0 ->
            Evergreen.V2.Melee.ShipState.LiveZoqFotPik (p0 |> migrate_Melee_ShipState_CombatantCore)


migrate_Melee_ShipState_CombatantCore : Evergreen.V1.Melee.ShipState.CombatantCore -> Evergreen.V2.Melee.ShipState.CombatantCore
migrate_Melee_ShipState_CombatantCore old =
    { element = old.element |> migrate_Melee_Id_ElementId
    , characteristics = old.characteristics |> migrate_Melee_Ship_Characteristics
    , energy = old.energy
    , maxEnergy = old.maxEnergy
    , maxCrew = old.maxCrew
    , weaponWait = old.weaponWait |> migrate_Melee_Units_Wait
    , specialWait = old.specialWait |> migrate_Melee_Units_Wait
    , energyWait = old.energyWait |> migrate_Melee_Units_Wait
    , facing = old.facing |> migrate_Melee_Units_Facing
    , input = old.input |> migrate_Melee_Input_BattleInput
    , shieldTicks = old.shieldTicks
    , confusedTicks = old.confusedTicks
    , chargeTicks = old.chargeTicks
    , cloaked = old.cloaked
    , oldInput = old.oldInput |> migrate_Melee_Input_BattleInput
    , flags = old.flags |> migrate_Melee_ShipState_MotionFlags
    }


migrate_Melee_ShipState_MelnormeExtra : Evergreen.V1.Melee.ShipState.MelnormeExtra -> Evergreen.V2.Melee.ShipState.MelnormeExtra
migrate_Melee_ShipState_MelnormeExtra old =
    { pump = old.pump |> migrate_Melee_ShipState_PumpLevel
    , levelCounter = old.levelCounter |> migrate_Melee_Units_Wait
    }


migrate_Melee_ShipState_MmrnmhrmExtra : Evergreen.V1.Melee.ShipState.MmrnmhrmExtra -> Evergreen.V2.Melee.ShipState.MmrnmhrmExtra
migrate_Melee_ShipState_MmrnmhrmExtra old =
    { form = old.form |> migrate_Melee_ShipState_MmrnmhrmForm
    , otherWing = old.otherWing |> migrate_Melee_Ship_Characteristics
    }


migrate_Melee_ShipState_MmrnmhrmForm : Evergreen.V1.Melee.ShipState.MmrnmhrmForm -> Evergreen.V2.Melee.ShipState.MmrnmhrmForm
migrate_Melee_ShipState_MmrnmhrmForm old =
    case old of
        Evergreen.V1.Melee.ShipState.XWing ->
            Evergreen.V2.Melee.ShipState.XWing

        Evergreen.V1.Melee.ShipState.YWing ->
            Evergreen.V2.Melee.ShipState.YWing


migrate_Melee_ShipState_MotionFlags : Evergreen.V1.Melee.ShipState.MotionFlags -> Evergreen.V2.Melee.ShipState.MotionFlags
migrate_Melee_ShipState_MotionFlags old =
    old


migrate_Melee_ShipState_OrzExtra : Evergreen.V1.Melee.ShipState.OrzExtra -> Evergreen.V2.Melee.ShipState.OrzExtra
migrate_Melee_ShipState_OrzExtra old =
    { turretFacing = old.turretFacing |> migrate_Melee_Units_Facing
    , turretWait = old.turretWait |> migrate_Melee_Units_Wait
    }


migrate_Melee_ShipState_PkunkExtra : Evergreen.V1.Melee.ShipState.PkunkExtra -> Evergreen.V2.Melee.ShipState.PkunkExtra
migrate_Melee_ShipState_PkunkExtra old =
    case old of
        Evergreen.V1.Melee.ShipState.Flying ->
            Evergreen.V2.Melee.ShipState.Flying

        Evergreen.V1.Melee.ShipState.Phoenix p0 ->
            Evergreen.V2.Melee.ShipState.Phoenix (p0 |> migrate_Melee_Id_ElementId)


migrate_Melee_ShipState_PumpLevel : Evergreen.V1.Melee.ShipState.PumpLevel -> Evergreen.V2.Melee.ShipState.PumpLevel
migrate_Melee_ShipState_PumpLevel old =
    case old of
        Evergreen.V1.Melee.ShipState.Pump1 ->
            Evergreen.V2.Melee.ShipState.Pump1

        Evergreen.V1.Melee.ShipState.Pump2 ->
            Evergreen.V2.Melee.ShipState.Pump2

        Evergreen.V1.Melee.ShipState.Pump3 ->
            Evergreen.V2.Melee.ShipState.Pump3

        Evergreen.V1.Melee.ShipState.Pump4 ->
            Evergreen.V2.Melee.ShipState.Pump4


migrate_Melee_ShipState_ShofixtiExtra : Evergreen.V1.Melee.ShipState.ShofixtiExtra -> Evergreen.V2.Melee.ShipState.ShofixtiExtra
migrate_Melee_ShipState_ShofixtiExtra old =
    case old of
        Evergreen.V1.Melee.ShipState.SafetyClosed ->
            Evergreen.V2.Melee.ShipState.SafetyClosed

        Evergreen.V1.Melee.ShipState.OpeningSafety ->
            Evergreen.V2.Melee.ShipState.OpeningSafety

        Evergreen.V1.Melee.ShipState.SafetyOpen ->
            Evergreen.V2.Melee.ShipState.SafetyOpen

        Evergreen.V1.Melee.ShipState.ArmingDevice ->
            Evergreen.V2.Melee.ShipState.ArmingDevice

        Evergreen.V1.Melee.ShipState.Armed ->
            Evergreen.V2.Melee.ShipState.Armed

        Evergreen.V1.Melee.ShipState.GloryDevice ->
            Evergreen.V2.Melee.ShipState.GloryDevice


migrate_Melee_ShipState_SupoxExtra : Evergreen.V1.Melee.ShipState.SupoxExtra -> Evergreen.V2.Melee.ShipState.SupoxExtra
migrate_Melee_ShipState_SupoxExtra old =
    case old of
        Evergreen.V1.Melee.ShipState.ForwardOnly ->
            Evergreen.V2.Melee.ShipState.ForwardOnly

        Evergreen.V1.Melee.ShipState.Strafing p0 ->
            Evergreen.V2.Melee.ShipState.Strafing (p0 |> migrate_Melee_Input_Turn)


migrate_Melee_ShipState_ThraddashExtra : Evergreen.V1.Melee.ShipState.ThraddashExtra -> Evergreen.V2.Melee.ShipState.ThraddashExtra
migrate_Melee_ShipState_ThraddashExtra old =
    case old of
        Evergreen.V1.Melee.ShipState.Cruise ->
            Evergreen.V2.Melee.ShipState.Cruise

        Evergreen.V1.Melee.ShipState.Afterburning p0 ->
            Evergreen.V2.Melee.ShipState.Afterburning p0


migrate_Melee_ShipState_UmgahExtra : Evergreen.V1.Melee.ShipState.UmgahExtra -> Evergreen.V2.Melee.ShipState.UmgahExtra
migrate_Melee_ShipState_UmgahExtra old =
    { prevFacing = old.prevFacing |> migrate_Melee_Units_Facing
    }


migrate_Melee_ShipState_VuxExtra : Evergreen.V1.Melee.ShipState.VuxExtra -> Evergreen.V2.Melee.ShipState.VuxExtra
migrate_Melee_ShipState_VuxExtra old =
    case old of
        Evergreen.V1.Melee.ShipState.WarpPending ->
            Evergreen.V2.Melee.ShipState.WarpPending

        Evergreen.V1.Melee.ShipState.OnField ->
            Evergreen.V2.Melee.ShipState.OnField


migrate_Melee_Ship_Characteristics : Evergreen.V1.Melee.Ship.Characteristics -> Evergreen.V2.Melee.Ship.Characteristics
migrate_Melee_Ship_Characteristics old =
    { maxThrust = old.maxThrust
    , thrustIncrement = old.thrustIncrement
    , energyRegeneration = old.energyRegeneration
    , weaponEnergyCost = old.weaponEnergyCost
    , specialEnergyCost = old.specialEnergyCost
    , energyWait = old.energyWait |> migrate_Melee_Units_Wait
    , turnWait = old.turnWait |> migrate_Melee_Units_Wait
    , thrustWait = old.thrustWait |> migrate_Melee_Units_Wait
    , weaponWait = old.weaponWait |> migrate_Melee_Units_Wait
    , specialWait = old.specialWait |> migrate_Melee_Units_Wait
    , shipMass = old.shipMass
    }


migrate_Melee_Ship_ShipKind : Evergreen.V1.Melee.Ship.ShipKind -> Evergreen.V2.Melee.Ship.ShipKind
migrate_Melee_Ship_ShipKind old =
    case old of
        Evergreen.V1.Melee.Ship.Androsynth ->
            Evergreen.V2.Melee.Ship.Androsynth

        Evergreen.V1.Melee.Ship.Arilou ->
            Evergreen.V2.Melee.Ship.Arilou

        Evergreen.V1.Melee.Ship.Chenjesu ->
            Evergreen.V2.Melee.Ship.Chenjesu

        Evergreen.V1.Melee.Ship.Chmmr ->
            Evergreen.V2.Melee.Ship.Chmmr

        Evergreen.V1.Melee.Ship.Druuge ->
            Evergreen.V2.Melee.Ship.Druuge

        Evergreen.V1.Melee.Ship.Earthling ->
            Evergreen.V2.Melee.Ship.Earthling

        Evergreen.V1.Melee.Ship.Ilwrath ->
            Evergreen.V2.Melee.Ship.Ilwrath

        Evergreen.V1.Melee.Ship.KohrAh ->
            Evergreen.V2.Melee.Ship.KohrAh

        Evergreen.V1.Melee.Ship.Melnorme ->
            Evergreen.V2.Melee.Ship.Melnorme

        Evergreen.V1.Melee.Ship.Mmrnmhrm ->
            Evergreen.V2.Melee.Ship.Mmrnmhrm

        Evergreen.V1.Melee.Ship.Mycon ->
            Evergreen.V2.Melee.Ship.Mycon

        Evergreen.V1.Melee.Ship.Orz ->
            Evergreen.V2.Melee.Ship.Orz

        Evergreen.V1.Melee.Ship.Pkunk ->
            Evergreen.V2.Melee.Ship.Pkunk

        Evergreen.V1.Melee.Ship.Shofixti ->
            Evergreen.V2.Melee.Ship.Shofixti

        Evergreen.V1.Melee.Ship.Slylandro ->
            Evergreen.V2.Melee.Ship.Slylandro

        Evergreen.V1.Melee.Ship.Spathi ->
            Evergreen.V2.Melee.Ship.Spathi

        Evergreen.V1.Melee.Ship.Supox ->
            Evergreen.V2.Melee.Ship.Supox

        Evergreen.V1.Melee.Ship.Syreen ->
            Evergreen.V2.Melee.Ship.Syreen

        Evergreen.V1.Melee.Ship.Thraddash ->
            Evergreen.V2.Melee.Ship.Thraddash

        Evergreen.V1.Melee.Ship.Umgah ->
            Evergreen.V2.Melee.Ship.Umgah

        Evergreen.V1.Melee.Ship.UrQuan ->
            Evergreen.V2.Melee.Ship.UrQuan

        Evergreen.V1.Melee.Ship.Utwig ->
            Evergreen.V2.Melee.Ship.Utwig

        Evergreen.V1.Melee.Ship.Vux ->
            Evergreen.V2.Melee.Ship.Vux

        Evergreen.V1.Melee.Ship.Yehat ->
            Evergreen.V2.Melee.Ship.Yehat

        Evergreen.V1.Melee.Ship.ZoqFotPik ->
            Evergreen.V2.Melee.Ship.ZoqFotPik


migrate_Melee_Units_Angle : Evergreen.V1.Melee.Units.Angle -> Evergreen.V2.Melee.Units.Angle
migrate_Melee_Units_Angle old =
    case old of
        Evergreen.V1.Melee.Units.Angle p0 ->
            Evergreen.V2.Melee.Units.Angle p0


migrate_Melee_Units_Facing : Evergreen.V1.Melee.Units.Facing -> Evergreen.V2.Melee.Units.Facing
migrate_Melee_Units_Facing old =
    case old of
        Evergreen.V1.Melee.Units.Facing p0 ->
            Evergreen.V2.Melee.Units.Facing p0


migrate_Melee_Units_FrameCount : Evergreen.V1.Melee.Units.FrameCount -> Evergreen.V2.Melee.Units.FrameCount
migrate_Melee_Units_FrameCount old =
    case old of
        Evergreen.V1.Melee.Units.FrameCount p0 ->
            Evergreen.V2.Melee.Units.FrameCount p0


migrate_Melee_Units_Side : Evergreen.V1.Melee.Units.Side -> Evergreen.V2.Melee.Units.Side
migrate_Melee_Units_Side old =
    case old of
        Evergreen.V1.Melee.Units.Bottom ->
            Evergreen.V2.Melee.Units.Bottom

        Evergreen.V1.Melee.Units.Top ->
            Evergreen.V2.Melee.Units.Top


migrate_Melee_Units_Sided : (a_old -> a_new) -> Evergreen.V1.Melee.Units.Sided a_old -> Evergreen.V2.Melee.Units.Sided a_new
migrate_Melee_Units_Sided migrate_a old =
    { bottom = old.bottom |> migrate_a
    , top = old.top |> migrate_a
    }


migrate_Melee_Units_VelocityDesc : Evergreen.V1.Melee.Units.VelocityDesc -> Evergreen.V2.Melee.Units.VelocityDesc
migrate_Melee_Units_VelocityDesc old =
    { travelAngle = old.travelAngle |> migrate_Melee_Units_Angle
    , vector = old.vector |> migrate_Melee_Units_WorldExtent
    , fract = old.fract |> migrate_Melee_Units_WorldExtent
    , error = old.error |> migrate_Melee_Units_WorldExtent
    , incr = old.incr |> migrate_Melee_Units_WorldExtent
    }


migrate_Melee_Units_Wait : Evergreen.V1.Melee.Units.Wait -> Evergreen.V2.Melee.Units.Wait
migrate_Melee_Units_Wait old =
    case old of
        Evergreen.V1.Melee.Units.Wait p0 ->
            Evergreen.V2.Melee.Units.Wait p0


migrate_Melee_Units_WorldExtent : Evergreen.V1.Melee.Units.WorldExtent -> Evergreen.V2.Melee.Units.WorldExtent
migrate_Melee_Units_WorldExtent old =
    old


migrate_Melee_Units_WorldPoint : Evergreen.V1.Melee.Units.WorldPoint -> Evergreen.V2.Melee.Units.WorldPoint
migrate_Melee_Units_WorldPoint old =
    old


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V1.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V2.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V1.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V2.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V1.OAuth.ErrorCode -> Evergreen.V2.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V1.OAuth.InvalidRequest ->
            Evergreen.V2.OAuth.InvalidRequest

        Evergreen.V1.OAuth.UnauthorizedClient ->
            Evergreen.V2.OAuth.UnauthorizedClient

        Evergreen.V1.OAuth.AccessDenied ->
            Evergreen.V2.OAuth.AccessDenied

        Evergreen.V1.OAuth.UnsupportedResponseType ->
            Evergreen.V2.OAuth.UnsupportedResponseType

        Evergreen.V1.OAuth.InvalidScope ->
            Evergreen.V2.OAuth.InvalidScope

        Evergreen.V1.OAuth.ServerError ->
            Evergreen.V2.OAuth.ServerError

        Evergreen.V1.OAuth.TemporarilyUnavailable ->
            Evergreen.V2.OAuth.TemporarilyUnavailable

        Evergreen.V1.OAuth.Custom p0 ->
            Evergreen.V2.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V1.OAuth.Token -> Evergreen.V2.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V1.OAuth.Bearer p0 ->
            Evergreen.V2.OAuth.Bearer p0


migrate_Types_BackendMsg : Evergreen.V1.Types.BackendMsg -> Evergreen.V2.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V1.Types.NoOpBackendMsg ->
            Evergreen.V2.Types.NoOpBackendMsg

        Evergreen.V1.Types.MeleeTick p0 ->
            Evergreen.V2.Types.MeleeTick p0

        Evergreen.V1.Types.MeleeConnected p0 p1 ->
            Evergreen.V2.Types.MeleeConnected p0 p1

        Evergreen.V1.Types.MeleeDisconnected p0 p1 ->
            Evergreen.V2.Types.MeleeDisconnected p0 p1

        Evergreen.V1.Types.GotLogTime p0 ->
            Evergreen.V2.Types.GotLogTime (p0 |> migrate_Logger_Msg)

        Evergreen.V1.Types.GotRemoteModel p0 ->
            Evergreen.V2.Types.GotRemoteModel (p0 |> Result.map migrate_Types_BackendModel)

        Evergreen.V1.Types.AuthBackendMsg p0 ->
            Evergreen.V2.Types.AuthBackendMsg (p0 |> migrate_Auth_Common_BackendMsg)

        Evergreen.V1.Types.EmailPasswordAuthResult p0 ->
            Evergreen.V2.Types.EmailPasswordAuthResult (p0 |> migrate_Types_EmailPasswordAuthResult)

        Evergreen.V1.Types.GotJobTime p0 p1 ->
            Evergreen.V2.Types.GotJobTime p0 p1

        Evergreen.V1.Types.GotCryptoPriceResult p0 p1 ->
            Evergreen.V2.Types.GotCryptoPriceResult p0 p1

        Evergreen.V1.Types.StoreTaskResult p0 p1 ->
            Evergreen.V2.Types.StoreTaskResult p0 p1


migrate_Types_EmailPasswordAuthResult : Evergreen.V1.Types.EmailPasswordAuthResult -> Evergreen.V2.Types.EmailPasswordAuthResult
migrate_Types_EmailPasswordAuthResult old =
    case old of
        Evergreen.V1.Types.EmailPasswordSignupWithHash p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V2.Types.EmailPasswordSignupWithHash p0 p1 p2 p3 p4 p5 p6


migrate_Types_PollingStatus : (a_old -> a_new) -> Evergreen.V1.Types.PollingStatus a_old -> Evergreen.V2.Types.PollingStatus a_new
migrate_Types_PollingStatus migrate_a old =
    case old of
        Evergreen.V1.Types.Busy ->
            Evergreen.V2.Types.Busy

        Evergreen.V1.Types.BusyWithTime p0 ->
            Evergreen.V2.Types.BusyWithTime p0

        Evergreen.V1.Types.Ready p0 ->
            Evergreen.V2.Types.Ready (p0 |> Result.map migrate_a)
