module Evergreen.Migrate.V5 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V4.Auth.Common
import Evergreen.V4.Logger
import Evergreen.V4.Melee.Battle
import Evergreen.V4.Melee.Element
import Evergreen.V4.Melee.Graphics
import Evergreen.V4.Melee.Id
import Evergreen.V4.Melee.Input
import Evergreen.V4.Melee.Keys
import Evergreen.V4.Melee.Local
import Evergreen.V4.Melee.Location
import Evergreen.V4.Melee.Menu
import Evergreen.V4.Melee.Preview
import Evergreen.V4.Melee.Projectile
import Evergreen.V4.Melee.Ranking
import Evergreen.V4.Melee.Rng
import Evergreen.V4.Melee.Room
import Evergreen.V4.Melee.Ship
import Evergreen.V4.Melee.ShipState
import Evergreen.V4.Melee.Stream
import Evergreen.V4.Melee.Units
import Evergreen.V4.OAuth
import Evergreen.V4.OAuth.AuthorizationCode
import Evergreen.V4.Types
import Evergreen.V5.Auth.Common
import Evergreen.V5.Logger
import Evergreen.V5.Melee.Battle
import Evergreen.V5.Melee.Element
import Evergreen.V5.Melee.Graphics
import Evergreen.V5.Melee.Id
import Evergreen.V5.Melee.Input
import Evergreen.V5.Melee.Keys
import Evergreen.V5.Melee.Local
import Evergreen.V5.Melee.Location
import Evergreen.V5.Melee.Menu
import Evergreen.V5.Melee.Preview
import Evergreen.V5.Melee.Projectile
import Evergreen.V5.Melee.Ranking
import Evergreen.V5.Melee.Rng
import Evergreen.V5.Melee.Room
import Evergreen.V5.Melee.Ship
import Evergreen.V5.Melee.ShipState
import Evergreen.V5.Melee.Stream
import Evergreen.V5.Melee.Units
import Evergreen.V5.OAuth
import Evergreen.V5.OAuth.AuthorizationCode
import Evergreen.V5.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V4.Types.FrontendModel -> ModelMigration Evergreen.V5.Types.FrontendModel Evergreen.V5.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V4.Types.BackendModel -> ModelMigration Evergreen.V5.Types.BackendModel Evergreen.V5.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V4.Types.FrontendMsg -> MsgMigration Evergreen.V5.Types.FrontendMsg Evergreen.V5.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V4.Types.ToBackend -> MsgMigration Evergreen.V5.Types.ToBackend Evergreen.V5.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V4.Types.BackendMsg -> MsgMigration Evergreen.V5.Types.BackendMsg Evergreen.V5.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V4.Types.ToFrontend -> MsgMigration Evergreen.V5.Types.ToFrontend Evergreen.V5.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V4.Types.BackendModel -> Evergreen.V5.Types.BackendModel
migrate_Types_BackendModel old =
    { logState = old.logState |> migrate_Logger_LogState
    , pendingAuths = old.pendingAuths
    , sessions = old.sessions
    , users = old.users
    , emailPasswordCredentials = old.emailPasswordCredentials
    , pollingJobs = old.pollingJobs |> Dict.map (\k -> migrate_Types_PollingStatus identity)
    , counters = { ticks = 0, inputs = 0, deliveries = 0, probes = 0 }
    , workload = { counters = { ticks = 0, inputs = 0, deliveries = 0, probes = 0 }, rooms = Dict.size old.melee.rooms, battles = 0, spectators = 0, viewers = Dict.size old.melee.previewClients, queued = List.length old.melee.queue, saved = Dict.size old.melee.roomSetups }
    , melee = old.melee |> migrate_Melee_Room_Host
    }


migrate_Types_FrontendModel : Evergreen.V4.Types.FrontendModel -> Evergreen.V5.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentRoute = old.currentRoute |> migrate_Types_Route
    , adminPage = old.adminPage |> migrate_Types_AdminPageModel
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    , login = old.login |> migrate_Types_LoginState
    , currentUser = old.currentUser
    , pendingAuth = old.pendingAuth
    , preferences = old.preferences |> migrate_Types_Preferences
    , emailPasswordForm = old.emailPasswordForm |> migrate_Types_EmailPasswordFormModel
    , profileDropdownOpen = old.profileDropdownOpen
    , loginModalOpen = old.loginModalOpen
    , melee = old.melee |> migrate_Melee_Room_Client
    , player = old.player
    , playerName = old.playerName
    , searching = old.searching
    , meleeVisible = old.meleeVisible
    , telemetry = { elapsed = 0, frames = 0, fps = Nothing, frameMs = Nothing, serial = 0, pending = Nothing, age = 5, rtt = Nothing, sample = Nothing, previous = Nothing, rates = Nothing }
    , telemetryReply = Nothing
    , meleeNow = old.meleeNow
    , creatingRoom = old.creatingRoom
    , location = old.location |> migrate_Melee_Location_Location
    , arenaPreview = old.arenaPreview |> Maybe.map migrate_Melee_Local_Model
    , showLocalGame = old.showLocalGame
    , watchableGames = old.watchableGames
    , availableRooms = old.availableRooms |> Maybe.map (List.map migrate_Melee_Room_Listing)
    , roomCode = old.roomCode
    , meleeHeld = old.meleeHeld
    , game = old.game |> migrate_Melee_Local_Model
    }


migrate_Auth_Common_AuthChallengeReason : Evergreen.V4.Auth.Common.AuthChallengeReason -> Evergreen.V5.Auth.Common.AuthChallengeReason
migrate_Auth_Common_AuthChallengeReason old =
    case old of
        Evergreen.V4.Auth.Common.AuthSessionMissing ->
            Evergreen.V5.Auth.Common.AuthSessionMissing

        Evergreen.V4.Auth.Common.AuthSessionInvalid ->
            Evergreen.V5.Auth.Common.AuthSessionInvalid

        Evergreen.V4.Auth.Common.AuthSessionExpired ->
            Evergreen.V5.Auth.Common.AuthSessionExpired

        Evergreen.V4.Auth.Common.AuthSessionLoggedOut ->
            Evergreen.V5.Auth.Common.AuthSessionLoggedOut


migrate_Auth_Common_BackendMsg : Evergreen.V4.Auth.Common.BackendMsg -> Evergreen.V5.Auth.Common.BackendMsg
migrate_Auth_Common_BackendMsg old =
    case old of
        Evergreen.V4.Auth.Common.AuthSigninInitiated_ p0 ->
            Evergreen.V5.Auth.Common.AuthSigninInitiated_ p0

        Evergreen.V4.Auth.Common.AuthSigninInitiatedDelayed_ p0 p1 ->
            Evergreen.V5.Auth.Common.AuthSigninInitiatedDelayed_ p0 (p1 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V4.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V5.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6

        Evergreen.V4.Auth.Common.AuthSuccess p0 p1 p2 p3 p4 ->
            Evergreen.V5.Auth.Common.AuthSuccess p0
                p1
                p2
                p3
                (p4 |> Result.mapError migrate_Auth_Common_Error >> Result.map (Tuple.mapBoth migrate_Auth_Common_UserInfo (Maybe.map migrate_Auth_Common_Token)))

        Evergreen.V4.Auth.Common.AuthRenewSession p0 p1 ->
            Evergreen.V5.Auth.Common.AuthRenewSession p0 p1

        Evergreen.V4.Auth.Common.AuthLogout p0 p1 ->
            Evergreen.V5.Auth.Common.AuthLogout p0 p1


migrate_Auth_Common_Error : Evergreen.V4.Auth.Common.Error -> Evergreen.V5.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V4.Auth.Common.ErrStateMismatch ->
            Evergreen.V5.Auth.Common.ErrStateMismatch

        Evergreen.V4.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V5.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V4.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V5.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V4.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V5.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V4.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V5.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V4.Auth.Common.ErrAuthString p0 ->
            Evergreen.V5.Auth.Common.ErrAuthString p0


migrate_Auth_Common_Flow : Evergreen.V4.Auth.Common.Flow -> Evergreen.V5.Auth.Common.Flow
migrate_Auth_Common_Flow old =
    case old of
        Evergreen.V4.Auth.Common.Idle ->
            Evergreen.V5.Auth.Common.Idle

        Evergreen.V4.Auth.Common.Requested p0 ->
            Evergreen.V5.Auth.Common.Requested p0

        Evergreen.V4.Auth.Common.Pending ->
            Evergreen.V5.Auth.Common.Pending

        Evergreen.V4.Auth.Common.Authorized p0 p1 ->
            Evergreen.V5.Auth.Common.Authorized p0 p1

        Evergreen.V4.Auth.Common.Authenticated p0 ->
            Evergreen.V5.Auth.Common.Authenticated (p0 |> migrate_OAuth_Token)

        Evergreen.V4.Auth.Common.Done p0 ->
            Evergreen.V5.Auth.Common.Done (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V4.Auth.Common.Errored p0 ->
            Evergreen.V5.Auth.Common.Errored (p0 |> migrate_Auth_Common_Error)


migrate_Auth_Common_ToBackend : Evergreen.V4.Auth.Common.ToBackend -> Evergreen.V5.Auth.Common.ToBackend
migrate_Auth_Common_ToBackend old =
    case old of
        Evergreen.V4.Auth.Common.AuthSigninInitiated p0 ->
            Evergreen.V5.Auth.Common.AuthSigninInitiated p0

        Evergreen.V4.Auth.Common.AuthCallbackReceived p0 p1 p2 p3 ->
            Evergreen.V5.Auth.Common.AuthCallbackReceived p0 p1 p2 p3

        Evergreen.V4.Auth.Common.AuthRenewSessionRequested ->
            Evergreen.V5.Auth.Common.AuthRenewSessionRequested

        Evergreen.V4.Auth.Common.AuthLogoutRequested ->
            Evergreen.V5.Auth.Common.AuthLogoutRequested


migrate_Auth_Common_ToFrontend : Evergreen.V4.Auth.Common.ToFrontend -> Evergreen.V5.Auth.Common.ToFrontend
migrate_Auth_Common_ToFrontend old =
    case old of
        Evergreen.V4.Auth.Common.AuthInitiateSignin p0 ->
            Evergreen.V5.Auth.Common.AuthInitiateSignin p0

        Evergreen.V4.Auth.Common.AuthError p0 ->
            Evergreen.V5.Auth.Common.AuthError (p0 |> migrate_Auth_Common_Error)

        Evergreen.V4.Auth.Common.AuthSessionChallenge p0 ->
            Evergreen.V5.Auth.Common.AuthSessionChallenge (p0 |> migrate_Auth_Common_AuthChallengeReason)


migrate_Auth_Common_Token : Evergreen.V4.Auth.Common.Token -> Evergreen.V5.Auth.Common.Token
migrate_Auth_Common_Token old =
    { methodId = old.methodId
    , token = old.token |> migrate_OAuth_Token
    , created = old.created
    , expires = old.expires
    }


migrate_Auth_Common_UserInfo : Evergreen.V4.Auth.Common.UserInfo -> Evergreen.V5.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Logger_LogEntry : Evergreen.V4.Logger.LogEntry -> Evergreen.V5.Logger.LogEntry
migrate_Logger_LogEntry old =
    { index = old.index
    , timestamp = old.timestamp
    , level = old.level |> migrate_Logger_LogLevel
    , message = old.message
    }


migrate_Logger_LogLevel : Evergreen.V4.Logger.LogLevel -> Evergreen.V5.Logger.LogLevel
migrate_Logger_LogLevel old =
    case old of
        Evergreen.V4.Logger.Debug ->
            Evergreen.V5.Logger.Debug

        Evergreen.V4.Logger.Info ->
            Evergreen.V5.Logger.Info

        Evergreen.V4.Logger.Warn ->
            Evergreen.V5.Logger.Warn

        Evergreen.V4.Logger.Error ->
            Evergreen.V5.Logger.Error


migrate_Logger_LogState : Evergreen.V4.Logger.LogState -> Evergreen.V5.Logger.LogState
migrate_Logger_LogState old =
    { entries = old.entries |> List.map migrate_Logger_LogEntry
    , nextIndex = old.nextIndex
    , maxEntries = old.maxEntries
    }


migrate_Logger_Msg : Evergreen.V4.Logger.Msg -> Evergreen.V5.Logger.Msg
migrate_Logger_Msg old =
    case old of
        Evergreen.V4.Logger.GotTimestamp p0 p1 ->
            Evergreen.V5.Logger.GotTimestamp p0 p1


migrate_Melee_Battle_Arena : Evergreen.V4.Melee.Battle.Arena -> Evergreen.V5.Melee.Battle.Arena
migrate_Melee_Battle_Arena old =
    { frame = old.frame |> migrate_Melee_Units_FrameCount
    , previousLocations = old.previousLocations
    , pumpAcc = old.pumpAcc
    , seed = old.seed |> migrate_Melee_Rng_Seed
    , space = old.space |> migrate_Melee_Units_WorldExtent
    , combatants = old.combatants |> migrate_Melee_Units_Sided migrate_Melee_ShipState_Combatant
    , elements = old.elements |> Dict.map (\k -> migrate_Melee_Element_Element)
    , queue = old.queue |> List.map migrate_Melee_Id_ElementId
    , nextElementId = old.nextElementId
    }


migrate_Melee_Element_Body : Evergreen.V4.Melee.Element.Body -> Evergreen.V5.Melee.Element.Body
migrate_Melee_Element_Body old =
    case old of
        Evergreen.V4.Melee.Element.ShipBody p0 ->
            Evergreen.V5.Melee.Element.ShipBody (p0 |> migrate_Melee_Units_Side)

        Evergreen.V4.Melee.Element.WreckBody p0 ->
            Evergreen.V5.Melee.Element.WreckBody (p0 |> migrate_Melee_Units_Side)

        Evergreen.V4.Melee.Element.PlanetBody ->
            Evergreen.V5.Melee.Element.PlanetBody

        Evergreen.V4.Melee.Element.AsteroidBody ->
            Evergreen.V5.Melee.Element.AsteroidBody

        Evergreen.V4.Melee.Element.CrewBody p0 ->
            Evergreen.V5.Melee.Element.CrewBody
                { origin = p0.origin |> migrate_Melee_Units_Side
                }

        Evergreen.V4.Melee.Element.WeaponImpact p0 ->
            Evergreen.V5.Melee.Element.WeaponImpact (p0 |> migrate_Melee_Projectile_MissileKind)

        Evergreen.V4.Melee.Element.BlastBody ->
            Evergreen.V5.Melee.Element.BlastBody

        Evergreen.V4.Melee.Element.ExplosionBody ->
            Evergreen.V5.Melee.Element.ExplosionBody

        Evergreen.V4.Melee.Element.WarpInBody ->
            Evergreen.V5.Melee.Element.WarpInBody

        Evergreen.V4.Melee.Element.IonTrailBody ->
            Evergreen.V5.Melee.Element.IonTrailBody

        Evergreen.V4.Melee.Element.AndrosynthBubble ->
            Evergreen.V5.Melee.Element.AndrosynthBubble

        Evergreen.V4.Melee.Element.ArilouLaser ->
            Evergreen.V5.Melee.Element.ArilouLaser

        Evergreen.V4.Melee.Element.ChenjesuPhoton ->
            Evergreen.V5.Melee.Element.ChenjesuPhoton

        Evergreen.V4.Melee.Element.ChenjesuFragment ->
            Evergreen.V5.Melee.Element.ChenjesuFragment

        Evergreen.V4.Melee.Element.ChenjesuDogi ->
            Evergreen.V5.Melee.Element.ChenjesuDogi

        Evergreen.V4.Melee.Element.ChmmrLaser ->
            Evergreen.V5.Melee.Element.ChmmrLaser

        Evergreen.V4.Melee.Element.ChmmrSatellite p0 ->
            Evergreen.V5.Melee.Element.ChmmrSatellite
                { orbitFacing = p0.orbitFacing |> migrate_Melee_Units_Facing
                }

        Evergreen.V4.Melee.Element.ChmmrZap ->
            Evergreen.V5.Melee.Element.ChmmrZap

        Evergreen.V4.Melee.Element.DruugeHotShot ->
            Evergreen.V5.Melee.Element.DruugeHotShot

        Evergreen.V4.Melee.Element.EarthlingNuke ->
            Evergreen.V5.Melee.Element.EarthlingNuke

        Evergreen.V4.Melee.Element.EarthlingPointDefense ->
            Evergreen.V5.Melee.Element.EarthlingPointDefense

        Evergreen.V4.Melee.Element.IlwrathFlame ->
            Evergreen.V5.Melee.Element.IlwrathFlame

        Evergreen.V4.Melee.Element.KohrAhSaw ->
            Evergreen.V5.Melee.Element.KohrAhSaw

        Evergreen.V4.Melee.Element.KohrAhFried ->
            Evergreen.V5.Melee.Element.KohrAhFried

        Evergreen.V4.Melee.Element.MelnormeCharge ->
            Evergreen.V5.Melee.Element.MelnormeCharge

        Evergreen.V4.Melee.Element.MelnormeConfusion ->
            Evergreen.V5.Melee.Element.MelnormeConfusion

        Evergreen.V4.Melee.Element.MmrnmhrmLaser ->
            Evergreen.V5.Melee.Element.MmrnmhrmLaser

        Evergreen.V4.Melee.Element.MmrnmhrmMissile ->
            Evergreen.V5.Melee.Element.MmrnmhrmMissile

        Evergreen.V4.Melee.Element.MyconPlasma ->
            Evergreen.V5.Melee.Element.MyconPlasma

        Evergreen.V4.Melee.Element.OrzHowitzer ->
            Evergreen.V5.Melee.Element.OrzHowitzer

        Evergreen.V4.Melee.Element.OrzMarine ->
            Evergreen.V5.Melee.Element.OrzMarine

        Evergreen.V4.Melee.Element.PkunkSpread ->
            Evergreen.V5.Melee.Element.PkunkSpread

        Evergreen.V4.Melee.Element.ShofixtiDart ->
            Evergreen.V5.Melee.Element.ShofixtiDart

        Evergreen.V4.Melee.Element.ShofixtiGlory ->
            Evergreen.V5.Melee.Element.ShofixtiGlory

        Evergreen.V4.Melee.Element.SlylandroLightning ->
            Evergreen.V5.Melee.Element.SlylandroLightning

        Evergreen.V4.Melee.Element.SpathiForward ->
            Evergreen.V5.Melee.Element.SpathiForward

        Evergreen.V4.Melee.Element.SpathiButt ->
            Evergreen.V5.Melee.Element.SpathiButt

        Evergreen.V4.Melee.Element.SupoxPellet ->
            Evergreen.V5.Melee.Element.SupoxPellet

        Evergreen.V4.Melee.Element.SyreenMissile ->
            Evergreen.V5.Melee.Element.SyreenMissile

        Evergreen.V4.Melee.Element.ThraddashBlaster ->
            Evergreen.V5.Melee.Element.ThraddashBlaster

        Evergreen.V4.Melee.Element.ThraddashAfterburn ->
            Evergreen.V5.Melee.Element.ThraddashAfterburn

        Evergreen.V4.Melee.Element.UmgahCone ->
            Evergreen.V5.Melee.Element.UmgahCone

        Evergreen.V4.Melee.Element.UrQuanFusion ->
            Evergreen.V5.Melee.Element.UrQuanFusion

        Evergreen.V4.Melee.Element.UrQuanFighter ->
            Evergreen.V5.Melee.Element.UrQuanFighter

        Evergreen.V4.Melee.Element.UrQuanFighterLaser ->
            Evergreen.V5.Melee.Element.UrQuanFighterLaser

        Evergreen.V4.Melee.Element.UtwigGizmo ->
            Evergreen.V5.Melee.Element.UtwigGizmo

        Evergreen.V4.Melee.Element.VuxLaser ->
            Evergreen.V5.Melee.Element.VuxLaser

        Evergreen.V4.Melee.Element.VuxLimpet ->
            Evergreen.V5.Melee.Element.VuxLimpet

        Evergreen.V4.Melee.Element.YehatMissile ->
            Evergreen.V5.Melee.Element.YehatMissile

        Evergreen.V4.Melee.Element.ZoqSpit ->
            Evergreen.V5.Melee.Element.ZoqSpit

        Evergreen.V4.Melee.Element.ZoqTongue ->
            Evergreen.V5.Melee.Element.ZoqTongue


migrate_Melee_Element_Element : Evergreen.V4.Melee.Element.Element -> Evergreen.V5.Melee.Element.Element
migrate_Melee_Element_Element old =
    { id = old.id |> migrate_Melee_Id_ElementId
    , owner = old.owner |> migrate_Melee_Element_Owner
    , parent = old.parent |> Maybe.map migrate_Melee_Units_Side
    , target = old.target |> Maybe.map migrate_Melee_Id_ElementId
    , flags = old.flags |> migrate_Melee_Element_ElementFlags
    , life = old.life |> migrate_Melee_Element_Life
    , points = old.points
    , mass = old.mass
    , turnWait = old.turnWait |> migrate_Melee_Units_Wait
    , thrustWait = old.thrustWait |> migrate_Melee_Units_Wait
    , colorCycleIndex = old.colorCycleIndex
    , velocity = old.velocity |> migrate_Melee_Units_VelocityDesc
    , intersect = old.intersect |> migrate_Melee_Element_IntersectControl
    , current = old.current |> migrate_Melee_Element_Image
    , next = old.next |> migrate_Melee_Element_Image
    , prim = old.prim |> migrate_Melee_Element_Prim
    , projectile = old.projectile |> Maybe.map migrate_Melee_Projectile_State
    , body = old.body |> migrate_Melee_Element_Body
    }


migrate_Melee_Element_ElementFlags : Evergreen.V4.Melee.Element.ElementFlags -> Evergreen.V5.Melee.Element.ElementFlags
migrate_Melee_Element_ElementFlags old =
    old


migrate_Melee_Element_Image : Evergreen.V4.Melee.Element.Image -> Evergreen.V5.Melee.Element.Image
migrate_Melee_Element_Image old =
    { location = old.location |> migrate_Melee_Units_WorldPoint
    , frameIndex = old.frameIndex
    }


migrate_Melee_Element_IntersectControl : Evergreen.V4.Melee.Element.IntersectControl -> Evergreen.V5.Melee.Element.IntersectControl
migrate_Melee_Element_IntersectControl old =
    { lastTimeVal = old.lastTimeVal
    , endPoint = old.endPoint |> migrate_Melee_Units_WorldPoint
    , stampOrigin = old.stampOrigin |> migrate_Melee_Units_WorldPoint
    }


migrate_Melee_Element_Life : Evergreen.V4.Melee.Element.Life -> Evergreen.V5.Melee.Element.Life
migrate_Melee_Element_Life old =
    case old of
        Evergreen.V4.Melee.Element.Persistent p0 ->
            Evergreen.V5.Melee.Element.Persistent p0

        Evergreen.V4.Melee.Element.Finite p0 ->
            Evergreen.V5.Melee.Element.Finite p0


migrate_Melee_Element_Owner : Evergreen.V4.Melee.Element.Owner -> Evergreen.V5.Melee.Element.Owner
migrate_Melee_Element_Owner old =
    case old of
        Evergreen.V4.Melee.Element.Neutral ->
            Evergreen.V5.Melee.Element.Neutral

        Evergreen.V4.Melee.Element.Owned p0 ->
            Evergreen.V5.Melee.Element.Owned (p0 |> migrate_Melee_Units_Side)


migrate_Melee_Element_Prim : Evergreen.V4.Melee.Element.Prim -> Evergreen.V5.Melee.Element.Prim
migrate_Melee_Element_Prim old =
    case old of
        Evergreen.V4.Melee.Element.NoPrim ->
            Evergreen.V5.Melee.Element.NoPrim

        Evergreen.V4.Melee.Element.Stamp ->
            Evergreen.V5.Melee.Element.Stamp

        Evergreen.V4.Melee.Element.StampFill p0 ->
            Evergreen.V5.Melee.Element.StampFill p0

        Evergreen.V4.Melee.Element.Line ->
            Evergreen.V5.Melee.Element.Line


migrate_Melee_Graphics_Quality : Evergreen.V4.Melee.Graphics.Quality -> Evergreen.V5.Melee.Graphics.Quality
migrate_Melee_Graphics_Quality old =
    case old of
        Evergreen.V4.Melee.Graphics.Classic ->
            Evergreen.V5.Melee.Graphics.Classic

        Evergreen.V4.Melee.Graphics.HighDefinition ->
            Evergreen.V5.Melee.Graphics.HighDefinition


migrate_Melee_Id_ElementId : Evergreen.V4.Melee.Id.ElementId -> Evergreen.V5.Melee.Id.ElementId
migrate_Melee_Id_ElementId old =
    case old of
        Evergreen.V4.Melee.Id.ElementId p0 ->
            Evergreen.V5.Melee.Id.ElementId p0


migrate_Melee_Input_BattleInput : Evergreen.V4.Melee.Input.BattleInput -> Evergreen.V5.Melee.Input.BattleInput
migrate_Melee_Input_BattleInput old =
    { turn = old.turn |> migrate_Melee_Input_Turn
    , thrust = old.thrust
    , weapon = old.weapon
    , special = old.special
    }


migrate_Melee_Input_CyborgRating : Evergreen.V4.Melee.Input.CyborgRating -> Evergreen.V5.Melee.Input.CyborgRating
migrate_Melee_Input_CyborgRating old =
    case old of
        Evergreen.V4.Melee.Input.StandardCyborg ->
            Evergreen.V5.Melee.Input.StandardCyborg

        Evergreen.V4.Melee.Input.GoodCyborg ->
            Evergreen.V5.Melee.Input.GoodCyborg

        Evergreen.V4.Melee.Input.AwesomeCyborg ->
            Evergreen.V5.Melee.Input.AwesomeCyborg


migrate_Melee_Input_Turn : Evergreen.V4.Melee.Input.Turn -> Evergreen.V5.Melee.Input.Turn
migrate_Melee_Input_Turn old =
    case old of
        Evergreen.V4.Melee.Input.NoTurn ->
            Evergreen.V5.Melee.Input.NoTurn

        Evergreen.V4.Melee.Input.TurnLeft ->
            Evergreen.V5.Melee.Input.TurnLeft

        Evergreen.V4.Melee.Input.TurnRight ->
            Evergreen.V5.Melee.Input.TurnRight


migrate_Melee_Local_Mode : Evergreen.V4.Melee.Local.Mode -> Evergreen.V5.Melee.Local.Mode
migrate_Melee_Local_Mode old =
    case old of
        Evergreen.V4.Melee.Local.Solo ->
            Evergreen.V5.Melee.Local.Solo

        Evergreen.V4.Melee.Local.Versus ->
            Evergreen.V5.Melee.Local.Versus

        Evergreen.V4.Melee.Local.Demo ->
            Evergreen.V5.Melee.Local.Demo

        Evergreen.V4.Melee.Local.ReverseSolo ->
            Evergreen.V5.Melee.Local.ReverseSolo


migrate_Melee_Local_Model : Evergreen.V4.Melee.Local.Model -> Evergreen.V5.Melee.Local.Model
migrate_Melee_Local_Model old =
    { names = old.names |> migrate_Melee_Units_Sided identity
    , notice = old.notice
    , difficulty = old.difficulty |> migrate_Melee_Input_CyborgRating
    , fleets = old.fleets |> migrate_Melee_Units_Sided (List.map migrate_Melee_Ship_ShipKind)
    , remaining = old.remaining |> migrate_Melee_Units_Sided (List.map migrate_Melee_Ship_ShipKind)
    , mode = old.mode |> migrate_Melee_Local_Mode
    , phase = old.phase |> migrate_Melee_Local_Phase
    , editing = old.editing |> migrate_Melee_Units_Side
    , seed = old.seed |> migrate_Melee_Rng_Seed
    , graphics = old.graphics |> migrate_Melee_Graphics_Quality
    , sound = old.sound
    , sounds = old.sounds
    , clock = old.clock
    , survivor = old.survivor |> Maybe.map migrate_Melee_Battle_Arena
    , zoomWidth = old.zoomWidth
    , presentationStep = old.presentationStep
    , presentationClock = old.presentationClock
    , round = old.round
    }


migrate_Melee_Local_Msg : Evergreen.V4.Melee.Local.Msg -> Evergreen.V5.Melee.Local.Msg
migrate_Melee_Local_Msg old =
    case old of
        Evergreen.V4.Melee.Local.Edit p0 ->
            Evergreen.V5.Melee.Local.Edit (p0 |> migrate_Melee_Units_Side)

        Evergreen.V4.Melee.Local.Rename p0 p1 ->
            Evergreen.V5.Melee.Local.Rename (p0 |> migrate_Melee_Units_Side) p1

        Evergreen.V4.Melee.Local.SetDifficulty p0 ->
            Evergreen.V5.Melee.Local.SetDifficulty (p0 |> migrate_Melee_Input_CyborgRating)

        Evergreen.V4.Melee.Local.Add p0 ->
            Evergreen.V5.Melee.Local.Add (p0 |> migrate_Melee_Ship_ShipKind)

        Evergreen.V4.Melee.Local.Remove p0 p1 ->
            Evergreen.V5.Melee.Local.Remove (p0 |> migrate_Melee_Units_Side) p1

        Evergreen.V4.Melee.Local.SetMode p0 ->
            Evergreen.V5.Melee.Local.SetMode (p0 |> migrate_Melee_Local_Mode)

        Evergreen.V4.Melee.Local.Start ->
            Evergreen.V5.Melee.Local.Start

        Evergreen.V4.Melee.Local.Pick p0 p1 ->
            Evergreen.V5.Melee.Local.Pick (p0 |> migrate_Melee_Units_Side) p1

        Evergreen.V4.Melee.Local.RandomPick p0 ->
            Evergreen.V5.Melee.Local.RandomPick (p0 |> migrate_Melee_Units_Side)

        Evergreen.V4.Melee.Local.TogglePause ->
            Evergreen.V5.Melee.Local.TogglePause

        Evergreen.V4.Melee.Local.Menu ->
            Evergreen.V5.Melee.Local.Menu

        Evergreen.V4.Melee.Local.Rematch ->
            Evergreen.V5.Melee.Local.Rematch

        Evergreen.V4.Melee.Local.QuickStart ->
            Evergreen.V5.Melee.Local.QuickStart

        Evergreen.V4.Melee.Local.ToggleGraphics ->
            Evergreen.V5.Melee.Local.ToggleGraphics

        Evergreen.V4.Melee.Local.ToggleSound ->
            Evergreen.V5.Melee.Local.ToggleSound

        Evergreen.V4.Melee.Local.Suspend ->
            Evergreen.V5.Melee.Local.Suspend


migrate_Melee_Local_Phase : Evergreen.V4.Melee.Local.Phase -> Evergreen.V5.Melee.Local.Phase
migrate_Melee_Local_Phase old =
    case old of
        Evergreen.V4.Melee.Local.Hangar ->
            Evergreen.V5.Melee.Local.Hangar

        Evergreen.V4.Melee.Local.Selecting p0 p1 ->
            Evergreen.V5.Melee.Local.Selecting (p0 |> Maybe.map migrate_Melee_Ship_ShipKind)
                (p1 |> Maybe.map migrate_Melee_Ship_ShipKind)

        Evergreen.V4.Melee.Local.Countdown p0 p1 ->
            Evergreen.V5.Melee.Local.Countdown p0 (p1 |> migrate_Melee_Battle_Arena)

        Evergreen.V4.Melee.Local.Combat p0 ->
            Evergreen.V5.Melee.Local.Combat (p0 |> migrate_Melee_Battle_Arena)

        Evergreen.V4.Melee.Local.Paused p0 ->
            Evergreen.V5.Melee.Local.Paused (p0 |> migrate_Melee_Battle_Arena)

        Evergreen.V4.Melee.Local.RoundOver p0 p1 ->
            Evergreen.V5.Melee.Local.RoundOver p0 (p1 |> migrate_Melee_Battle_Arena)

        Evergreen.V4.Melee.Local.Victory p0 ->
            Evergreen.V5.Melee.Local.Victory (p0 |> Maybe.map migrate_Melee_Units_Side)


migrate_Melee_Location_Location : Evergreen.V4.Melee.Location.Location -> Evergreen.V5.Melee.Location.Location
migrate_Melee_Location_Location old =
    { room = old.room
    , watching = old.watching
    , local = old.local
    , watchingList = old.watchingList
    , page = old.page
    , roster = old.roster
    , mode = old.mode |> migrate_Melee_Local_Mode
    , difficulty = old.difficulty |> migrate_Melee_Input_CyborgRating
    }


migrate_Melee_Menu_Event : Evergreen.V4.Melee.Menu.Event -> Evergreen.V5.Melee.Menu.Event
migrate_Melee_Menu_Event old =
    case old of
        Evergreen.V4.Melee.Menu.Click p0 ->
            Evergreen.V5.Melee.Menu.Click p0

        Evergreen.V4.Melee.Menu.Key p0 p1 p2 p3 ->
            Evergreen.V5.Melee.Menu.Key p0 p1 p2 p3

        Evergreen.V4.Melee.Menu.Ignored ->
            Evergreen.V5.Melee.Menu.Ignored


migrate_Melee_Preview_Preview : Evergreen.V4.Melee.Preview.Preview -> Evergreen.V5.Melee.Preview.Preview
migrate_Melee_Preview_Preview old =
    case old of
        Evergreen.V4.Melee.Preview.Snapshot p0 ->
            Evergreen.V5.Melee.Preview.Snapshot (p0 |> migrate_Melee_Local_Model)

        Evergreen.V4.Melee.Preview.Delta p0 ->
            Evergreen.V5.Melee.Preview.Delta (p0 |> migrate_Melee_Stream_Delta)


migrate_Melee_Projectile_BeamKind : Evergreen.V4.Melee.Projectile.BeamKind -> Evergreen.V5.Melee.Projectile.BeamKind
migrate_Melee_Projectile_BeamKind old =
    case old of
        Evergreen.V4.Melee.Projectile.AutoAim ->
            Evergreen.V5.Melee.Projectile.AutoAim

        Evergreen.V4.Melee.Projectile.Megawatt ->
            Evergreen.V5.Melee.Projectile.Megawatt

        Evergreen.V4.Melee.Projectile.Twin ->
            Evergreen.V5.Melee.Projectile.Twin

        Evergreen.V4.Melee.Projectile.Green ->
            Evergreen.V5.Melee.Projectile.Green

        Evergreen.V4.Melee.Projectile.PointDefense ->
            Evergreen.V5.Melee.Projectile.PointDefense

        Evergreen.V4.Melee.Projectile.Zap ->
            Evergreen.V5.Melee.Projectile.Zap

        Evergreen.V4.Melee.Projectile.FighterBeam ->
            Evergreen.V5.Melee.Projectile.FighterBeam


migrate_Melee_Projectile_ContactKind : Evergreen.V4.Melee.Projectile.ContactKind -> Evergreen.V5.Melee.Projectile.ContactKind
migrate_Melee_Projectile_ContactKind old =
    case old of
        Evergreen.V4.Melee.Projectile.Cone ->
            Evergreen.V5.Melee.Projectile.Cone

        Evergreen.V4.Melee.Projectile.Tongue ->
            Evergreen.V5.Melee.Projectile.Tongue


migrate_Melee_Projectile_MissileKind : Evergreen.V4.Melee.Projectile.MissileKind -> Evergreen.V5.Melee.Projectile.MissileKind
migrate_Melee_Projectile_MissileKind old =
    case old of
        Evergreen.V4.Melee.Projectile.Bubble ->
            Evergreen.V5.Melee.Projectile.Bubble

        Evergreen.V4.Melee.Projectile.Crystal ->
            Evergreen.V5.Melee.Projectile.Crystal

        Evergreen.V4.Melee.Projectile.Shard ->
            Evergreen.V5.Melee.Projectile.Shard

        Evergreen.V4.Melee.Projectile.Dogi ->
            Evergreen.V5.Melee.Projectile.Dogi

        Evergreen.V4.Melee.Projectile.Cannon ->
            Evergreen.V5.Melee.Projectile.Cannon

        Evergreen.V4.Melee.Projectile.Nuke ->
            Evergreen.V5.Melee.Projectile.Nuke

        Evergreen.V4.Melee.Projectile.Flame ->
            Evergreen.V5.Melee.Projectile.Flame

        Evergreen.V4.Melee.Projectile.Saw ->
            Evergreen.V5.Melee.Projectile.Saw

        Evergreen.V4.Melee.Projectile.Fried ->
            Evergreen.V5.Melee.Projectile.Fried

        Evergreen.V4.Melee.Projectile.Charge ->
            Evergreen.V5.Melee.Projectile.Charge

        Evergreen.V4.Melee.Projectile.Confusion ->
            Evergreen.V5.Melee.Projectile.Confusion

        Evergreen.V4.Melee.Projectile.Torpedo ->
            Evergreen.V5.Melee.Projectile.Torpedo

        Evergreen.V4.Melee.Projectile.Plasma ->
            Evergreen.V5.Melee.Projectile.Plasma

        Evergreen.V4.Melee.Projectile.Howitzer ->
            Evergreen.V5.Melee.Projectile.Howitzer

        Evergreen.V4.Melee.Projectile.Marine ->
            Evergreen.V5.Melee.Projectile.Marine

        Evergreen.V4.Melee.Projectile.Bug ->
            Evergreen.V5.Melee.Projectile.Bug

        Evergreen.V4.Melee.Projectile.Dart ->
            Evergreen.V5.Melee.Projectile.Dart

        Evergreen.V4.Melee.Projectile.SpathiShot ->
            Evergreen.V5.Melee.Projectile.SpathiShot

        Evergreen.V4.Melee.Projectile.Butt ->
            Evergreen.V5.Melee.Projectile.Butt

        Evergreen.V4.Melee.Projectile.Pellet ->
            Evergreen.V5.Melee.Projectile.Pellet

        Evergreen.V4.Melee.Projectile.Dagger ->
            Evergreen.V5.Melee.Projectile.Dagger

        Evergreen.V4.Melee.Projectile.Blaster ->
            Evergreen.V5.Melee.Projectile.Blaster

        Evergreen.V4.Melee.Projectile.Napalm ->
            Evergreen.V5.Melee.Projectile.Napalm

        Evergreen.V4.Melee.Projectile.Fusion ->
            Evergreen.V5.Melee.Projectile.Fusion

        Evergreen.V4.Melee.Projectile.Fighter ->
            Evergreen.V5.Melee.Projectile.Fighter

        Evergreen.V4.Melee.Projectile.Lance ->
            Evergreen.V5.Melee.Projectile.Lance

        Evergreen.V4.Melee.Projectile.Limpet ->
            Evergreen.V5.Melee.Projectile.Limpet

        Evergreen.V4.Melee.Projectile.YehatShot ->
            Evergreen.V5.Melee.Projectile.YehatShot

        Evergreen.V4.Melee.Projectile.Spit ->
            Evergreen.V5.Melee.Projectile.Spit


migrate_Melee_Projectile_State : Evergreen.V4.Melee.Projectile.State -> Evergreen.V5.Melee.Projectile.State
migrate_Melee_Projectile_State old =
    case old of
        Evergreen.V4.Melee.Projectile.Flying p0 p1 ->
            Evergreen.V5.Melee.Projectile.Flying (p0 |> migrate_Melee_Projectile_MissileKind)
                { age = p1.age
                , facing = p1.facing |> migrate_Melee_Units_Facing
                , trackingWait = p1.trackingWait
                }

        Evergreen.V4.Melee.Projectile.Charging p0 ->
            Evergreen.V5.Melee.Projectile.Charging
                { ticks = p0.ticks
                , facing = p0.facing |> migrate_Melee_Units_Facing
                }

        Evergreen.V4.Melee.Projectile.Ray p0 p1 ->
            Evergreen.V5.Melee.Projectile.Ray (p0 |> migrate_Melee_Projectile_BeamKind)
                { origin = p1.origin |> migrate_Melee_Units_WorldPoint
                , end = p1.end |> migrate_Melee_Units_WorldPoint
                }

        Evergreen.V4.Melee.Projectile.Attached p0 p1 ->
            Evergreen.V5.Melee.Projectile.Attached (p0 |> migrate_Melee_Projectile_ContactKind)
                { age = p1.age
                , facing = p1.facing |> migrate_Melee_Units_Facing
                }

        Evergreen.V4.Melee.Projectile.LightningSegment p0 ->
            Evergreen.V5.Melee.Projectile.LightningSegment
                { origin = p0.origin |> migrate_Melee_Units_WorldPoint
                , end = p0.end |> migrate_Melee_Units_WorldPoint
                }


migrate_Melee_Ranking_Match : Evergreen.V4.Melee.Ranking.Match -> Evergreen.V5.Melee.Ranking.Match
migrate_Melee_Ranking_Match old =
    { players = old.players |> migrate_Melee_Units_Sided identity
    , ratings = old.ratings |> migrate_Melee_Units_Sided identity
    , deadline = old.deadline
    , started = old.started
    , away = old.away |> migrate_Melee_Units_Sided identity
    , outcome = old.outcome |> Maybe.map migrate_Melee_Ranking_Outcome
    }


migrate_Melee_Ranking_Outcome : Evergreen.V4.Melee.Ranking.Outcome -> Evergreen.V5.Melee.Ranking.Outcome
migrate_Melee_Ranking_Outcome old =
    case old of
        Evergreen.V4.Melee.Ranking.Cancelled ->
            Evergreen.V5.Melee.Ranking.Cancelled

        Evergreen.V4.Melee.Ranking.Scored p0 ->
            Evergreen.V5.Melee.Ranking.Scored
                { winner = p0.winner |> Maybe.map migrate_Melee_Units_Side
                , changes = p0.changes |> migrate_Melee_Units_Sided identity
                , ratings = p0.ratings |> migrate_Melee_Units_Sided identity
                }


migrate_Melee_Ranking_Profile : Evergreen.V4.Melee.Ranking.Profile -> Evergreen.V5.Melee.Ranking.Profile
migrate_Melee_Ranking_Profile old =
    old


migrate_Melee_Ranking_View : Evergreen.V4.Melee.Ranking.View -> Evergreen.V5.Melee.Ranking.View
migrate_Melee_Ranking_View old =
    { ratings = old.ratings |> migrate_Melee_Units_Sided identity
    , deadline = old.deadline
    , outcome = old.outcome |> Maybe.map migrate_Melee_Ranking_Outcome
    }


migrate_Melee_Rng_Seed : Evergreen.V4.Melee.Rng.Seed -> Evergreen.V5.Melee.Rng.Seed
migrate_Melee_Rng_Seed old =
    case old of
        Evergreen.V4.Melee.Rng.Seed p0 ->
            Evergreen.V5.Melee.Rng.Seed p0


migrate_Melee_Room_Client : Evergreen.V4.Melee.Room.Client -> Evergreen.V5.Melee.Room.Client
migrate_Melee_Room_Client old =
    case old of
        Evergreen.V4.Melee.Room.Browsing ->
            Evergreen.V5.Melee.Room.Browsing

        Evergreen.V4.Melee.Room.Seated p0 ->
            Evergreen.V5.Melee.Room.Seated (p0 |> migrate_Melee_Room_Snapshot)

        Evergreen.V4.Melee.Room.Watching p0 ->
            Evergreen.V5.Melee.Room.Watching (p0 |> migrate_Melee_Room_SpectatorSnapshot)


migrate_Melee_Room_Host : Evergreen.V4.Melee.Room.Host -> Evergreen.V5.Melee.Room.Host
migrate_Melee_Room_Host old =
    { rooms = old.rooms |> Dict.map (\k -> migrate_Melee_Room_Room)
    , roomSetups = old.roomSetups |> Dict.map (\k -> migrate_Melee_Room_RoomSetup)
    , clientRooms = old.clientRooms
    , nextId = old.nextId
    , now = old.now
    , previewClients = old.previewClients
    , previewAt = old.previewAt
    , previewGame = old.previewGame |> Maybe.map migrate_Melee_Local_Model
    , players = old.players
    , queue = old.queue
    }


migrate_Melee_Room_Listing : Evergreen.V4.Melee.Room.Listing -> Evergreen.V5.Melee.Room.Listing
migrate_Melee_Room_Listing old =
    { code = old.code
    , name = old.name
    , ships = old.ships
    , points = old.points
    , fleet = old.fleet |> List.map migrate_Melee_Ship_ShipKind
    }


migrate_Melee_Room_LocalMsg : Evergreen.V4.Melee.Room.LocalMsg -> Evergreen.V5.Melee.Room.LocalMsg
migrate_Melee_Room_LocalMsg old =
    case old of
        Evergreen.V4.Melee.Room.Tick ->
            Evergreen.V5.Melee.Room.Tick

        Evergreen.V4.Melee.Room.KeyDown p0 ->
            Evergreen.V5.Melee.Room.KeyDown p0

        Evergreen.V4.Melee.Room.KeyUp p0 ->
            Evergreen.V5.Melee.Room.KeyUp p0

        Evergreen.V4.Melee.Room.Restart ->
            Evergreen.V5.Melee.Room.Restart


migrate_Melee_Room_Room : Evergreen.V4.Melee.Room.Room -> Evergreen.V5.Melee.Room.Room
migrate_Melee_Room_Room old =
    { code = old.code
    , seats = old.seats |> migrate_Melee_Units_Sided identity
    , game = old.game |> migrate_Melee_Local_Model
    , inputs = old.inputs |> migrate_Melee_Units_Sided migrate_Melee_Input_BattleInput
    , controllers = old.controllers |> migrate_Melee_Units_Sided migrate_Melee_Room_SeatControl
    , ready = old.ready |> migrate_Melee_Units_Sided identity
    , revision = old.revision
    , lastBroadcast = old.lastBroadcast |> Maybe.map migrate_Melee_Local_Model
    , broadcastAt = old.broadcastAt
    , spectators = old.spectators
    , touched = old.touched
    , ranked = old.ranked |> Maybe.map migrate_Melee_Ranking_Match
    }


migrate_Melee_Room_RoomSetup : Evergreen.V4.Melee.Room.RoomSetup -> Evergreen.V5.Melee.Room.RoomSetup
migrate_Melee_Room_RoomSetup old =
    { names = old.names |> migrate_Melee_Units_Sided identity
    , fleets = old.fleets |> migrate_Melee_Units_Sided (List.map migrate_Melee_Ship_ShipKind)
    , controllers = old.controllers |> migrate_Melee_Units_Sided migrate_Melee_Room_SeatControl
    }


migrate_Melee_Room_SeatControl : Evergreen.V4.Melee.Room.SeatControl -> Evergreen.V5.Melee.Room.SeatControl
migrate_Melee_Room_SeatControl old =
    case old of
        Evergreen.V4.Melee.Room.Human ->
            Evergreen.V5.Melee.Room.Human

        Evergreen.V4.Melee.Room.Computer ->
            Evergreen.V5.Melee.Room.Computer


migrate_Melee_Room_Snapshot : Evergreen.V4.Melee.Room.Snapshot -> Evergreen.V5.Melee.Room.Snapshot
migrate_Melee_Room_Snapshot old =
    { code = old.code
    , side = old.side |> migrate_Melee_Units_Side
    , game = old.game |> migrate_Melee_Local_Model
    , connected = old.connected |> migrate_Melee_Units_Sided identity
    , controllers = old.controllers |> migrate_Melee_Units_Sided migrate_Melee_Room_SeatControl
    , ready = old.ready |> migrate_Melee_Units_Sided identity
    , revision = old.revision
    , ranked = old.ranked |> Maybe.map migrate_Melee_Ranking_View
    }


migrate_Melee_Room_SpectatorSnapshot : Evergreen.V4.Melee.Room.SpectatorSnapshot -> Evergreen.V5.Melee.Room.SpectatorSnapshot
migrate_Melee_Room_SpectatorSnapshot old =
    { code = old.code
    , game = old.game |> migrate_Melee_Local_Model
    , connected = old.connected |> migrate_Melee_Units_Sided identity
    , controllers = old.controllers |> migrate_Melee_Units_Sided migrate_Melee_Room_SeatControl
    , revision = old.revision
    }


migrate_Melee_Room_ToHost : Evergreen.V4.Melee.Room.ToHost -> Evergreen.V5.Melee.Room.ToHost
migrate_Melee_Room_ToHost old =
    case old of
        Evergreen.V4.Melee.Room.Identify ->
            Evergreen.V5.Melee.Room.Identify

        Evergreen.V4.Melee.Room.FindMatch ->
            Evergreen.V5.Melee.Room.FindMatch

        Evergreen.V4.Melee.Room.CancelSearch ->
            Evergreen.V5.Melee.Room.CancelSearch

        Evergreen.V4.Melee.Room.SetPlayerName p0 ->
            Evergreen.V5.Melee.Room.SetPlayerName p0

        Evergreen.V4.Melee.Room.DiscoverRooms ->
            Evergreen.V5.Melee.Room.DiscoverRooms

        Evergreen.V4.Melee.Room.CreateRoom ->
            Evergreen.V5.Melee.Room.CreateRoom

        Evergreen.V4.Melee.Room.JoinRoom p0 ->
            Evergreen.V5.Melee.Room.JoinRoom p0

        Evergreen.V4.Melee.Room.WatchRoom p0 ->
            Evergreen.V5.Melee.Room.WatchRoom p0

        Evergreen.V4.Melee.Room.LeaveRoom ->
            Evergreen.V5.Melee.Room.LeaveRoom

        Evergreen.V4.Melee.Room.Rename p0 ->
            Evergreen.V5.Melee.Room.Rename p0

        Evergreen.V4.Melee.Room.Add p0 ->
            Evergreen.V5.Melee.Room.Add (p0 |> migrate_Melee_Ship_ShipKind)

        Evergreen.V4.Melee.Room.Remove p0 ->
            Evergreen.V5.Melee.Room.Remove p0

        Evergreen.V4.Melee.Room.ReplaceFleet p0 p1 ->
            Evergreen.V5.Melee.Room.ReplaceFleet p0 (p1 |> List.map migrate_Melee_Ship_ShipKind)

        Evergreen.V4.Melee.Room.Visit p0 p1 ->
            Evergreen.V5.Melee.Room.Visit p0 p1

        Evergreen.V4.Melee.Room.PreviewSubscription p0 ->
            Evergreen.V5.Melee.Room.PreviewSubscription p0

        Evergreen.V4.Melee.Room.SetController p0 p1 ->
            Evergreen.V5.Melee.Room.SetController (p0 |> migrate_Melee_Units_Side)
                (p1 |> migrate_Melee_Room_SeatControl)

        Evergreen.V4.Melee.Room.Ready ->
            Evergreen.V5.Melee.Room.Ready

        Evergreen.V4.Melee.Room.Pick p0 ->
            Evergreen.V5.Melee.Room.Pick p0

        Evergreen.V4.Melee.Room.RandomPick ->
            Evergreen.V5.Melee.Room.RandomPick

        Evergreen.V4.Melee.Room.Controls p0 ->
            Evergreen.V5.Melee.Room.Controls (p0 |> migrate_Melee_Input_BattleInput)

        Evergreen.V4.Melee.Room.Pause ->
            Evergreen.V5.Melee.Room.Pause

        Evergreen.V4.Melee.Room.Suspend ->
            Evergreen.V5.Melee.Room.Suspend

        Evergreen.V4.Melee.Room.Hangar ->
            Evergreen.V5.Melee.Room.Hangar

        Evergreen.V4.Melee.Room.Rematch ->
            Evergreen.V5.Melee.Room.Rematch


migrate_Melee_Room_ToSeat : Evergreen.V4.Melee.Room.ToSeat -> Evergreen.V5.Melee.Room.ToSeat
migrate_Melee_Room_ToSeat old =
    case old of
        Evergreen.V4.Melee.Room.PlayerStatus p0 p1 ->
            Evergreen.V5.Melee.Room.PlayerStatus (p0 |> migrate_Melee_Ranking_Profile) p1

        Evergreen.V4.Melee.Room.MatchFound p0 ->
            Evergreen.V5.Melee.Room.MatchFound (p0 |> migrate_Melee_Room_Snapshot)

        Evergreen.V4.Melee.Room.RoomsAvailable p0 ->
            Evergreen.V5.Melee.Room.RoomsAvailable (p0 |> List.map migrate_Melee_Room_Listing)

        Evergreen.V4.Melee.Room.CombatDelta p0 p1 p2 ->
            Evergreen.V5.Melee.Room.CombatDelta p0 p1 (p2 |> migrate_Melee_Stream_Delta)

        Evergreen.V4.Melee.Room.ArenaPreview p0 ->
            Evergreen.V5.Melee.Room.ArenaPreview (p0 |> migrate_Melee_Preview_Preview)

        Evergreen.V4.Melee.Room.GamesAvailable p0 ->
            Evergreen.V5.Melee.Room.GamesAvailable p0

        Evergreen.V4.Melee.Room.SpectatorView p0 ->
            Evergreen.V5.Melee.Room.SpectatorView (p0 |> migrate_Melee_Room_SpectatorSnapshot)

        Evergreen.V4.Melee.Room.RoomSnapshot p0 ->
            Evergreen.V5.Melee.Room.RoomSnapshot (p0 |> migrate_Melee_Room_Snapshot)

        Evergreen.V4.Melee.Room.RoomLeft ->
            Evergreen.V5.Melee.Room.RoomLeft

        Evergreen.V4.Melee.Room.RoomError p0 ->
            Evergreen.V5.Melee.Room.RoomError p0


migrate_Melee_ShipState_AndrosynthExtra : Evergreen.V4.Melee.ShipState.AndrosynthExtra -> Evergreen.V5.Melee.ShipState.AndrosynthExtra
migrate_Melee_ShipState_AndrosynthExtra old =
    case old of
        Evergreen.V4.Melee.ShipState.Guardian ->
            Evergreen.V5.Melee.ShipState.Guardian

        Evergreen.V4.Melee.ShipState.Blazer p0 ->
            Evergreen.V5.Melee.ShipState.Blazer
                { guardian = p0.guardian |> migrate_Melee_Ship_Characteristics
                }


migrate_Melee_ShipState_ArilouExtra : Evergreen.V4.Melee.ShipState.ArilouExtra -> Evergreen.V5.Melee.ShipState.ArilouExtra
migrate_Melee_ShipState_ArilouExtra old =
    case old of
        Evergreen.V4.Melee.ShipState.Present ->
            Evergreen.V5.Melee.ShipState.Present

        Evergreen.V4.Melee.ShipState.Teleporting p0 ->
            Evergreen.V5.Melee.ShipState.Teleporting (p0 |> migrate_Melee_Units_Wait)


migrate_Melee_ShipState_ChmmrExtra : Evergreen.V4.Melee.ShipState.ChmmrExtra -> Evergreen.V5.Melee.ShipState.ChmmrExtra
migrate_Melee_ShipState_ChmmrExtra old =
    case old of
        Evergreen.V4.Melee.ShipState.TractorIdle ->
            Evergreen.V5.Melee.ShipState.TractorIdle

        Evergreen.V4.Melee.ShipState.TractorOn ->
            Evergreen.V5.Melee.ShipState.TractorOn


migrate_Melee_ShipState_Combatant : Evergreen.V4.Melee.ShipState.Combatant -> Evergreen.V5.Melee.ShipState.Combatant
migrate_Melee_ShipState_Combatant old =
    case old of
        Evergreen.V4.Melee.ShipState.LiveAndrosynth p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveAndrosynth (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_AndrosynthExtra)

        Evergreen.V4.Melee.ShipState.LiveArilou p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveArilou (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ArilouExtra)

        Evergreen.V4.Melee.ShipState.LiveChenjesu p0 ->
            Evergreen.V5.Melee.ShipState.LiveChenjesu (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveChmmr p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveChmmr (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ChmmrExtra)

        Evergreen.V4.Melee.ShipState.LiveDruuge p0 ->
            Evergreen.V5.Melee.ShipState.LiveDruuge (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveEarthling p0 ->
            Evergreen.V5.Melee.ShipState.LiveEarthling (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveIlwrath p0 ->
            Evergreen.V5.Melee.ShipState.LiveIlwrath (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveKohrAh p0 ->
            Evergreen.V5.Melee.ShipState.LiveKohrAh (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveMelnorme p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveMelnorme (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_MelnormeExtra)

        Evergreen.V4.Melee.ShipState.LiveMmrnmhrm p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveMmrnmhrm (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_MmrnmhrmExtra)

        Evergreen.V4.Melee.ShipState.LiveMycon p0 ->
            Evergreen.V5.Melee.ShipState.LiveMycon (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveOrz p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveOrz (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_OrzExtra)

        Evergreen.V4.Melee.ShipState.LivePkunk p0 p1 ->
            Evergreen.V5.Melee.ShipState.LivePkunk (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_PkunkExtra)

        Evergreen.V4.Melee.ShipState.LiveShofixti p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveShofixti (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ShofixtiExtra)

        Evergreen.V4.Melee.ShipState.LiveSlylandro p0 ->
            Evergreen.V5.Melee.ShipState.LiveSlylandro (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveSpathi p0 ->
            Evergreen.V5.Melee.ShipState.LiveSpathi (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveSupox p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveSupox (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_SupoxExtra)

        Evergreen.V4.Melee.ShipState.LiveSyreen p0 ->
            Evergreen.V5.Melee.ShipState.LiveSyreen (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveThraddash p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveThraddash (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ThraddashExtra)

        Evergreen.V4.Melee.ShipState.LiveUmgah p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveUmgah (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_UmgahExtra)

        Evergreen.V4.Melee.ShipState.LiveUrQuan p0 ->
            Evergreen.V5.Melee.ShipState.LiveUrQuan (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveUtwig p0 ->
            Evergreen.V5.Melee.ShipState.LiveUtwig (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveVux p0 p1 ->
            Evergreen.V5.Melee.ShipState.LiveVux (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_VuxExtra)

        Evergreen.V4.Melee.ShipState.LiveYehat p0 ->
            Evergreen.V5.Melee.ShipState.LiveYehat (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V4.Melee.ShipState.LiveZoqFotPik p0 ->
            Evergreen.V5.Melee.ShipState.LiveZoqFotPik (p0 |> migrate_Melee_ShipState_CombatantCore)


migrate_Melee_ShipState_CombatantCore : Evergreen.V4.Melee.ShipState.CombatantCore -> Evergreen.V5.Melee.ShipState.CombatantCore
migrate_Melee_ShipState_CombatantCore old =
    { element = old.element |> migrate_Melee_Id_ElementId
    , characteristics = old.characteristics |> migrate_Melee_Ship_Characteristics
    , energy = old.energy
    , maxEnergy = old.maxEnergy
    , maxCrew = old.maxCrew
    , weaponWait = old.weaponWait |> migrate_Melee_Units_Wait
    , specialWait = old.specialWait |> migrate_Melee_Units_Wait
    , energyWait = old.energyWait |> migrate_Melee_Units_Wait
    , facing = old.facing |> migrate_Melee_Units_Facing
    , input = old.input |> migrate_Melee_Input_BattleInput
    , shieldTicks = old.shieldTicks
    , confusedTicks = old.confusedTicks
    , chargeTicks = old.chargeTicks
    , cloaked = old.cloaked
    , oldInput = old.oldInput |> migrate_Melee_Input_BattleInput
    , flags = old.flags |> migrate_Melee_ShipState_MotionFlags
    }


migrate_Melee_ShipState_MelnormeExtra : Evergreen.V4.Melee.ShipState.MelnormeExtra -> Evergreen.V5.Melee.ShipState.MelnormeExtra
migrate_Melee_ShipState_MelnormeExtra old =
    { pump = old.pump |> migrate_Melee_ShipState_PumpLevel
    , levelCounter = old.levelCounter |> migrate_Melee_Units_Wait
    }


migrate_Melee_ShipState_MmrnmhrmExtra : Evergreen.V4.Melee.ShipState.MmrnmhrmExtra -> Evergreen.V5.Melee.ShipState.MmrnmhrmExtra
migrate_Melee_ShipState_MmrnmhrmExtra old =
    { form = old.form |> migrate_Melee_ShipState_MmrnmhrmForm
    , otherWing = old.otherWing |> migrate_Melee_Ship_Characteristics
    }


migrate_Melee_ShipState_MmrnmhrmForm : Evergreen.V4.Melee.ShipState.MmrnmhrmForm -> Evergreen.V5.Melee.ShipState.MmrnmhrmForm
migrate_Melee_ShipState_MmrnmhrmForm old =
    case old of
        Evergreen.V4.Melee.ShipState.XWing ->
            Evergreen.V5.Melee.ShipState.XWing

        Evergreen.V4.Melee.ShipState.YWing ->
            Evergreen.V5.Melee.ShipState.YWing


migrate_Melee_ShipState_MotionFlags : Evergreen.V4.Melee.ShipState.MotionFlags -> Evergreen.V5.Melee.ShipState.MotionFlags
migrate_Melee_ShipState_MotionFlags old =
    old


migrate_Melee_ShipState_OrzExtra : Evergreen.V4.Melee.ShipState.OrzExtra -> Evergreen.V5.Melee.ShipState.OrzExtra
migrate_Melee_ShipState_OrzExtra old =
    { turretFacing = old.turretFacing |> migrate_Melee_Units_Facing
    , turretWait = old.turretWait |> migrate_Melee_Units_Wait
    }


migrate_Melee_ShipState_PkunkExtra : Evergreen.V4.Melee.ShipState.PkunkExtra -> Evergreen.V5.Melee.ShipState.PkunkExtra
migrate_Melee_ShipState_PkunkExtra old =
    case old of
        Evergreen.V4.Melee.ShipState.Flying ->
            Evergreen.V5.Melee.ShipState.Flying

        Evergreen.V4.Melee.ShipState.Phoenix p0 ->
            Evergreen.V5.Melee.ShipState.Phoenix (p0 |> migrate_Melee_Id_ElementId)


migrate_Melee_ShipState_PumpLevel : Evergreen.V4.Melee.ShipState.PumpLevel -> Evergreen.V5.Melee.ShipState.PumpLevel
migrate_Melee_ShipState_PumpLevel old =
    case old of
        Evergreen.V4.Melee.ShipState.Pump1 ->
            Evergreen.V5.Melee.ShipState.Pump1

        Evergreen.V4.Melee.ShipState.Pump2 ->
            Evergreen.V5.Melee.ShipState.Pump2

        Evergreen.V4.Melee.ShipState.Pump3 ->
            Evergreen.V5.Melee.ShipState.Pump3

        Evergreen.V4.Melee.ShipState.Pump4 ->
            Evergreen.V5.Melee.ShipState.Pump4


migrate_Melee_ShipState_ShofixtiExtra : Evergreen.V4.Melee.ShipState.ShofixtiExtra -> Evergreen.V5.Melee.ShipState.ShofixtiExtra
migrate_Melee_ShipState_ShofixtiExtra old =
    case old of
        Evergreen.V4.Melee.ShipState.SafetyClosed ->
            Evergreen.V5.Melee.ShipState.SafetyClosed

        Evergreen.V4.Melee.ShipState.OpeningSafety ->
            Evergreen.V5.Melee.ShipState.OpeningSafety

        Evergreen.V4.Melee.ShipState.SafetyOpen ->
            Evergreen.V5.Melee.ShipState.SafetyOpen

        Evergreen.V4.Melee.ShipState.ArmingDevice ->
            Evergreen.V5.Melee.ShipState.ArmingDevice

        Evergreen.V4.Melee.ShipState.Armed ->
            Evergreen.V5.Melee.ShipState.Armed

        Evergreen.V4.Melee.ShipState.GloryDevice ->
            Evergreen.V5.Melee.ShipState.GloryDevice


migrate_Melee_ShipState_SupoxExtra : Evergreen.V4.Melee.ShipState.SupoxExtra -> Evergreen.V5.Melee.ShipState.SupoxExtra
migrate_Melee_ShipState_SupoxExtra old =
    case old of
        Evergreen.V4.Melee.ShipState.ForwardOnly ->
            Evergreen.V5.Melee.ShipState.ForwardOnly

        Evergreen.V4.Melee.ShipState.Strafing p0 ->
            Evergreen.V5.Melee.ShipState.Strafing (p0 |> migrate_Melee_Input_Turn)


migrate_Melee_ShipState_ThraddashExtra : Evergreen.V4.Melee.ShipState.ThraddashExtra -> Evergreen.V5.Melee.ShipState.ThraddashExtra
migrate_Melee_ShipState_ThraddashExtra old =
    case old of
        Evergreen.V4.Melee.ShipState.Cruise ->
            Evergreen.V5.Melee.ShipState.Cruise

        Evergreen.V4.Melee.ShipState.Afterburning p0 ->
            Evergreen.V5.Melee.ShipState.Afterburning p0


migrate_Melee_ShipState_UmgahExtra : Evergreen.V4.Melee.ShipState.UmgahExtra -> Evergreen.V5.Melee.ShipState.UmgahExtra
migrate_Melee_ShipState_UmgahExtra old =
    { prevFacing = old.prevFacing |> migrate_Melee_Units_Facing
    }


migrate_Melee_ShipState_VuxExtra : Evergreen.V4.Melee.ShipState.VuxExtra -> Evergreen.V5.Melee.ShipState.VuxExtra
migrate_Melee_ShipState_VuxExtra old =
    case old of
        Evergreen.V4.Melee.ShipState.WarpPending ->
            Evergreen.V5.Melee.ShipState.WarpPending

        Evergreen.V4.Melee.ShipState.OnField ->
            Evergreen.V5.Melee.ShipState.OnField


migrate_Melee_Ship_Characteristics : Evergreen.V4.Melee.Ship.Characteristics -> Evergreen.V5.Melee.Ship.Characteristics
migrate_Melee_Ship_Characteristics old =
    { maxThrust = old.maxThrust
    , thrustIncrement = old.thrustIncrement
    , energyRegeneration = old.energyRegeneration
    , weaponEnergyCost = old.weaponEnergyCost
    , specialEnergyCost = old.specialEnergyCost
    , energyWait = old.energyWait |> migrate_Melee_Units_Wait
    , turnWait = old.turnWait |> migrate_Melee_Units_Wait
    , thrustWait = old.thrustWait |> migrate_Melee_Units_Wait
    , weaponWait = old.weaponWait |> migrate_Melee_Units_Wait
    , specialWait = old.specialWait |> migrate_Melee_Units_Wait
    , shipMass = old.shipMass
    }


migrate_Melee_Ship_ShipKind : Evergreen.V4.Melee.Ship.ShipKind -> Evergreen.V5.Melee.Ship.ShipKind
migrate_Melee_Ship_ShipKind old =
    case old of
        Evergreen.V4.Melee.Ship.Androsynth ->
            Evergreen.V5.Melee.Ship.Androsynth

        Evergreen.V4.Melee.Ship.Arilou ->
            Evergreen.V5.Melee.Ship.Arilou

        Evergreen.V4.Melee.Ship.Chenjesu ->
            Evergreen.V5.Melee.Ship.Chenjesu

        Evergreen.V4.Melee.Ship.Chmmr ->
            Evergreen.V5.Melee.Ship.Chmmr

        Evergreen.V4.Melee.Ship.Druuge ->
            Evergreen.V5.Melee.Ship.Druuge

        Evergreen.V4.Melee.Ship.Earthling ->
            Evergreen.V5.Melee.Ship.Earthling

        Evergreen.V4.Melee.Ship.Ilwrath ->
            Evergreen.V5.Melee.Ship.Ilwrath

        Evergreen.V4.Melee.Ship.KohrAh ->
            Evergreen.V5.Melee.Ship.KohrAh

        Evergreen.V4.Melee.Ship.Melnorme ->
            Evergreen.V5.Melee.Ship.Melnorme

        Evergreen.V4.Melee.Ship.Mmrnmhrm ->
            Evergreen.V5.Melee.Ship.Mmrnmhrm

        Evergreen.V4.Melee.Ship.Mycon ->
            Evergreen.V5.Melee.Ship.Mycon

        Evergreen.V4.Melee.Ship.Orz ->
            Evergreen.V5.Melee.Ship.Orz

        Evergreen.V4.Melee.Ship.Pkunk ->
            Evergreen.V5.Melee.Ship.Pkunk

        Evergreen.V4.Melee.Ship.Shofixti ->
            Evergreen.V5.Melee.Ship.Shofixti

        Evergreen.V4.Melee.Ship.Slylandro ->
            Evergreen.V5.Melee.Ship.Slylandro

        Evergreen.V4.Melee.Ship.Spathi ->
            Evergreen.V5.Melee.Ship.Spathi

        Evergreen.V4.Melee.Ship.Supox ->
            Evergreen.V5.Melee.Ship.Supox

        Evergreen.V4.Melee.Ship.Syreen ->
            Evergreen.V5.Melee.Ship.Syreen

        Evergreen.V4.Melee.Ship.Thraddash ->
            Evergreen.V5.Melee.Ship.Thraddash

        Evergreen.V4.Melee.Ship.Umgah ->
            Evergreen.V5.Melee.Ship.Umgah

        Evergreen.V4.Melee.Ship.UrQuan ->
            Evergreen.V5.Melee.Ship.UrQuan

        Evergreen.V4.Melee.Ship.Utwig ->
            Evergreen.V5.Melee.Ship.Utwig

        Evergreen.V4.Melee.Ship.Vux ->
            Evergreen.V5.Melee.Ship.Vux

        Evergreen.V4.Melee.Ship.Yehat ->
            Evergreen.V5.Melee.Ship.Yehat

        Evergreen.V4.Melee.Ship.ZoqFotPik ->
            Evergreen.V5.Melee.Ship.ZoqFotPik


migrate_Melee_Stream_Delta : Evergreen.V4.Melee.Stream.Delta -> Evergreen.V5.Melee.Stream.Delta
migrate_Melee_Stream_Delta old =
    { stage = old.stage |> migrate_Melee_Stream_Stage
    , frame = old.frame |> migrate_Melee_Units_FrameCount
    , combatants = old.combatants |> migrate_Melee_Units_Sided migrate_Melee_ShipState_Combatant
    , changed = old.changed |> List.map migrate_Melee_Element_Element
    , removed = old.removed
    , queue = old.queue |> List.map migrate_Melee_Id_ElementId
    , sounds = old.sounds
    , interval = old.interval
    }


migrate_Melee_Stream_Stage : Evergreen.V4.Melee.Stream.Stage -> Evergreen.V5.Melee.Stream.Stage
migrate_Melee_Stream_Stage old =
    case old of
        Evergreen.V4.Melee.Stream.Fighting ->
            Evergreen.V5.Melee.Stream.Fighting

        Evergreen.V4.Melee.Stream.Arriving p0 ->
            Evergreen.V5.Melee.Stream.Arriving p0

        Evergreen.V4.Melee.Stream.Stopped ->
            Evergreen.V5.Melee.Stream.Stopped

        Evergreen.V4.Melee.Stream.Aftermath p0 ->
            Evergreen.V5.Melee.Stream.Aftermath p0


migrate_Melee_Units_Angle : Evergreen.V4.Melee.Units.Angle -> Evergreen.V5.Melee.Units.Angle
migrate_Melee_Units_Angle old =
    case old of
        Evergreen.V4.Melee.Units.Angle p0 ->
            Evergreen.V5.Melee.Units.Angle p0


migrate_Melee_Units_Facing : Evergreen.V4.Melee.Units.Facing -> Evergreen.V5.Melee.Units.Facing
migrate_Melee_Units_Facing old =
    case old of
        Evergreen.V4.Melee.Units.Facing p0 ->
            Evergreen.V5.Melee.Units.Facing p0


migrate_Melee_Units_FrameCount : Evergreen.V4.Melee.Units.FrameCount -> Evergreen.V5.Melee.Units.FrameCount
migrate_Melee_Units_FrameCount old =
    case old of
        Evergreen.V4.Melee.Units.FrameCount p0 ->
            Evergreen.V5.Melee.Units.FrameCount p0


migrate_Melee_Units_Side : Evergreen.V4.Melee.Units.Side -> Evergreen.V5.Melee.Units.Side
migrate_Melee_Units_Side old =
    case old of
        Evergreen.V4.Melee.Units.Bottom ->
            Evergreen.V5.Melee.Units.Bottom

        Evergreen.V4.Melee.Units.Top ->
            Evergreen.V5.Melee.Units.Top


migrate_Melee_Units_Sided : (a_old -> a_new) -> Evergreen.V4.Melee.Units.Sided a_old -> Evergreen.V5.Melee.Units.Sided a_new
migrate_Melee_Units_Sided migrate_a old =
    { bottom = old.bottom |> migrate_a
    , top = old.top |> migrate_a
    }


migrate_Melee_Units_VelocityDesc : Evergreen.V4.Melee.Units.VelocityDesc -> Evergreen.V5.Melee.Units.VelocityDesc
migrate_Melee_Units_VelocityDesc old =
    { travelAngle = old.travelAngle |> migrate_Melee_Units_Angle
    , vector = old.vector |> migrate_Melee_Units_WorldExtent
    , fract = old.fract |> migrate_Melee_Units_WorldExtent
    , error = old.error |> migrate_Melee_Units_WorldExtent
    , incr = old.incr |> migrate_Melee_Units_WorldExtent
    }


migrate_Melee_Units_Wait : Evergreen.V4.Melee.Units.Wait -> Evergreen.V5.Melee.Units.Wait
migrate_Melee_Units_Wait old =
    case old of
        Evergreen.V4.Melee.Units.Wait p0 ->
            Evergreen.V5.Melee.Units.Wait p0


migrate_Melee_Units_WorldExtent : Evergreen.V4.Melee.Units.WorldExtent -> Evergreen.V5.Melee.Units.WorldExtent
migrate_Melee_Units_WorldExtent old =
    old


migrate_Melee_Units_WorldPoint : Evergreen.V4.Melee.Units.WorldPoint -> Evergreen.V5.Melee.Units.WorldPoint
migrate_Melee_Units_WorldPoint old =
    old


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V4.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V5.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V4.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V5.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V4.OAuth.ErrorCode -> Evergreen.V5.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V4.OAuth.InvalidRequest ->
            Evergreen.V5.OAuth.InvalidRequest

        Evergreen.V4.OAuth.UnauthorizedClient ->
            Evergreen.V5.OAuth.UnauthorizedClient

        Evergreen.V4.OAuth.AccessDenied ->
            Evergreen.V5.OAuth.AccessDenied

        Evergreen.V4.OAuth.UnsupportedResponseType ->
            Evergreen.V5.OAuth.UnsupportedResponseType

        Evergreen.V4.OAuth.InvalidScope ->
            Evergreen.V5.OAuth.InvalidScope

        Evergreen.V4.OAuth.ServerError ->
            Evergreen.V5.OAuth.ServerError

        Evergreen.V4.OAuth.TemporarilyUnavailable ->
            Evergreen.V5.OAuth.TemporarilyUnavailable

        Evergreen.V4.OAuth.Custom p0 ->
            Evergreen.V5.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V4.OAuth.Token -> Evergreen.V5.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V4.OAuth.Bearer p0 ->
            Evergreen.V5.OAuth.Bearer p0


migrate_Types_AdminLogsUrlParams : Evergreen.V4.Types.AdminLogsUrlParams -> Evergreen.V5.Types.AdminLogsUrlParams
migrate_Types_AdminLogsUrlParams old =
    old


migrate_Types_AdminPageModel : Evergreen.V4.Types.AdminPageModel -> Evergreen.V5.Types.AdminPageModel
migrate_Types_AdminPageModel old =
    { logs = old.logs |> List.map migrate_Logger_LogEntry
    , isAuthenticated = old.isAuthenticated
    , remoteUrl = old.remoteUrl
    }


migrate_Types_AdminRoute : Evergreen.V4.Types.AdminRoute -> Evergreen.V5.Types.AdminRoute
migrate_Types_AdminRoute old =
    case old of
        Evergreen.V4.Types.AdminDefault ->
            Evergreen.V5.Types.AdminDefault

        Evergreen.V4.Types.AdminLogs p0 ->
            Evergreen.V5.Types.AdminLogs (p0 |> migrate_Types_AdminLogsUrlParams)

        Evergreen.V4.Types.AdminFetchModel ->
            Evergreen.V5.Types.AdminFetchModel


migrate_Types_BackendMsg : Evergreen.V4.Types.BackendMsg -> Evergreen.V5.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V4.Types.NoOpBackendMsg ->
            Evergreen.V5.Types.NoOpBackendMsg

        Evergreen.V4.Types.MeleeTick p0 ->
            Evergreen.V5.Types.MeleeTick p0

        Evergreen.V4.Types.MeleeConnected p0 p1 ->
            Evergreen.V5.Types.MeleeConnected p0 p1

        Evergreen.V4.Types.MeleeDisconnected p0 p1 ->
            Evergreen.V5.Types.MeleeDisconnected p0 p1

        Evergreen.V4.Types.GotLogTime p0 ->
            Evergreen.V5.Types.GotLogTime (p0 |> migrate_Logger_Msg)

        Evergreen.V4.Types.GotRemoteModel p0 ->
            Evergreen.V5.Types.GotRemoteModel (p0 |> Result.map migrate_Types_BackendModel)

        Evergreen.V4.Types.AuthBackendMsg p0 ->
            Evergreen.V5.Types.AuthBackendMsg (p0 |> migrate_Auth_Common_BackendMsg)

        Evergreen.V4.Types.EmailPasswordAuthResult p0 ->
            Evergreen.V5.Types.EmailPasswordAuthResult (p0 |> migrate_Types_EmailPasswordAuthResult)

        Evergreen.V4.Types.GotJobTime p0 p1 ->
            Evergreen.V5.Types.GotJobTime p0 p1

        Evergreen.V4.Types.GotCryptoPriceResult p0 p1 ->
            Evergreen.V5.Types.GotCryptoPriceResult p0 p1

        Evergreen.V4.Types.StoreTaskResult p0 p1 ->
            Evergreen.V5.Types.StoreTaskResult p0 p1


migrate_Types_EmailPasswordAuthMsg : Evergreen.V4.Types.EmailPasswordAuthMsg -> Evergreen.V5.Types.EmailPasswordAuthMsg
migrate_Types_EmailPasswordAuthMsg old =
    case old of
        Evergreen.V4.Types.EmailPasswordFormMsg p0 ->
            Evergreen.V5.Types.EmailPasswordFormMsg (p0 |> migrate_Types_EmailPasswordFormMsg)

        Evergreen.V4.Types.EmailPasswordLoginRequested p0 p1 ->
            Evergreen.V5.Types.EmailPasswordLoginRequested p0 p1

        Evergreen.V4.Types.EmailPasswordSignupRequested p0 p1 p2 ->
            Evergreen.V5.Types.EmailPasswordSignupRequested p0 p1 p2


migrate_Types_EmailPasswordAuthResult : Evergreen.V4.Types.EmailPasswordAuthResult -> Evergreen.V5.Types.EmailPasswordAuthResult
migrate_Types_EmailPasswordAuthResult old =
    case old of
        Evergreen.V4.Types.EmailPasswordSignupWithHash p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V5.Types.EmailPasswordSignupWithHash p0 p1 p2 p3 p4 p5 p6


migrate_Types_EmailPasswordAuthToBackend : Evergreen.V4.Types.EmailPasswordAuthToBackend -> Evergreen.V5.Types.EmailPasswordAuthToBackend
migrate_Types_EmailPasswordAuthToBackend old =
    case old of
        Evergreen.V4.Types.EmailPasswordLoginToBackend p0 p1 ->
            Evergreen.V5.Types.EmailPasswordLoginToBackend p0 p1

        Evergreen.V4.Types.EmailPasswordSignupToBackend p0 p1 p2 ->
            Evergreen.V5.Types.EmailPasswordSignupToBackend p0 p1 p2


migrate_Types_EmailPasswordFormModel : Evergreen.V4.Types.EmailPasswordFormModel -> Evergreen.V5.Types.EmailPasswordFormModel
migrate_Types_EmailPasswordFormModel old =
    old


migrate_Types_EmailPasswordFormMsg : Evergreen.V4.Types.EmailPasswordFormMsg -> Evergreen.V5.Types.EmailPasswordFormMsg
migrate_Types_EmailPasswordFormMsg old =
    case old of
        Evergreen.V4.Types.EmailPasswordFormEmailChanged p0 ->
            Evergreen.V5.Types.EmailPasswordFormEmailChanged p0

        Evergreen.V4.Types.EmailPasswordFormPasswordChanged p0 ->
            Evergreen.V5.Types.EmailPasswordFormPasswordChanged p0

        Evergreen.V4.Types.EmailPasswordFormConfirmPasswordChanged p0 ->
            Evergreen.V5.Types.EmailPasswordFormConfirmPasswordChanged p0

        Evergreen.V4.Types.EmailPasswordFormNameChanged p0 ->
            Evergreen.V5.Types.EmailPasswordFormNameChanged p0

        Evergreen.V4.Types.EmailPasswordFormToggleMode ->
            Evergreen.V5.Types.EmailPasswordFormToggleMode

        Evergreen.V4.Types.EmailPasswordFormSubmit ->
            Evergreen.V5.Types.EmailPasswordFormSubmit


migrate_Types_FrontendMsg : Evergreen.V4.Types.FrontendMsg -> Evergreen.V5.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V4.Types.UrlClicked p0 ->
            Evergreen.V5.Types.UrlClicked p0

        Evergreen.V4.Types.UrlChanged p0 ->
            Evergreen.V5.Types.UrlChanged p0

        Evergreen.V4.Types.UrlRequested p0 ->
            Evergreen.V5.Types.UrlRequested p0

        Evergreen.V4.Types.NoOpFrontendMsg ->
            Evergreen.V5.Types.NoOpFrontendMsg

        Evergreen.V4.Types.DirectToBackend p0 ->
            Evergreen.V5.Types.DirectToBackend (p0 |> migrate_Types_ToBackend)

        Evergreen.V4.Types.Admin_RemoteUrlChanged p0 ->
            Evergreen.V5.Types.Admin_RemoteUrlChanged p0

        Evergreen.V4.Types.Admin_LogsNavigate p0 ->
            Evergreen.V5.Types.Admin_LogsNavigate (p0 |> migrate_Types_AdminLogsUrlParams)

        Evergreen.V4.Types.Auth0SigninRequested ->
            Evergreen.V5.Types.Auth0SigninRequested

        Evergreen.V4.Types.EmailPasswordAuthMsg p0 ->
            Evergreen.V5.Types.EmailPasswordAuthMsg (p0 |> migrate_Types_EmailPasswordAuthMsg)

        Evergreen.V4.Types.Logout ->
            Evergreen.V5.Types.Logout

        Evergreen.V4.Types.ToggleDarkMode ->
            Evergreen.V5.Types.ToggleDarkMode

        Evergreen.V4.Types.ToggleProfileDropdown ->
            Evergreen.V5.Types.ToggleProfileDropdown

        Evergreen.V4.Types.ToggleLoginModal ->
            Evergreen.V5.Types.ToggleLoginModal

        Evergreen.V4.Types.CloseLoginModal ->
            Evergreen.V5.Types.CloseLoginModal

        Evergreen.V4.Types.EmailPasswordAuthError p0 ->
            Evergreen.V5.Types.EmailPasswordAuthError p0

        Evergreen.V4.Types.ConsoleLogClicked ->
            Evergreen.V5.Types.ConsoleLogClicked

        Evergreen.V4.Types.ConsoleLogReceived p0 ->
            Evergreen.V5.Types.ConsoleLogReceived p0

        Evergreen.V4.Types.CopyToClipboard p0 ->
            Evergreen.V5.Types.CopyToClipboard p0

        Evergreen.V4.Types.ClipboardResult p0 ->
            Evergreen.V5.Types.ClipboardResult p0

        Evergreen.V4.Types.MeleeLocal p0 ->
            Evergreen.V5.Types.MeleeLocal (p0 |> migrate_Melee_Room_LocalMsg)

        Evergreen.V4.Types.GameMsg p0 ->
            Evergreen.V5.Types.GameMsg (p0 |> migrate_Melee_Local_Msg)

        Evergreen.V4.Types.MeleeFrame p0 ->
            Evergreen.V5.Types.MeleeFrame p0

        Evergreen.V4.Types.Online p0 ->
            Evergreen.V5.Types.Online (p0 |> migrate_Melee_Room_ToHost)

        Evergreen.V4.Types.RoomCodeChanged p0 ->
            Evergreen.V5.Types.RoomCodeChanged p0

        Evergreen.V4.Types.ShowLocalGame p0 ->
            Evergreen.V5.Types.ShowLocalGame p0

        Evergreen.V4.Types.NavigateMelee p0 ->
            Evergreen.V5.Types.NavigateMelee (p0 |> migrate_Melee_Location_Location)

        Evergreen.V4.Types.PlayerNameChanged p0 ->
            Evergreen.V5.Types.PlayerNameChanged p0

        Evergreen.V4.Types.MeleeBrowser p0 ->
            Evergreen.V5.Types.MeleeBrowser (p0 |> migrate_Melee_Menu_Event)

        Evergreen.V4.Types.MeleeClock p0 ->
            Evergreen.V5.Types.MeleeClock p0

        Evergreen.V4.Types.MeleeVisibility p0 ->
            Evergreen.V5.Types.MeleeVisibility p0

        Evergreen.V4.Types.SaveFleets ->
            Evergreen.V5.Types.SaveFleets

        Evergreen.V4.Types.LoadFleets ->
            Evergreen.V5.Types.LoadFleets

        Evergreen.V4.Types.FleetFileSelected p0 ->
            Evergreen.V5.Types.FleetFileSelected p0

        Evergreen.V4.Types.FleetFileLoaded p0 ->
            Evergreen.V5.Types.FleetFileLoaded p0


migrate_Types_LoginState : Evergreen.V4.Types.LoginState -> Evergreen.V5.Types.LoginState
migrate_Types_LoginState old =
    case old of
        Evergreen.V4.Types.JustArrived ->
            Evergreen.V5.Types.JustArrived

        Evergreen.V4.Types.NotLogged p0 ->
            Evergreen.V5.Types.NotLogged p0

        Evergreen.V4.Types.LoginTokenSent ->
            Evergreen.V5.Types.LoginTokenSent

        Evergreen.V4.Types.LoggedIn p0 ->
            Evergreen.V5.Types.LoggedIn (p0 |> migrate_Auth_Common_UserInfo)


migrate_Types_PollingStatus : (a_old -> a_new) -> Evergreen.V4.Types.PollingStatus a_old -> Evergreen.V5.Types.PollingStatus a_new
migrate_Types_PollingStatus migrate_a old =
    case old of
        Evergreen.V4.Types.Busy ->
            Evergreen.V5.Types.Busy

        Evergreen.V4.Types.BusyWithTime p0 ->
            Evergreen.V5.Types.BusyWithTime p0

        Evergreen.V4.Types.Ready p0 ->
            Evergreen.V5.Types.Ready (p0 |> Result.map migrate_a)


migrate_Types_Preferences : Evergreen.V4.Types.Preferences -> Evergreen.V5.Types.Preferences
migrate_Types_Preferences old =
    old


migrate_Types_Route : Evergreen.V4.Types.Route -> Evergreen.V5.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V4.Types.Default ->
            Evergreen.V5.Types.Default

        Evergreen.V4.Types.Admin p0 ->
            Evergreen.V5.Types.Admin (p0 |> migrate_Types_AdminRoute)

        Evergreen.V4.Types.Examples ->
            Evergreen.V5.Types.Examples

        Evergreen.V4.Types.Melee ->
            Evergreen.V5.Types.Melee

        Evergreen.V4.Types.NotFound ->
            Evergreen.V5.Types.NotFound


migrate_Types_ToBackend : Evergreen.V4.Types.ToBackend -> Evergreen.V5.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V4.Types.A p0 ->
            Evergreen.V5.Types.A p0

        Evergreen.V4.Types.Admin_ClearLogs ->
            Evergreen.V5.Types.Admin_ClearLogs

        Evergreen.V4.Types.Admin_FetchLogs p0 ->
            Evergreen.V5.Types.Admin_FetchLogs p0

        Evergreen.V4.Types.Admin_FetchRemoteModel p0 ->
            Evergreen.V5.Types.Admin_FetchRemoteModel p0

        Evergreen.V4.Types.AuthToBackend p0 ->
            Evergreen.V5.Types.AuthToBackend (p0 |> migrate_Auth_Common_ToBackend)

        Evergreen.V4.Types.EmailPasswordAuthToBackend p0 ->
            Evergreen.V5.Types.EmailPasswordAuthToBackend (p0 |> migrate_Types_EmailPasswordAuthToBackend)

        Evergreen.V4.Types.GetUserToBackend ->
            Evergreen.V5.Types.GetUserToBackend

        Evergreen.V4.Types.LoggedOut ->
            Evergreen.V5.Types.LoggedOut

        Evergreen.V4.Types.NoOpToBackend ->
            Evergreen.V5.Types.NoOpToBackend

        Evergreen.V4.Types.SetDarkModePreference p0 ->
            Evergreen.V5.Types.SetDarkModePreference p0

        Evergreen.V4.Types.MeleeToBackend p0 ->
            Evergreen.V5.Types.MeleeToBackend (p0 |> migrate_Melee_Room_ToHost)


migrate_Types_ToFrontend : Evergreen.V4.Types.ToFrontend -> Evergreen.V5.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V4.Types.A0 p0 ->
            Evergreen.V5.Types.A0 p0

        Evergreen.V4.Types.Admin_Logs_ToFrontend p0 ->
            Evergreen.V5.Types.Admin_Logs_ToFrontend (p0 |> List.map migrate_Logger_LogEntry)

        Evergreen.V4.Types.AuthSuccess p0 ->
            Evergreen.V5.Types.AuthSuccess (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V4.Types.AuthToFrontend p0 ->
            Evergreen.V5.Types.AuthToFrontend (p0 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V4.Types.NoOpToFrontend ->
            Evergreen.V5.Types.NoOpToFrontend

        Evergreen.V4.Types.PermissionDenied p0 ->
            Evergreen.V5.Types.PermissionDenied (p0 |> migrate_Types_ToBackend)

        Evergreen.V4.Types.UserDataToFrontend p0 ->
            Evergreen.V5.Types.UserDataToFrontend (p0 |> migrate_Types_UserFrontend)

        Evergreen.V4.Types.UserInfoMsg p0 ->
            Evergreen.V5.Types.UserInfoMsg p0

        Evergreen.V4.Types.MeleeToFrontend p0 ->
            Evergreen.V5.Types.MeleeToFrontend (p0 |> migrate_Melee_Room_ToSeat)


migrate_Types_UserFrontend : Evergreen.V4.Types.UserFrontend -> Evergreen.V5.Types.UserFrontend
migrate_Types_UserFrontend old =
    { email = old.email
    , isSysAdmin = old.isSysAdmin
    , role = old.role
    , preferences = old.preferences |> migrate_Types_Preferences
    }
