module Evergreen.Migrate.V6 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V5.Auth.Common
import Evergreen.V5.Logger
import Evergreen.V5.Melee.Battle
import Evergreen.V5.Melee.Element
import Evergreen.V5.Melee.Graphics
import Evergreen.V5.Melee.Id
import Evergreen.V5.Melee.Input
import Evergreen.V5.Melee.Keys
import Evergreen.V5.Melee.Local
import Evergreen.V5.Melee.Location
import Evergreen.V5.Melee.Projectile
import Evergreen.V5.Melee.Ranking
import Evergreen.V5.Melee.Rng
import Evergreen.V5.Melee.Room
import Evergreen.V5.Melee.Ship
import Evergreen.V5.Melee.ShipState
import Evergreen.V5.Melee.Telemetry
import Evergreen.V5.Melee.Units
import Evergreen.V5.OAuth
import Evergreen.V5.OAuth.AuthorizationCode
import Evergreen.V5.Types
import Evergreen.V6.Auth.Common
import Evergreen.V6.Logger
import Evergreen.V6.Melee.Battle
import Evergreen.V6.Melee.Element
import Evergreen.V6.Melee.Graphics
import Evergreen.V6.Melee.Id
import Evergreen.V6.Melee.Input
import Evergreen.V6.Melee.Keys
import Evergreen.V6.Melee.Local
import Evergreen.V6.Melee.Location
import Evergreen.V6.Melee.Projectile
import Evergreen.V6.Melee.Ranking
import Evergreen.V6.Melee.Rng
import Evergreen.V6.Melee.Room
import Evergreen.V6.Melee.Ship
import Evergreen.V6.Melee.ShipState
import Evergreen.V6.Melee.Telemetry
import Evergreen.V6.Melee.Units
import Evergreen.V6.OAuth
import Evergreen.V6.OAuth.AuthorizationCode
import Evergreen.V6.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V5.Types.FrontendModel -> ModelMigration Evergreen.V6.Types.FrontendModel Evergreen.V6.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V5.Types.BackendModel -> ModelMigration Evergreen.V6.Types.BackendModel Evergreen.V6.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V5.Types.FrontendMsg -> MsgMigration Evergreen.V6.Types.FrontendMsg Evergreen.V6.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V5.Types.ToBackend -> MsgMigration Evergreen.V6.Types.ToBackend Evergreen.V6.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V5.Types.BackendMsg -> MsgMigration Evergreen.V6.Types.BackendMsg Evergreen.V6.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V5.Types.ToFrontend -> MsgMigration Evergreen.V6.Types.ToFrontend Evergreen.V6.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V5.Types.FrontendModel -> Evergreen.V6.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentRoute = old.currentRoute |> migrate_Types_Route
    , adminPage = old.adminPage |> migrate_Types_AdminPageModel
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    , login = old.login |> migrate_Types_LoginState
    , currentUser = old.currentUser
    , pendingAuth = old.pendingAuth
    , preferences = old.preferences |> migrate_Types_Preferences
    , emailPasswordForm = old.emailPasswordForm |> migrate_Types_EmailPasswordFormModel
    , profileDropdownOpen = old.profileDropdownOpen
    , loginModalOpen = old.loginModalOpen
    , melee = old.melee |> migrate_Melee_Room_Client
    , player = old.player
    , playerName = old.playerName
    , searching = old.searching
    , meleeVisible = old.meleeVisible
    , telemetry = old.telemetry |> migrate_Melee_Telemetry_Client
    , telemetryReply = old.telemetryReply
    , meleeNow = old.meleeNow
    , creatingRoom = old.creatingRoom
    , location = old.location |> migrate_Melee_Location_Location
    , arenaPreview = old.arenaPreview |> Maybe.map migrate_Melee_Local_Model
    , showLocalGame = old.showLocalGame
    , watchableGames = old.watchableGames
    , availableRooms = old.availableRooms |> Maybe.map (List.map migrate_Melee_Room_Listing)
    , roomCode = old.roomCode
    , meleeHeld = old.meleeHeld |> migrate_Melee_Keys_Held
    , game = old.game |> migrate_Melee_Local_Model
    , pickCell = { bottom = { row = 0, col = 7 }, top = { row = 0, col = 7 } }
    }


migrate_Auth_Common_Error : Evergreen.V5.Auth.Common.Error -> Evergreen.V6.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V5.Auth.Common.ErrStateMismatch ->
            Evergreen.V6.Auth.Common.ErrStateMismatch

        Evergreen.V5.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V6.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V5.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V6.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V5.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V6.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V5.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V6.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V5.Auth.Common.ErrAuthString p0 ->
            Evergreen.V6.Auth.Common.ErrAuthString p0


migrate_Auth_Common_Flow : Evergreen.V5.Auth.Common.Flow -> Evergreen.V6.Auth.Common.Flow
migrate_Auth_Common_Flow old =
    case old of
        Evergreen.V5.Auth.Common.Idle ->
            Evergreen.V6.Auth.Common.Idle

        Evergreen.V5.Auth.Common.Requested p0 ->
            Evergreen.V6.Auth.Common.Requested p0

        Evergreen.V5.Auth.Common.Pending ->
            Evergreen.V6.Auth.Common.Pending

        Evergreen.V5.Auth.Common.Authorized p0 p1 ->
            Evergreen.V6.Auth.Common.Authorized p0 p1

        Evergreen.V5.Auth.Common.Authenticated p0 ->
            Evergreen.V6.Auth.Common.Authenticated (p0 |> migrate_OAuth_Token)

        Evergreen.V5.Auth.Common.Done p0 ->
            Evergreen.V6.Auth.Common.Done (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V5.Auth.Common.Errored p0 ->
            Evergreen.V6.Auth.Common.Errored (p0 |> migrate_Auth_Common_Error)


migrate_Auth_Common_UserInfo : Evergreen.V5.Auth.Common.UserInfo -> Evergreen.V6.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Logger_LogEntry : Evergreen.V5.Logger.LogEntry -> Evergreen.V6.Logger.LogEntry
migrate_Logger_LogEntry old =
    { index = old.index
    , timestamp = old.timestamp
    , level = old.level |> migrate_Logger_LogLevel
    , message = old.message
    }


migrate_Logger_LogLevel : Evergreen.V5.Logger.LogLevel -> Evergreen.V6.Logger.LogLevel
migrate_Logger_LogLevel old =
    case old of
        Evergreen.V5.Logger.Debug ->
            Evergreen.V6.Logger.Debug

        Evergreen.V5.Logger.Info ->
            Evergreen.V6.Logger.Info

        Evergreen.V5.Logger.Warn ->
            Evergreen.V6.Logger.Warn

        Evergreen.V5.Logger.Error ->
            Evergreen.V6.Logger.Error


migrate_Melee_Battle_Arena : Evergreen.V5.Melee.Battle.Arena -> Evergreen.V6.Melee.Battle.Arena
migrate_Melee_Battle_Arena old =
    { frame = old.frame |> migrate_Melee_Units_FrameCount
    , previousLocations = old.previousLocations
    , pumpAcc = old.pumpAcc
    , seed = old.seed |> migrate_Melee_Rng_Seed
    , space = old.space |> migrate_Melee_Units_WorldExtent
    , combatants = old.combatants |> migrate_Melee_Units_Sided migrate_Melee_ShipState_Combatant
    , elements = old.elements |> Dict.map (\k -> migrate_Melee_Element_Element)
    , queue = old.queue |> List.map migrate_Melee_Id_ElementId
    , nextElementId = old.nextElementId
    }


migrate_Melee_Element_Body : Evergreen.V5.Melee.Element.Body -> Evergreen.V6.Melee.Element.Body
migrate_Melee_Element_Body old =
    case old of
        Evergreen.V5.Melee.Element.ShipBody p0 ->
            Evergreen.V6.Melee.Element.ShipBody (p0 |> migrate_Melee_Units_Side)

        Evergreen.V5.Melee.Element.WreckBody p0 ->
            Evergreen.V6.Melee.Element.WreckBody (p0 |> migrate_Melee_Units_Side)

        Evergreen.V5.Melee.Element.PlanetBody ->
            Evergreen.V6.Melee.Element.PlanetBody

        Evergreen.V5.Melee.Element.AsteroidBody ->
            Evergreen.V6.Melee.Element.AsteroidBody

        Evergreen.V5.Melee.Element.CrewBody p0 ->
            Evergreen.V6.Melee.Element.CrewBody
                { origin = p0.origin |> migrate_Melee_Units_Side
                }

        Evergreen.V5.Melee.Element.WeaponImpact p0 ->
            Evergreen.V6.Melee.Element.WeaponImpact (p0 |> migrate_Melee_Projectile_MissileKind)

        Evergreen.V5.Melee.Element.BlastBody ->
            Evergreen.V6.Melee.Element.BlastBody

        Evergreen.V5.Melee.Element.ExplosionBody ->
            Evergreen.V6.Melee.Element.ExplosionBody

        Evergreen.V5.Melee.Element.WarpInBody ->
            Evergreen.V6.Melee.Element.WarpInBody

        Evergreen.V5.Melee.Element.IonTrailBody ->
            Evergreen.V6.Melee.Element.IonTrailBody

        Evergreen.V5.Melee.Element.AndrosynthBubble ->
            Evergreen.V6.Melee.Element.AndrosynthBubble

        Evergreen.V5.Melee.Element.ArilouLaser ->
            Evergreen.V6.Melee.Element.ArilouLaser

        Evergreen.V5.Melee.Element.ChenjesuPhoton ->
            Evergreen.V6.Melee.Element.ChenjesuPhoton

        Evergreen.V5.Melee.Element.ChenjesuFragment ->
            Evergreen.V6.Melee.Element.ChenjesuFragment

        Evergreen.V5.Melee.Element.ChenjesuDogi ->
            Evergreen.V6.Melee.Element.ChenjesuDogi

        Evergreen.V5.Melee.Element.ChmmrLaser ->
            Evergreen.V6.Melee.Element.ChmmrLaser

        Evergreen.V5.Melee.Element.ChmmrSatellite p0 ->
            Evergreen.V6.Melee.Element.ChmmrSatellite
                { orbitFacing = p0.orbitFacing |> migrate_Melee_Units_Facing
                }

        Evergreen.V5.Melee.Element.ChmmrZap ->
            Evergreen.V6.Melee.Element.ChmmrZap

        Evergreen.V5.Melee.Element.DruugeHotShot ->
            Evergreen.V6.Melee.Element.DruugeHotShot

        Evergreen.V5.Melee.Element.EarthlingNuke ->
            Evergreen.V6.Melee.Element.EarthlingNuke

        Evergreen.V5.Melee.Element.EarthlingPointDefense ->
            Evergreen.V6.Melee.Element.EarthlingPointDefense

        Evergreen.V5.Melee.Element.IlwrathFlame ->
            Evergreen.V6.Melee.Element.IlwrathFlame

        Evergreen.V5.Melee.Element.KohrAhSaw ->
            Evergreen.V6.Melee.Element.KohrAhSaw

        Evergreen.V5.Melee.Element.KohrAhFried ->
            Evergreen.V6.Melee.Element.KohrAhFried

        Evergreen.V5.Melee.Element.MelnormeCharge ->
            Evergreen.V6.Melee.Element.MelnormeCharge

        Evergreen.V5.Melee.Element.MelnormeConfusion ->
            Evergreen.V6.Melee.Element.MelnormeConfusion

        Evergreen.V5.Melee.Element.MmrnmhrmLaser ->
            Evergreen.V6.Melee.Element.MmrnmhrmLaser

        Evergreen.V5.Melee.Element.MmrnmhrmMissile ->
            Evergreen.V6.Melee.Element.MmrnmhrmMissile

        Evergreen.V5.Melee.Element.MyconPlasma ->
            Evergreen.V6.Melee.Element.MyconPlasma

        Evergreen.V5.Melee.Element.OrzHowitzer ->
            Evergreen.V6.Melee.Element.OrzHowitzer

        Evergreen.V5.Melee.Element.OrzMarine ->
            Evergreen.V6.Melee.Element.OrzMarine

        Evergreen.V5.Melee.Element.PkunkSpread ->
            Evergreen.V6.Melee.Element.PkunkSpread

        Evergreen.V5.Melee.Element.ShofixtiDart ->
            Evergreen.V6.Melee.Element.ShofixtiDart

        Evergreen.V5.Melee.Element.ShofixtiGlory ->
            Evergreen.V6.Melee.Element.ShofixtiGlory

        Evergreen.V5.Melee.Element.SlylandroLightning ->
            Evergreen.V6.Melee.Element.SlylandroLightning

        Evergreen.V5.Melee.Element.SpathiForward ->
            Evergreen.V6.Melee.Element.SpathiForward

        Evergreen.V5.Melee.Element.SpathiButt ->
            Evergreen.V6.Melee.Element.SpathiButt

        Evergreen.V5.Melee.Element.SupoxPellet ->
            Evergreen.V6.Melee.Element.SupoxPellet

        Evergreen.V5.Melee.Element.SyreenMissile ->
            Evergreen.V6.Melee.Element.SyreenMissile

        Evergreen.V5.Melee.Element.ThraddashBlaster ->
            Evergreen.V6.Melee.Element.ThraddashBlaster

        Evergreen.V5.Melee.Element.ThraddashAfterburn ->
            Evergreen.V6.Melee.Element.ThraddashAfterburn

        Evergreen.V5.Melee.Element.UmgahCone ->
            Evergreen.V6.Melee.Element.UmgahCone

        Evergreen.V5.Melee.Element.UrQuanFusion ->
            Evergreen.V6.Melee.Element.UrQuanFusion

        Evergreen.V5.Melee.Element.UrQuanFighter ->
            Evergreen.V6.Melee.Element.UrQuanFighter

        Evergreen.V5.Melee.Element.UrQuanFighterLaser ->
            Evergreen.V6.Melee.Element.UrQuanFighterLaser

        Evergreen.V5.Melee.Element.UtwigGizmo ->
            Evergreen.V6.Melee.Element.UtwigGizmo

        Evergreen.V5.Melee.Element.VuxLaser ->
            Evergreen.V6.Melee.Element.VuxLaser

        Evergreen.V5.Melee.Element.VuxLimpet ->
            Evergreen.V6.Melee.Element.VuxLimpet

        Evergreen.V5.Melee.Element.YehatMissile ->
            Evergreen.V6.Melee.Element.YehatMissile

        Evergreen.V5.Melee.Element.ZoqSpit ->
            Evergreen.V6.Melee.Element.ZoqSpit

        Evergreen.V5.Melee.Element.ZoqTongue ->
            Evergreen.V6.Melee.Element.ZoqTongue


migrate_Melee_Element_Element : Evergreen.V5.Melee.Element.Element -> Evergreen.V6.Melee.Element.Element
migrate_Melee_Element_Element old =
    { id = old.id |> migrate_Melee_Id_ElementId
    , owner = old.owner |> migrate_Melee_Element_Owner
    , parent = old.parent |> Maybe.map migrate_Melee_Units_Side
    , target = old.target |> Maybe.map migrate_Melee_Id_ElementId
    , flags = old.flags |> migrate_Melee_Element_ElementFlags
    , life = old.life |> migrate_Melee_Element_Life
    , points = old.points
    , mass = old.mass
    , turnWait = old.turnWait |> migrate_Melee_Units_Wait
    , thrustWait = old.thrustWait |> migrate_Melee_Units_Wait
    , colorCycleIndex = old.colorCycleIndex
    , velocity = old.velocity |> migrate_Melee_Units_VelocityDesc
    , intersect = old.intersect |> migrate_Melee_Element_IntersectControl
    , current = old.current |> migrate_Melee_Element_Image
    , next = old.next |> migrate_Melee_Element_Image
    , prim = old.prim |> migrate_Melee_Element_Prim
    , projectile = old.projectile |> Maybe.map migrate_Melee_Projectile_State
    , body = old.body |> migrate_Melee_Element_Body
    }


migrate_Melee_Element_ElementFlags : Evergreen.V5.Melee.Element.ElementFlags -> Evergreen.V6.Melee.Element.ElementFlags
migrate_Melee_Element_ElementFlags old =
    old


migrate_Melee_Element_Image : Evergreen.V5.Melee.Element.Image -> Evergreen.V6.Melee.Element.Image
migrate_Melee_Element_Image old =
    { location = old.location |> migrate_Melee_Units_WorldPoint
    , frameIndex = old.frameIndex
    }


migrate_Melee_Element_IntersectControl : Evergreen.V5.Melee.Element.IntersectControl -> Evergreen.V6.Melee.Element.IntersectControl
migrate_Melee_Element_IntersectControl old =
    { lastTimeVal = old.lastTimeVal
    , endPoint = old.endPoint |> migrate_Melee_Units_WorldPoint
    , stampOrigin = old.stampOrigin |> migrate_Melee_Units_WorldPoint
    }


migrate_Melee_Element_Life : Evergreen.V5.Melee.Element.Life -> Evergreen.V6.Melee.Element.Life
migrate_Melee_Element_Life old =
    case old of
        Evergreen.V5.Melee.Element.Persistent p0 ->
            Evergreen.V6.Melee.Element.Persistent p0

        Evergreen.V5.Melee.Element.Finite p0 ->
            Evergreen.V6.Melee.Element.Finite p0


migrate_Melee_Element_Owner : Evergreen.V5.Melee.Element.Owner -> Evergreen.V6.Melee.Element.Owner
migrate_Melee_Element_Owner old =
    case old of
        Evergreen.V5.Melee.Element.Neutral ->
            Evergreen.V6.Melee.Element.Neutral

        Evergreen.V5.Melee.Element.Owned p0 ->
            Evergreen.V6.Melee.Element.Owned (p0 |> migrate_Melee_Units_Side)


migrate_Melee_Element_Prim : Evergreen.V5.Melee.Element.Prim -> Evergreen.V6.Melee.Element.Prim
migrate_Melee_Element_Prim old =
    case old of
        Evergreen.V5.Melee.Element.NoPrim ->
            Evergreen.V6.Melee.Element.NoPrim

        Evergreen.V5.Melee.Element.Stamp ->
            Evergreen.V6.Melee.Element.Stamp

        Evergreen.V5.Melee.Element.StampFill p0 ->
            Evergreen.V6.Melee.Element.StampFill p0

        Evergreen.V5.Melee.Element.Line ->
            Evergreen.V6.Melee.Element.Line


migrate_Melee_Graphics_Quality : Evergreen.V5.Melee.Graphics.Quality -> Evergreen.V6.Melee.Graphics.Quality
migrate_Melee_Graphics_Quality old =
    case old of
        Evergreen.V5.Melee.Graphics.Classic ->
            Evergreen.V6.Melee.Graphics.Classic

        Evergreen.V5.Melee.Graphics.HighDefinition ->
            Evergreen.V6.Melee.Graphics.HighDefinition


migrate_Melee_Id_ElementId : Evergreen.V5.Melee.Id.ElementId -> Evergreen.V6.Melee.Id.ElementId
migrate_Melee_Id_ElementId old =
    case old of
        Evergreen.V5.Melee.Id.ElementId p0 ->
            Evergreen.V6.Melee.Id.ElementId p0


migrate_Melee_Input_BattleInput : Evergreen.V5.Melee.Input.BattleInput -> Evergreen.V6.Melee.Input.BattleInput
migrate_Melee_Input_BattleInput old =
    { turn = old.turn |> migrate_Melee_Input_Turn
    , thrust = old.thrust
    , weapon = old.weapon
    , special = old.special
    }


migrate_Melee_Input_CyborgRating : Evergreen.V5.Melee.Input.CyborgRating -> Evergreen.V6.Melee.Input.CyborgRating
migrate_Melee_Input_CyborgRating old =
    case old of
        Evergreen.V5.Melee.Input.StandardCyborg ->
            Evergreen.V6.Melee.Input.StandardCyborg

        Evergreen.V5.Melee.Input.GoodCyborg ->
            Evergreen.V6.Melee.Input.GoodCyborg

        Evergreen.V5.Melee.Input.AwesomeCyborg ->
            Evergreen.V6.Melee.Input.AwesomeCyborg


migrate_Melee_Input_Turn : Evergreen.V5.Melee.Input.Turn -> Evergreen.V6.Melee.Input.Turn
migrate_Melee_Input_Turn old =
    case old of
        Evergreen.V5.Melee.Input.NoTurn ->
            Evergreen.V6.Melee.Input.NoTurn

        Evergreen.V5.Melee.Input.TurnLeft ->
            Evergreen.V6.Melee.Input.TurnLeft

        Evergreen.V5.Melee.Input.TurnRight ->
            Evergreen.V6.Melee.Input.TurnRight


migrate_Melee_Keys_Held : Evergreen.V5.Melee.Keys.Held -> Evergreen.V6.Melee.Keys.Held
migrate_Melee_Keys_Held old =
    old


migrate_Melee_Local_Mode : Evergreen.V5.Melee.Local.Mode -> Evergreen.V6.Melee.Local.Mode
migrate_Melee_Local_Mode old =
    case old of
        Evergreen.V5.Melee.Local.Solo ->
            Evergreen.V6.Melee.Local.Solo

        Evergreen.V5.Melee.Local.Versus ->
            Evergreen.V6.Melee.Local.Versus

        Evergreen.V5.Melee.Local.Demo ->
            Evergreen.V6.Melee.Local.Demo

        Evergreen.V5.Melee.Local.ReverseSolo ->
            Evergreen.V6.Melee.Local.ReverseSolo


migrate_Melee_Local_Model : Evergreen.V5.Melee.Local.Model -> Evergreen.V6.Melee.Local.Model
migrate_Melee_Local_Model old =
    { names = old.names |> migrate_Melee_Units_Sided identity
    , notice = old.notice
    , difficulty = old.difficulty |> migrate_Melee_Input_CyborgRating
    , fleets = old.fleets |> migrate_Melee_Units_Sided (List.map migrate_Melee_Ship_ShipKind)
    , remaining = old.remaining |> migrate_Melee_Units_Sided (List.map migrate_Melee_Ship_ShipKind)
    , mode = old.mode |> migrate_Melee_Local_Mode
    , phase = old.phase |> migrate_Melee_Local_Phase
    , editing = old.editing |> migrate_Melee_Units_Side
    , seed = old.seed |> migrate_Melee_Rng_Seed
    , graphics = old.graphics |> migrate_Melee_Graphics_Quality
    , sound = old.sound
    , sounds = old.sounds
    , clock = old.clock
    , survivor = old.survivor |> Maybe.map migrate_Melee_Battle_Arena
    , zoomWidth = old.zoomWidth
    , presentationStep = old.presentationStep
    , presentationClock = old.presentationClock
    , round = old.round
    }


migrate_Melee_Local_Phase : Evergreen.V5.Melee.Local.Phase -> Evergreen.V6.Melee.Local.Phase
migrate_Melee_Local_Phase old =
    case old of
        Evergreen.V5.Melee.Local.Hangar ->
            Evergreen.V6.Melee.Local.Hangar

        Evergreen.V5.Melee.Local.Selecting p0 p1 ->
            Evergreen.V6.Melee.Local.Selecting (p0 |> Maybe.map migrate_Melee_Ship_ShipKind)
                (p1 |> Maybe.map migrate_Melee_Ship_ShipKind)

        Evergreen.V5.Melee.Local.Countdown p0 p1 ->
            Evergreen.V6.Melee.Local.Countdown p0 (p1 |> migrate_Melee_Battle_Arena)

        Evergreen.V5.Melee.Local.Combat p0 ->
            Evergreen.V6.Melee.Local.Combat (p0 |> migrate_Melee_Battle_Arena)

        Evergreen.V5.Melee.Local.Paused p0 ->
            Evergreen.V6.Melee.Local.Paused (p0 |> migrate_Melee_Battle_Arena)

        Evergreen.V5.Melee.Local.RoundOver p0 p1 ->
            Evergreen.V6.Melee.Local.RoundOver p0 (p1 |> migrate_Melee_Battle_Arena)

        Evergreen.V5.Melee.Local.Victory p0 ->
            Evergreen.V6.Melee.Local.Victory (p0 |> Maybe.map migrate_Melee_Units_Side)


migrate_Melee_Location_Location : Evergreen.V5.Melee.Location.Location -> Evergreen.V6.Melee.Location.Location
migrate_Melee_Location_Location old =
    { room = old.room
    , watching = old.watching
    , local = old.local
    , watchingList = old.watchingList
    , page = old.page
    , roster = old.roster
    , mode = old.mode |> migrate_Melee_Local_Mode
    , difficulty = old.difficulty |> migrate_Melee_Input_CyborgRating
    }


migrate_Melee_Projectile_BeamKind : Evergreen.V5.Melee.Projectile.BeamKind -> Evergreen.V6.Melee.Projectile.BeamKind
migrate_Melee_Projectile_BeamKind old =
    case old of
        Evergreen.V5.Melee.Projectile.AutoAim ->
            Evergreen.V6.Melee.Projectile.AutoAim

        Evergreen.V5.Melee.Projectile.Megawatt ->
            Evergreen.V6.Melee.Projectile.Megawatt

        Evergreen.V5.Melee.Projectile.Twin ->
            Evergreen.V6.Melee.Projectile.Twin

        Evergreen.V5.Melee.Projectile.Green ->
            Evergreen.V6.Melee.Projectile.Green

        Evergreen.V5.Melee.Projectile.PointDefense ->
            Evergreen.V6.Melee.Projectile.PointDefense

        Evergreen.V5.Melee.Projectile.Zap ->
            Evergreen.V6.Melee.Projectile.Zap

        Evergreen.V5.Melee.Projectile.FighterBeam ->
            Evergreen.V6.Melee.Projectile.FighterBeam


migrate_Melee_Projectile_ContactKind : Evergreen.V5.Melee.Projectile.ContactKind -> Evergreen.V6.Melee.Projectile.ContactKind
migrate_Melee_Projectile_ContactKind old =
    case old of
        Evergreen.V5.Melee.Projectile.Cone ->
            Evergreen.V6.Melee.Projectile.Cone

        Evergreen.V5.Melee.Projectile.Tongue ->
            Evergreen.V6.Melee.Projectile.Tongue


migrate_Melee_Projectile_MissileKind : Evergreen.V5.Melee.Projectile.MissileKind -> Evergreen.V6.Melee.Projectile.MissileKind
migrate_Melee_Projectile_MissileKind old =
    case old of
        Evergreen.V5.Melee.Projectile.Bubble ->
            Evergreen.V6.Melee.Projectile.Bubble

        Evergreen.V5.Melee.Projectile.Crystal ->
            Evergreen.V6.Melee.Projectile.Crystal

        Evergreen.V5.Melee.Projectile.Shard ->
            Evergreen.V6.Melee.Projectile.Shard

        Evergreen.V5.Melee.Projectile.Dogi ->
            Evergreen.V6.Melee.Projectile.Dogi

        Evergreen.V5.Melee.Projectile.Cannon ->
            Evergreen.V6.Melee.Projectile.Cannon

        Evergreen.V5.Melee.Projectile.Nuke ->
            Evergreen.V6.Melee.Projectile.Nuke

        Evergreen.V5.Melee.Projectile.Flame ->
            Evergreen.V6.Melee.Projectile.Flame

        Evergreen.V5.Melee.Projectile.Saw ->
            Evergreen.V6.Melee.Projectile.Saw

        Evergreen.V5.Melee.Projectile.Fried ->
            Evergreen.V6.Melee.Projectile.Fried

        Evergreen.V5.Melee.Projectile.Charge ->
            Evergreen.V6.Melee.Projectile.Charge

        Evergreen.V5.Melee.Projectile.Confusion ->
            Evergreen.V6.Melee.Projectile.Confusion

        Evergreen.V5.Melee.Projectile.Torpedo ->
            Evergreen.V6.Melee.Projectile.Torpedo

        Evergreen.V5.Melee.Projectile.Plasma ->
            Evergreen.V6.Melee.Projectile.Plasma

        Evergreen.V5.Melee.Projectile.Howitzer ->
            Evergreen.V6.Melee.Projectile.Howitzer

        Evergreen.V5.Melee.Projectile.Marine ->
            Evergreen.V6.Melee.Projectile.Marine

        Evergreen.V5.Melee.Projectile.Bug ->
            Evergreen.V6.Melee.Projectile.Bug

        Evergreen.V5.Melee.Projectile.Dart ->
            Evergreen.V6.Melee.Projectile.Dart

        Evergreen.V5.Melee.Projectile.SpathiShot ->
            Evergreen.V6.Melee.Projectile.SpathiShot

        Evergreen.V5.Melee.Projectile.Butt ->
            Evergreen.V6.Melee.Projectile.Butt

        Evergreen.V5.Melee.Projectile.Pellet ->
            Evergreen.V6.Melee.Projectile.Pellet

        Evergreen.V5.Melee.Projectile.Dagger ->
            Evergreen.V6.Melee.Projectile.Dagger

        Evergreen.V5.Melee.Projectile.Blaster ->
            Evergreen.V6.Melee.Projectile.Blaster

        Evergreen.V5.Melee.Projectile.Napalm ->
            Evergreen.V6.Melee.Projectile.Napalm

        Evergreen.V5.Melee.Projectile.Fusion ->
            Evergreen.V6.Melee.Projectile.Fusion

        Evergreen.V5.Melee.Projectile.Fighter ->
            Evergreen.V6.Melee.Projectile.Fighter

        Evergreen.V5.Melee.Projectile.Lance ->
            Evergreen.V6.Melee.Projectile.Lance

        Evergreen.V5.Melee.Projectile.Limpet ->
            Evergreen.V6.Melee.Projectile.Limpet

        Evergreen.V5.Melee.Projectile.YehatShot ->
            Evergreen.V6.Melee.Projectile.YehatShot

        Evergreen.V5.Melee.Projectile.Spit ->
            Evergreen.V6.Melee.Projectile.Spit


migrate_Melee_Projectile_State : Evergreen.V5.Melee.Projectile.State -> Evergreen.V6.Melee.Projectile.State
migrate_Melee_Projectile_State old =
    case old of
        Evergreen.V5.Melee.Projectile.Flying p0 p1 ->
            Evergreen.V6.Melee.Projectile.Flying (p0 |> migrate_Melee_Projectile_MissileKind)
                { age = p1.age
                , facing = p1.facing |> migrate_Melee_Units_Facing
                , trackingWait = p1.trackingWait
                }

        Evergreen.V5.Melee.Projectile.Charging p0 ->
            Evergreen.V6.Melee.Projectile.Charging
                { ticks = p0.ticks
                , facing = p0.facing |> migrate_Melee_Units_Facing
                }

        Evergreen.V5.Melee.Projectile.Ray p0 p1 ->
            Evergreen.V6.Melee.Projectile.Ray (p0 |> migrate_Melee_Projectile_BeamKind)
                { origin = p1.origin |> migrate_Melee_Units_WorldPoint
                , end = p1.end |> migrate_Melee_Units_WorldPoint
                }

        Evergreen.V5.Melee.Projectile.Attached p0 p1 ->
            Evergreen.V6.Melee.Projectile.Attached (p0 |> migrate_Melee_Projectile_ContactKind)
                { age = p1.age
                , facing = p1.facing |> migrate_Melee_Units_Facing
                }

        Evergreen.V5.Melee.Projectile.LightningSegment p0 ->
            Evergreen.V6.Melee.Projectile.LightningSegment
                { origin = p0.origin |> migrate_Melee_Units_WorldPoint
                , end = p0.end |> migrate_Melee_Units_WorldPoint
                }


migrate_Melee_Ranking_Outcome : Evergreen.V5.Melee.Ranking.Outcome -> Evergreen.V6.Melee.Ranking.Outcome
migrate_Melee_Ranking_Outcome old =
    case old of
        Evergreen.V5.Melee.Ranking.Cancelled ->
            Evergreen.V6.Melee.Ranking.Cancelled

        Evergreen.V5.Melee.Ranking.Scored p0 ->
            Evergreen.V6.Melee.Ranking.Scored
                { winner = p0.winner |> Maybe.map migrate_Melee_Units_Side
                , changes = p0.changes |> migrate_Melee_Units_Sided identity
                , ratings = p0.ratings |> migrate_Melee_Units_Sided identity
                }


migrate_Melee_Ranking_View : Evergreen.V5.Melee.Ranking.View -> Evergreen.V6.Melee.Ranking.View
migrate_Melee_Ranking_View old =
    { ratings = old.ratings |> migrate_Melee_Units_Sided identity
    , deadline = old.deadline
    , outcome = old.outcome |> Maybe.map migrate_Melee_Ranking_Outcome
    }


migrate_Melee_Rng_Seed : Evergreen.V5.Melee.Rng.Seed -> Evergreen.V6.Melee.Rng.Seed
migrate_Melee_Rng_Seed old =
    case old of
        Evergreen.V5.Melee.Rng.Seed p0 ->
            Evergreen.V6.Melee.Rng.Seed p0


migrate_Melee_Room_Client : Evergreen.V5.Melee.Room.Client -> Evergreen.V6.Melee.Room.Client
migrate_Melee_Room_Client old =
    case old of
        Evergreen.V5.Melee.Room.Browsing ->
            Evergreen.V6.Melee.Room.Browsing

        Evergreen.V5.Melee.Room.Seated p0 ->
            Evergreen.V6.Melee.Room.Seated (p0 |> migrate_Melee_Room_Snapshot)

        Evergreen.V5.Melee.Room.Watching p0 ->
            Evergreen.V6.Melee.Room.Watching (p0 |> migrate_Melee_Room_SpectatorSnapshot)


migrate_Melee_Room_Listing : Evergreen.V5.Melee.Room.Listing -> Evergreen.V6.Melee.Room.Listing
migrate_Melee_Room_Listing old =
    { code = old.code
    , name = old.name
    , ships = old.ships
    , points = old.points
    , fleet = old.fleet |> List.map migrate_Melee_Ship_ShipKind
    }


migrate_Melee_Room_SeatControl : Evergreen.V5.Melee.Room.SeatControl -> Evergreen.V6.Melee.Room.SeatControl
migrate_Melee_Room_SeatControl old =
    case old of
        Evergreen.V5.Melee.Room.Human ->
            Evergreen.V6.Melee.Room.Human

        Evergreen.V5.Melee.Room.Computer ->
            Evergreen.V6.Melee.Room.Computer


migrate_Melee_Room_Snapshot : Evergreen.V5.Melee.Room.Snapshot -> Evergreen.V6.Melee.Room.Snapshot
migrate_Melee_Room_Snapshot old =
    { code = old.code
    , side = old.side |> migrate_Melee_Units_Side
    , game = old.game |> migrate_Melee_Local_Model
    , connected = old.connected |> migrate_Melee_Units_Sided identity
    , controllers = old.controllers |> migrate_Melee_Units_Sided migrate_Melee_Room_SeatControl
    , ready = old.ready |> migrate_Melee_Units_Sided identity
    , revision = old.revision
    , ranked = old.ranked |> Maybe.map migrate_Melee_Ranking_View
    }


migrate_Melee_Room_SpectatorSnapshot : Evergreen.V5.Melee.Room.SpectatorSnapshot -> Evergreen.V6.Melee.Room.SpectatorSnapshot
migrate_Melee_Room_SpectatorSnapshot old =
    { code = old.code
    , game = old.game |> migrate_Melee_Local_Model
    , connected = old.connected |> migrate_Melee_Units_Sided identity
    , controllers = old.controllers |> migrate_Melee_Units_Sided migrate_Melee_Room_SeatControl
    , revision = old.revision
    }


migrate_Melee_ShipState_AndrosynthExtra : Evergreen.V5.Melee.ShipState.AndrosynthExtra -> Evergreen.V6.Melee.ShipState.AndrosynthExtra
migrate_Melee_ShipState_AndrosynthExtra old =
    case old of
        Evergreen.V5.Melee.ShipState.Guardian ->
            Evergreen.V6.Melee.ShipState.Guardian

        Evergreen.V5.Melee.ShipState.Blazer p0 ->
            Evergreen.V6.Melee.ShipState.Blazer
                { guardian = p0.guardian |> migrate_Melee_Ship_Characteristics
                }


migrate_Melee_ShipState_ArilouExtra : Evergreen.V5.Melee.ShipState.ArilouExtra -> Evergreen.V6.Melee.ShipState.ArilouExtra
migrate_Melee_ShipState_ArilouExtra old =
    case old of
        Evergreen.V5.Melee.ShipState.Present ->
            Evergreen.V6.Melee.ShipState.Present

        Evergreen.V5.Melee.ShipState.Teleporting p0 ->
            Evergreen.V6.Melee.ShipState.Teleporting (p0 |> migrate_Melee_Units_Wait)


migrate_Melee_ShipState_ChmmrExtra : Evergreen.V5.Melee.ShipState.ChmmrExtra -> Evergreen.V6.Melee.ShipState.ChmmrExtra
migrate_Melee_ShipState_ChmmrExtra old =
    case old of
        Evergreen.V5.Melee.ShipState.TractorIdle ->
            Evergreen.V6.Melee.ShipState.TractorIdle

        Evergreen.V5.Melee.ShipState.TractorOn ->
            Evergreen.V6.Melee.ShipState.TractorOn


migrate_Melee_ShipState_Combatant : Evergreen.V5.Melee.ShipState.Combatant -> Evergreen.V6.Melee.ShipState.Combatant
migrate_Melee_ShipState_Combatant old =
    case old of
        Evergreen.V5.Melee.ShipState.LiveAndrosynth p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveAndrosynth (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_AndrosynthExtra)

        Evergreen.V5.Melee.ShipState.LiveArilou p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveArilou (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ArilouExtra)

        Evergreen.V5.Melee.ShipState.LiveChenjesu p0 ->
            Evergreen.V6.Melee.ShipState.LiveChenjesu (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveChmmr p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveChmmr (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ChmmrExtra)

        Evergreen.V5.Melee.ShipState.LiveDruuge p0 ->
            Evergreen.V6.Melee.ShipState.LiveDruuge (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveEarthling p0 ->
            Evergreen.V6.Melee.ShipState.LiveEarthling (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveIlwrath p0 ->
            Evergreen.V6.Melee.ShipState.LiveIlwrath (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveKohrAh p0 ->
            Evergreen.V6.Melee.ShipState.LiveKohrAh (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveMelnorme p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveMelnorme (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_MelnormeExtra)

        Evergreen.V5.Melee.ShipState.LiveMmrnmhrm p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveMmrnmhrm (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_MmrnmhrmExtra)

        Evergreen.V5.Melee.ShipState.LiveMycon p0 ->
            Evergreen.V6.Melee.ShipState.LiveMycon (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveOrz p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveOrz (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_OrzExtra)

        Evergreen.V5.Melee.ShipState.LivePkunk p0 p1 ->
            Evergreen.V6.Melee.ShipState.LivePkunk (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_PkunkExtra)

        Evergreen.V5.Melee.ShipState.LiveShofixti p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveShofixti (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ShofixtiExtra)

        Evergreen.V5.Melee.ShipState.LiveSlylandro p0 ->
            Evergreen.V6.Melee.ShipState.LiveSlylandro (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveSpathi p0 ->
            Evergreen.V6.Melee.ShipState.LiveSpathi (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveSupox p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveSupox (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_SupoxExtra)

        Evergreen.V5.Melee.ShipState.LiveSyreen p0 ->
            Evergreen.V6.Melee.ShipState.LiveSyreen (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveThraddash p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveThraddash (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_ThraddashExtra)

        Evergreen.V5.Melee.ShipState.LiveUmgah p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveUmgah (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_UmgahExtra)

        Evergreen.V5.Melee.ShipState.LiveUrQuan p0 ->
            Evergreen.V6.Melee.ShipState.LiveUrQuan (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveUtwig p0 ->
            Evergreen.V6.Melee.ShipState.LiveUtwig (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveVux p0 p1 ->
            Evergreen.V6.Melee.ShipState.LiveVux (p0 |> migrate_Melee_ShipState_CombatantCore)
                (p1 |> migrate_Melee_ShipState_VuxExtra)

        Evergreen.V5.Melee.ShipState.LiveYehat p0 ->
            Evergreen.V6.Melee.ShipState.LiveYehat (p0 |> migrate_Melee_ShipState_CombatantCore)

        Evergreen.V5.Melee.ShipState.LiveZoqFotPik p0 ->
            Evergreen.V6.Melee.ShipState.LiveZoqFotPik (p0 |> migrate_Melee_ShipState_CombatantCore)


migrate_Melee_ShipState_CombatantCore : Evergreen.V5.Melee.ShipState.CombatantCore -> Evergreen.V6.Melee.ShipState.CombatantCore
migrate_Melee_ShipState_CombatantCore old =
    { element = old.element |> migrate_Melee_Id_ElementId
    , characteristics = old.characteristics |> migrate_Melee_Ship_Characteristics
    , energy = old.energy
    , maxEnergy = old.maxEnergy
    , maxCrew = old.maxCrew
    , weaponWait = old.weaponWait |> migrate_Melee_Units_Wait
    , specialWait = old.specialWait |> migrate_Melee_Units_Wait
    , energyWait = old.energyWait |> migrate_Melee_Units_Wait
    , facing = old.facing |> migrate_Melee_Units_Facing
    , input = old.input |> migrate_Melee_Input_BattleInput
    , shieldTicks = old.shieldTicks
    , confusedTicks = old.confusedTicks
    , chargeTicks = old.chargeTicks
    , cloaked = old.cloaked
    , oldInput = old.oldInput |> migrate_Melee_Input_BattleInput
    , flags = old.flags |> migrate_Melee_ShipState_MotionFlags
    }


migrate_Melee_ShipState_MelnormeExtra : Evergreen.V5.Melee.ShipState.MelnormeExtra -> Evergreen.V6.Melee.ShipState.MelnormeExtra
migrate_Melee_ShipState_MelnormeExtra old =
    { pump = old.pump |> migrate_Melee_ShipState_PumpLevel
    , levelCounter = old.levelCounter |> migrate_Melee_Units_Wait
    }


migrate_Melee_ShipState_MmrnmhrmExtra : Evergreen.V5.Melee.ShipState.MmrnmhrmExtra -> Evergreen.V6.Melee.ShipState.MmrnmhrmExtra
migrate_Melee_ShipState_MmrnmhrmExtra old =
    { form = old.form |> migrate_Melee_ShipState_MmrnmhrmForm
    , otherWing = old.otherWing |> migrate_Melee_Ship_Characteristics
    }


migrate_Melee_ShipState_MmrnmhrmForm : Evergreen.V5.Melee.ShipState.MmrnmhrmForm -> Evergreen.V6.Melee.ShipState.MmrnmhrmForm
migrate_Melee_ShipState_MmrnmhrmForm old =
    case old of
        Evergreen.V5.Melee.ShipState.XWing ->
            Evergreen.V6.Melee.ShipState.XWing

        Evergreen.V5.Melee.ShipState.YWing ->
            Evergreen.V6.Melee.ShipState.YWing


migrate_Melee_ShipState_MotionFlags : Evergreen.V5.Melee.ShipState.MotionFlags -> Evergreen.V6.Melee.ShipState.MotionFlags
migrate_Melee_ShipState_MotionFlags old =
    old


migrate_Melee_ShipState_OrzExtra : Evergreen.V5.Melee.ShipState.OrzExtra -> Evergreen.V6.Melee.ShipState.OrzExtra
migrate_Melee_ShipState_OrzExtra old =
    { turretFacing = old.turretFacing |> migrate_Melee_Units_Facing
    , turretWait = old.turretWait |> migrate_Melee_Units_Wait
    }


migrate_Melee_ShipState_PkunkExtra : Evergreen.V5.Melee.ShipState.PkunkExtra -> Evergreen.V6.Melee.ShipState.PkunkExtra
migrate_Melee_ShipState_PkunkExtra old =
    case old of
        Evergreen.V5.Melee.ShipState.Flying ->
            Evergreen.V6.Melee.ShipState.Flying

        Evergreen.V5.Melee.ShipState.Phoenix p0 ->
            Evergreen.V6.Melee.ShipState.Phoenix (p0 |> migrate_Melee_Id_ElementId)


migrate_Melee_ShipState_PumpLevel : Evergreen.V5.Melee.ShipState.PumpLevel -> Evergreen.V6.Melee.ShipState.PumpLevel
migrate_Melee_ShipState_PumpLevel old =
    case old of
        Evergreen.V5.Melee.ShipState.Pump1 ->
            Evergreen.V6.Melee.ShipState.Pump1

        Evergreen.V5.Melee.ShipState.Pump2 ->
            Evergreen.V6.Melee.ShipState.Pump2

        Evergreen.V5.Melee.ShipState.Pump3 ->
            Evergreen.V6.Melee.ShipState.Pump3

        Evergreen.V5.Melee.ShipState.Pump4 ->
            Evergreen.V6.Melee.ShipState.Pump4


migrate_Melee_ShipState_ShofixtiExtra : Evergreen.V5.Melee.ShipState.ShofixtiExtra -> Evergreen.V6.Melee.ShipState.ShofixtiExtra
migrate_Melee_ShipState_ShofixtiExtra old =
    case old of
        Evergreen.V5.Melee.ShipState.SafetyClosed ->
            Evergreen.V6.Melee.ShipState.SafetyClosed

        Evergreen.V5.Melee.ShipState.OpeningSafety ->
            Evergreen.V6.Melee.ShipState.OpeningSafety

        Evergreen.V5.Melee.ShipState.SafetyOpen ->
            Evergreen.V6.Melee.ShipState.SafetyOpen

        Evergreen.V5.Melee.ShipState.ArmingDevice ->
            Evergreen.V6.Melee.ShipState.ArmingDevice

        Evergreen.V5.Melee.ShipState.Armed ->
            Evergreen.V6.Melee.ShipState.Armed

        Evergreen.V5.Melee.ShipState.GloryDevice ->
            Evergreen.V6.Melee.ShipState.GloryDevice


migrate_Melee_ShipState_SupoxExtra : Evergreen.V5.Melee.ShipState.SupoxExtra -> Evergreen.V6.Melee.ShipState.SupoxExtra
migrate_Melee_ShipState_SupoxExtra old =
    case old of
        Evergreen.V5.Melee.ShipState.ForwardOnly ->
            Evergreen.V6.Melee.ShipState.ForwardOnly

        Evergreen.V5.Melee.ShipState.Strafing p0 ->
            Evergreen.V6.Melee.ShipState.Strafing (p0 |> migrate_Melee_Input_Turn)


migrate_Melee_ShipState_ThraddashExtra : Evergreen.V5.Melee.ShipState.ThraddashExtra -> Evergreen.V6.Melee.ShipState.ThraddashExtra
migrate_Melee_ShipState_ThraddashExtra old =
    case old of
        Evergreen.V5.Melee.ShipState.Cruise ->
            Evergreen.V6.Melee.ShipState.Cruise

        Evergreen.V5.Melee.ShipState.Afterburning p0 ->
            Evergreen.V6.Melee.ShipState.Afterburning p0


migrate_Melee_ShipState_UmgahExtra : Evergreen.V5.Melee.ShipState.UmgahExtra -> Evergreen.V6.Melee.ShipState.UmgahExtra
migrate_Melee_ShipState_UmgahExtra old =
    { prevFacing = old.prevFacing |> migrate_Melee_Units_Facing
    }


migrate_Melee_ShipState_VuxExtra : Evergreen.V5.Melee.ShipState.VuxExtra -> Evergreen.V6.Melee.ShipState.VuxExtra
migrate_Melee_ShipState_VuxExtra old =
    case old of
        Evergreen.V5.Melee.ShipState.WarpPending ->
            Evergreen.V6.Melee.ShipState.WarpPending

        Evergreen.V5.Melee.ShipState.OnField ->
            Evergreen.V6.Melee.ShipState.OnField


migrate_Melee_Ship_Characteristics : Evergreen.V5.Melee.Ship.Characteristics -> Evergreen.V6.Melee.Ship.Characteristics
migrate_Melee_Ship_Characteristics old =
    { maxThrust = old.maxThrust
    , thrustIncrement = old.thrustIncrement
    , energyRegeneration = old.energyRegeneration
    , weaponEnergyCost = old.weaponEnergyCost
    , specialEnergyCost = old.specialEnergyCost
    , energyWait = old.energyWait |> migrate_Melee_Units_Wait
    , turnWait = old.turnWait |> migrate_Melee_Units_Wait
    , thrustWait = old.thrustWait |> migrate_Melee_Units_Wait
    , weaponWait = old.weaponWait |> migrate_Melee_Units_Wait
    , specialWait = old.specialWait |> migrate_Melee_Units_Wait
    , shipMass = old.shipMass
    }


migrate_Melee_Ship_ShipKind : Evergreen.V5.Melee.Ship.ShipKind -> Evergreen.V6.Melee.Ship.ShipKind
migrate_Melee_Ship_ShipKind old =
    case old of
        Evergreen.V5.Melee.Ship.Androsynth ->
            Evergreen.V6.Melee.Ship.Androsynth

        Evergreen.V5.Melee.Ship.Arilou ->
            Evergreen.V6.Melee.Ship.Arilou

        Evergreen.V5.Melee.Ship.Chenjesu ->
            Evergreen.V6.Melee.Ship.Chenjesu

        Evergreen.V5.Melee.Ship.Chmmr ->
            Evergreen.V6.Melee.Ship.Chmmr

        Evergreen.V5.Melee.Ship.Druuge ->
            Evergreen.V6.Melee.Ship.Druuge

        Evergreen.V5.Melee.Ship.Earthling ->
            Evergreen.V6.Melee.Ship.Earthling

        Evergreen.V5.Melee.Ship.Ilwrath ->
            Evergreen.V6.Melee.Ship.Ilwrath

        Evergreen.V5.Melee.Ship.KohrAh ->
            Evergreen.V6.Melee.Ship.KohrAh

        Evergreen.V5.Melee.Ship.Melnorme ->
            Evergreen.V6.Melee.Ship.Melnorme

        Evergreen.V5.Melee.Ship.Mmrnmhrm ->
            Evergreen.V6.Melee.Ship.Mmrnmhrm

        Evergreen.V5.Melee.Ship.Mycon ->
            Evergreen.V6.Melee.Ship.Mycon

        Evergreen.V5.Melee.Ship.Orz ->
            Evergreen.V6.Melee.Ship.Orz

        Evergreen.V5.Melee.Ship.Pkunk ->
            Evergreen.V6.Melee.Ship.Pkunk

        Evergreen.V5.Melee.Ship.Shofixti ->
            Evergreen.V6.Melee.Ship.Shofixti

        Evergreen.V5.Melee.Ship.Slylandro ->
            Evergreen.V6.Melee.Ship.Slylandro

        Evergreen.V5.Melee.Ship.Spathi ->
            Evergreen.V6.Melee.Ship.Spathi

        Evergreen.V5.Melee.Ship.Supox ->
            Evergreen.V6.Melee.Ship.Supox

        Evergreen.V5.Melee.Ship.Syreen ->
            Evergreen.V6.Melee.Ship.Syreen

        Evergreen.V5.Melee.Ship.Thraddash ->
            Evergreen.V6.Melee.Ship.Thraddash

        Evergreen.V5.Melee.Ship.Umgah ->
            Evergreen.V6.Melee.Ship.Umgah

        Evergreen.V5.Melee.Ship.UrQuan ->
            Evergreen.V6.Melee.Ship.UrQuan

        Evergreen.V5.Melee.Ship.Utwig ->
            Evergreen.V6.Melee.Ship.Utwig

        Evergreen.V5.Melee.Ship.Vux ->
            Evergreen.V6.Melee.Ship.Vux

        Evergreen.V5.Melee.Ship.Yehat ->
            Evergreen.V6.Melee.Ship.Yehat

        Evergreen.V5.Melee.Ship.ZoqFotPik ->
            Evergreen.V6.Melee.Ship.ZoqFotPik


migrate_Melee_Telemetry_Client : Evergreen.V5.Melee.Telemetry.Client -> Evergreen.V6.Melee.Telemetry.Client
migrate_Melee_Telemetry_Client old =
    old


migrate_Melee_Units_Angle : Evergreen.V5.Melee.Units.Angle -> Evergreen.V6.Melee.Units.Angle
migrate_Melee_Units_Angle old =
    case old of
        Evergreen.V5.Melee.Units.Angle p0 ->
            Evergreen.V6.Melee.Units.Angle p0


migrate_Melee_Units_Facing : Evergreen.V5.Melee.Units.Facing -> Evergreen.V6.Melee.Units.Facing
migrate_Melee_Units_Facing old =
    case old of
        Evergreen.V5.Melee.Units.Facing p0 ->
            Evergreen.V6.Melee.Units.Facing p0


migrate_Melee_Units_FrameCount : Evergreen.V5.Melee.Units.FrameCount -> Evergreen.V6.Melee.Units.FrameCount
migrate_Melee_Units_FrameCount old =
    case old of
        Evergreen.V5.Melee.Units.FrameCount p0 ->
            Evergreen.V6.Melee.Units.FrameCount p0


migrate_Melee_Units_Side : Evergreen.V5.Melee.Units.Side -> Evergreen.V6.Melee.Units.Side
migrate_Melee_Units_Side old =
    case old of
        Evergreen.V5.Melee.Units.Bottom ->
            Evergreen.V6.Melee.Units.Bottom

        Evergreen.V5.Melee.Units.Top ->
            Evergreen.V6.Melee.Units.Top


migrate_Melee_Units_Sided : (a_old -> a_new) -> Evergreen.V5.Melee.Units.Sided a_old -> Evergreen.V6.Melee.Units.Sided a_new
migrate_Melee_Units_Sided migrate_a old =
    { bottom = old.bottom |> migrate_a
    , top = old.top |> migrate_a
    }


migrate_Melee_Units_VelocityDesc : Evergreen.V5.Melee.Units.VelocityDesc -> Evergreen.V6.Melee.Units.VelocityDesc
migrate_Melee_Units_VelocityDesc old =
    { travelAngle = old.travelAngle |> migrate_Melee_Units_Angle
    , vector = old.vector |> migrate_Melee_Units_WorldExtent
    , fract = old.fract |> migrate_Melee_Units_WorldExtent
    , error = old.error |> migrate_Melee_Units_WorldExtent
    , incr = old.incr |> migrate_Melee_Units_WorldExtent
    }


migrate_Melee_Units_Wait : Evergreen.V5.Melee.Units.Wait -> Evergreen.V6.Melee.Units.Wait
migrate_Melee_Units_Wait old =
    case old of
        Evergreen.V5.Melee.Units.Wait p0 ->
            Evergreen.V6.Melee.Units.Wait p0


migrate_Melee_Units_WorldExtent : Evergreen.V5.Melee.Units.WorldExtent -> Evergreen.V6.Melee.Units.WorldExtent
migrate_Melee_Units_WorldExtent old =
    old


migrate_Melee_Units_WorldPoint : Evergreen.V5.Melee.Units.WorldPoint -> Evergreen.V6.Melee.Units.WorldPoint
migrate_Melee_Units_WorldPoint old =
    old


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V5.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V6.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V5.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V6.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V5.OAuth.ErrorCode -> Evergreen.V6.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V5.OAuth.InvalidRequest ->
            Evergreen.V6.OAuth.InvalidRequest

        Evergreen.V5.OAuth.UnauthorizedClient ->
            Evergreen.V6.OAuth.UnauthorizedClient

        Evergreen.V5.OAuth.AccessDenied ->
            Evergreen.V6.OAuth.AccessDenied

        Evergreen.V5.OAuth.UnsupportedResponseType ->
            Evergreen.V6.OAuth.UnsupportedResponseType

        Evergreen.V5.OAuth.InvalidScope ->
            Evergreen.V6.OAuth.InvalidScope

        Evergreen.V5.OAuth.ServerError ->
            Evergreen.V6.OAuth.ServerError

        Evergreen.V5.OAuth.TemporarilyUnavailable ->
            Evergreen.V6.OAuth.TemporarilyUnavailable

        Evergreen.V5.OAuth.Custom p0 ->
            Evergreen.V6.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V5.OAuth.Token -> Evergreen.V6.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V5.OAuth.Bearer p0 ->
            Evergreen.V6.OAuth.Bearer p0


migrate_Types_AdminLogsUrlParams : Evergreen.V5.Types.AdminLogsUrlParams -> Evergreen.V6.Types.AdminLogsUrlParams
migrate_Types_AdminLogsUrlParams old =
    old


migrate_Types_AdminPageModel : Evergreen.V5.Types.AdminPageModel -> Evergreen.V6.Types.AdminPageModel
migrate_Types_AdminPageModel old =
    { logs = old.logs |> List.map migrate_Logger_LogEntry
    , isAuthenticated = old.isAuthenticated
    , remoteUrl = old.remoteUrl
    }


migrate_Types_AdminRoute : Evergreen.V5.Types.AdminRoute -> Evergreen.V6.Types.AdminRoute
migrate_Types_AdminRoute old =
    case old of
        Evergreen.V5.Types.AdminDefault ->
            Evergreen.V6.Types.AdminDefault

        Evergreen.V5.Types.AdminLogs p0 ->
            Evergreen.V6.Types.AdminLogs (p0 |> migrate_Types_AdminLogsUrlParams)

        Evergreen.V5.Types.AdminFetchModel ->
            Evergreen.V6.Types.AdminFetchModel


migrate_Types_EmailPasswordFormModel : Evergreen.V5.Types.EmailPasswordFormModel -> Evergreen.V6.Types.EmailPasswordFormModel
migrate_Types_EmailPasswordFormModel old =
    old


migrate_Types_LoginState : Evergreen.V5.Types.LoginState -> Evergreen.V6.Types.LoginState
migrate_Types_LoginState old =
    case old of
        Evergreen.V5.Types.JustArrived ->
            Evergreen.V6.Types.JustArrived

        Evergreen.V5.Types.NotLogged p0 ->
            Evergreen.V6.Types.NotLogged p0

        Evergreen.V5.Types.LoginTokenSent ->
            Evergreen.V6.Types.LoginTokenSent

        Evergreen.V5.Types.LoggedIn p0 ->
            Evergreen.V6.Types.LoggedIn (p0 |> migrate_Auth_Common_UserInfo)


migrate_Types_Preferences : Evergreen.V5.Types.Preferences -> Evergreen.V6.Types.Preferences
migrate_Types_Preferences old =
    old


migrate_Types_Route : Evergreen.V5.Types.Route -> Evergreen.V6.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V5.Types.Default ->
            Evergreen.V6.Types.Default

        Evergreen.V5.Types.Admin p0 ->
            Evergreen.V6.Types.Admin (p0 |> migrate_Types_AdminRoute)

        Evergreen.V5.Types.Examples ->
            Evergreen.V6.Types.Examples

        Evergreen.V5.Types.Melee ->
            Evergreen.V6.Types.Melee

        Evergreen.V5.Types.Metrics ->
            Evergreen.V6.Types.Metrics

        Evergreen.V5.Types.NotFound ->
            Evergreen.V6.Types.NotFound
