#!/usr/bin/env node
// Generates rust/crates/melee-sim/src/catalog_generated.rs from the Elm
// catalog dump, so the Rust tables are derived from Melee.Ship / Melee.Arsenal
// rather than transcribed. Run scripts/oracle/gen.sh, never hand-edit output.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const cat = JSON.parse(readFileSync(join(root, "artifacts/oracle/catalog.json"), "utf8"));
const MAX_MOUNTS = 8;

const abilityFields = [
  ["seekingWeapon", "seeking_weapon"], ["seekingSpecial", "seeking_special"],
  ["pointDefense", "point_defense"], ["immediateWeapon", "immediate_weapon"],
  ["crewImmune", "crew_immune"], ["firesFore", "fires_fore"],
  ["firesRight", "fires_right"], ["firesAft", "fires_aft"],
  ["firesLeft", "fires_left"], ["shieldDefense", "shield_defense"],
  ["dontChase", "dont_chase"],
];
const charFields = [
  ["maxThrust", "max_thrust"], ["thrustIncrement", "thrust_increment"],
  ["energyRegeneration", "energy_regeneration"], ["weaponEnergyCost", "weapon_energy_cost"],
  ["specialEnergyCost", "special_energy_cost"], ["energyWait", "energy_wait"],
  ["turnWait", "turn_wait"], ["thrustWait", "thrust_wait"],
  ["weaponWait", "weapon_wait"], ["specialWait", "special_wait"],
  ["shipMass", "ship_mass"],
];

const ability = (a) =>
  `Ability { ${abilityFields.map(([j, r]) => `${r}: ${a[j]}`).join(", ")} }`;
const chars = (c) =>
  `Characteristics { ${charFields.map(([j, r]) => `${r}: ${c[j]}`).join(", ")} }`;

const guidance = (g) => {
  switch (g.tag) {
    case "ballistic": return "Guidance::Ballistic";
    case "tracking": return `Guidance::Tracking { wait: ${g.wait}, initial_wait: ${g.initialWait} }`;
    case "bubble": return "Guidance::BubbleFlight";
    case "heldBlade": return "Guidance::HeldBlade";
    default: throw new Error(`unknown guidance ${g.tag}`);
  }
};
const animation = (a) => {
  switch (a.tag) {
    case "directional": return "Animation::Directional";
    case "frames": return `Animation::Frames { count: ${a.count}, ticks: ${a.ticks} }`;
    case "plasmaDecay": return "Animation::PlasmaDecay";
    case "chargeLevel": return "Animation::ChargeLevel";
    default: throw new Error(`unknown animation ${a.tag}`);
  }
};
const weapon = (w) => {
  switch (w.tag) {
    case "missile": return `Weapon::Missile(MissileKind::${w.missile})`;
    case "beam": return `Weapon::Beam(BeamKind::${w.beam})`;
    case "contact": return `Weapon::Contact(ContactKind::${w.contact})`;
    case "lightning": return "Weapon::Lightning";
    default: throw new Error(`unknown weapon ${w.tag}`);
  }
};

const mounts = (ms) => {
  if (ms.length > MAX_MOUNTS) throw new Error(`mount overflow: ${ms.length}`);
  const filled = ms.map(
    (m) => `Mount { forward: ${m.forward}, sideways: ${m.sideways}, facing_offset: ${m.facingOffset} }`
  );
  while (filled.length < MAX_MOUNTS) filled.push("Mount { forward: 0, sideways: 0, facing_offset: 0 }");
  return `[${filled.join(", ")}]`;
};

const L = [];
L.push("//! GENERATED by scripts/oracle/gen-catalog.mjs from the Elm catalog dump.");
L.push("//! Source of truth: src/Melee/Ship.elm, src/Melee/Arsenal.elm, src/Melee/Catalog.elm.");
L.push("//! Do not edit; run `bash scripts/oracle/gen.sh` instead.");
L.push("");
L.push("#![allow(clippy::all)]");
L.push("");
L.push("use crate::catalog::*;");
L.push("use crate::element::Body;");
L.push("");

L.push(`pub const SHIP_NAMES: [&str; ${cat.ships.length}] = [`);
for (const s of cat.ships) L.push(`    ${JSON.stringify(s.name)},`);
L.push("];");
L.push("");

L.push(`pub const SHIP_VESSELS: [&str; ${cat.ships.length}] = [`);
for (const s of cat.ships) L.push(`    ${JSON.stringify(s.vessel)},`);
L.push("];");
L.push("");

L.push(`pub const INTEL_RANGE: [i64; ${cat.ships.length}] = [`);
L.push(`    ${cat.ships.map((s) => s.intelRange).join(", ")},`);
L.push("];");
L.push("");

L.push(`pub const STOCK: [Stock; ${cat.ships.length}] = [`);
for (const s of cat.ships) {
  L.push("    Stock {");
  L.push(`        kind: ShipKind::${s.kind},`);
  L.push(`        cost: ${s.cost},`);
  L.push(`        max_crew: ${s.maxCrew},`);
  L.push(`        max_energy: ${s.maxEnergy},`);
  L.push(`        starting_crew: ${s.startingCrew},`);
  L.push(`        starting_energy: ${s.startingEnergy},`);
  L.push(`        ability: ${ability(s.ability)},`);
  L.push(`        characteristics: ${chars(s.characteristics)},`);
  L.push("    },");
}
L.push("];");
L.push("");

L.push(`pub const STANDARD_WEAPON: [Weapon; ${cat.ships.length}] = [`);
for (const s of cat.ships) L.push(`    ${weapon(s.weapon)},`);
L.push("];");
L.push("");

L.push(`pub const MMRNMHRM_Y_WING: Characteristics = ${chars(cat.mmrnmhrmYWing)};`);
L.push("");

L.push(`pub const MISSILE_SPECS: [MissileSpec; ${cat.missiles.length}] = [`);
for (const m of cat.missiles) {
  if (m.kind !== m.requested) throw new Error(`spec ${m.requested} returns kind ${m.kind}`);
  L.push("    MissileSpec {");
  L.push(`        kind: MissileKind::${m.kind},`);
  L.push(`        speed: ${m.speed},`);
  L.push(`        life: ${m.life},`);
  L.push(`        damage: ${m.damage},`);
  L.push(`        hit_points: ${m.hitPoints},`);
  L.push(`        guidance: ${guidance(m.guidance)},`);
  L.push(`        animation: ${animation(m.animation)},`);
  L.push(`        inheritance: Inheritance::${m.inheritance},`);
  L.push(`        blast_offset: ${m.blastOffset},`);
  L.push(`        friendly_fire: ${m.friendlyFire},`);
  L.push(`        direction_count: ${m.directions.length},`);
  L.push(`        mount_count: ${m.mounts.length},`);
  L.push(`        mounts: ${mounts(m.mounts)},`);
  L.push("    },");
}
L.push("];");
L.push("");

// Body identity for each missile / beam kind, so spawn code never guesses.
L.push(`pub const MISSILE_BODY: [Body; ${cat.missiles.length}] = [`);
for (const m of cat.missiles) L.push(`    Body::${m.body},`);
L.push("];");
L.push("");
L.push(`pub const MISSILE_HOMING: [bool; ${cat.missiles.length}] = [`);
L.push(`    ${cat.missiles.map((m) => m.homing).join(", ")},`);
L.push("];");
L.push("");
L.push(`pub const BEAM_BODY: [Body; ${cat.beams.length}] = [`);
for (const b of cat.beams) L.push(`    Body::${b.body},`);
L.push("];");
L.push("");

writeFileSync(join(root, "rust/crates/melee-sim/src/catalog_generated.rs"), L.join("\n") + "\n");
console.log(
  `catalog_generated.rs: ${cat.ships.length} ships, ${cat.missiles.length} missiles, ${cat.beams.length} beams`
);
