#!/usr/bin/env node
// Generates rust/crates/melee-sim/src/masks_generated.rs from the Elm mask dump.
// Sprite paths are resolved at generation time, so the Rust collision path is
// pure integer indexing: (body, frame) and (kind, variant, facing) -> mask id.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const dump = JSON.parse(readFileSync(join(root, "artifacts/oracle/masks.json"), "utf8"));

const MAX_FRAMES = dump.projectiles[0].frames.length;

// Deduplicate mask bodies; identical sprites across frames are common.
const maskIds = new Map();
const masks = [];
const rows = []; // [spanStart, spanLen]
const spans = []; // [a, b]

function intern(mask) {
  if (mask === null) return -1;
  const key = JSON.stringify(mask);
  const seen = maskIds.get(key);
  if (seen !== undefined) return seen;
  const rowStart = rows.length;
  for (const row of mask.rows) {
    const spanStart = spans.length;
    for (const [a, b] of row) spans.push([a, b]);
    rows.push([spanStart, row.length]);
  }
  const id = masks.length;
  masks.push({
    width: mask.width,
    height: mask.height,
    x: mask.x,
    y: mask.y,
    rowStart,
    rowCount: mask.rows.length,
  });
  maskIds.set(key, id);
  return id;
}

const projectileTags = dump.projectiles.map((p) => p.body);
const projectileTable = dump.projectiles.map((p) => p.frames.map(intern));

const SHIP_ORDER = [
  "Androsynth", "Arilou", "Chenjesu", "Chmmr", "Druuge", "Earthling", "Ilwrath",
  "KohrAh", "Melnorme", "Mmrnmhrm", "Mycon", "Orz", "Pkunk", "Shofixti",
  "Slylandro", "Spathi", "Supox", "Syreen", "Thraddash", "Umgah", "UrQuan",
  "Utwig", "Vux", "Yehat", "ZoqFotPik",
];
const shipTable = SHIP_ORDER.map((kind) => {
  const normal = dump.ships.find((s) => s.kind === kind && s.variant === "normal");
  const alt = dump.ships.find((s) => s.kind === kind && s.variant === "alt") || normal;
  if (!normal) throw new Error(`no mask row for ${kind}`);
  return [normal.facings.map(intern), alt.facings.map(intern)];
});

// Body -> projectile sprite row. Payload-carrying bodies are matched on their
// payload where the sprite depends on it (weapon impacts) and ignored where it
// does not (the Chmmr satellite's orbit facing).
function bodyPattern(tag) {
  if (tag.startsWith("WeaponImpact:")) {
    return `Body::WeaponImpact(MissileKind::${tag.slice("WeaponImpact:".length)})`;
  }
  if (tag === "ChmmrSatellite") return "Body::ChmmrSatellite { .. }";
  return `Body::${tag}`;
}

const L = [];
L.push("//! GENERATED by scripts/oracle/gen-masks.mjs from the Elm mask dump.");
L.push("//! Source of truth: src/Melee/Masks.elm, src/Melee/Art.elm, src/Melee/Catalog.elm.");
L.push("//! Do not edit; run `bash scripts/oracle/gen.sh` instead.");
L.push("");
L.push("#![allow(clippy::all)]");
L.push("");
L.push("use crate::catalog::{MissileKind, ShipKind};");
L.push("use crate::element::Body;");
L.push("use crate::masks::Mask;");
L.push("");
L.push(`/// \`Melee.Masks.maximumDimension\`.`);
L.push(`pub const MAXIMUM_DIMENSION: i64 = ${dump.maximumDimension};`);
L.push(`/// Widest frame index the sprite tables answer for.`);
L.push(`pub const MAX_FRAMES: usize = ${MAX_FRAMES};`);
L.push("/// Sentinel for \"this sprite has no collision mask\" (circle fallback).");
L.push("pub const NO_MASK: i32 = -1;");
L.push("");

L.push(`pub const MASKS: [Mask; ${masks.length}] = [`);
for (const m of masks) {
  L.push(
    `    Mask { width: ${m.width}, height: ${m.height}, x: ${m.x}, y: ${m.y}, row_start: ${m.rowStart}, row_count: ${m.rowCount} },`
  );
}
L.push("];");
L.push("");

L.push(`/// (span_start, span_len) per mask row, indexed by \`Mask::row_start + y\`.`);
L.push(`pub const MASK_ROWS: [(u32, u32); ${rows.length}] = [`);
for (let i = 0; i < rows.length; i += 8) {
  L.push("    " + rows.slice(i, i + 8).map(([a, b]) => `(${a}, ${b})`).join(", ") + ",");
}
L.push("];");
L.push("");

L.push(`/// Inclusive \`(from, to)\` opaque pixel spans.`);
L.push(`pub const MASK_SPANS: [(i16, i16); ${spans.length}] = [`);
for (let i = 0; i < spans.length; i += 12) {
  L.push("    " + spans.slice(i, i + 12).map(([a, b]) => `(${a}, ${b})`).join(", ") + ",");
}
L.push("];");
L.push("");

L.push(`const PROJECTILE_MASK: [[i32; ${MAX_FRAMES}]; ${projectileTable.length}] = [`);
for (const frames of projectileTable) {
  L.push(`    [${frames.join(", ")}],`);
}
L.push("];");
L.push("");

L.push(`const SHIP_MASK: [[[i32; 16]; 2]; ${shipTable.length}] = [`);
for (const [normal, alt] of shipTable) {
  L.push(`    [[${normal.join(", ")}], [${alt.join(", ")}]],`);
}
L.push("];");
L.push("");

L.push("/// Row index into `PROJECTILE_MASK` for a body, or `None` when the body has");
L.push("/// no sprite at all (`Melee.Art.projectile` returning `Nothing`).");
L.push("pub fn projectile_row(body: Body) -> Option<usize> {");
L.push("    Some(match body {");
for (let i = 0; i < projectileTags.length; i += 1) {
  L.push(`        ${bodyPattern(projectileTags[i])} => ${i},`);
}
L.push("        _ => return None,");
L.push("    })");
L.push("}");
L.push("");
L.push("/// Mask for a non-ship body at `frame_index`, matching `Art.projectile`.");
L.push("#[inline]");
L.push("pub fn projectile_mask(body: Body, frame_index: i64) -> Option<&'static Mask> {");
L.push("    let row = projectile_row(body)?;");
L.push("    if frame_index < 0 || frame_index >= MAX_FRAMES as i64 {");
L.push("        return None;");
L.push("    }");
L.push("    let id = PROJECTILE_MASK[row][frame_index as usize];");
L.push("    if id == NO_MASK { None } else { Some(&MASKS[id as usize]) }");
L.push("}");
L.push("");
L.push("/// Mask for a ship sprite. `alt` selects the Androsynth blazer strip and the");
L.push("/// Mmrnmhrm Y-wing strip; every other ship ignores it.");
L.push("#[inline]");
L.push("pub fn ship_mask(kind: ShipKind, alt: bool, facing: i64) -> Option<&'static Mask> {");
L.push("    let id = SHIP_MASK[kind.index()][alt as usize][facing.rem_euclid(16) as usize];");
L.push("    if id == NO_MASK { None } else { Some(&MASKS[id as usize]) }");
L.push("}");
L.push("");

writeFileSync(join(root, "rust/crates/melee-sim/src/masks_generated.rs"), L.join("\n") + "\n");
console.log(
  `masks_generated.rs: ${masks.length} masks, ${rows.length} rows, ${spans.length} spans, ` +
    `${projectileTable.length} projectile bodies, ${shipTable.length} ships`
);
